"""Order-independent fixed-seed payload generation."""

from __future__ import annotations

import base64
import hashlib
import hmac
from typing import Final, TypedDict

DEFAULT_SEED: Final[int] = 0x474F525449
_PERSONALIZATION: Final[bytes] = b"gorti.verification.payload/v1\x00"
_MAX_U64: Final[int] = (1 << 64) - 1


class PayloadEnvelope(TypedDict):
    """PayloadEnvelope is the JSON-safe representation of generated bytes."""

    encoding: str
    size: int
    sha256: str
    data: str


def _validate_inputs(seed: int, stream: str, index: int, size: int) -> bytes:
    if isinstance(seed, bool) or not isinstance(seed, int) or not 0 <= seed <= _MAX_U64:
        raise ValueError("seed must be an unsigned 64-bit integer")
    if not isinstance(stream, str) or not stream:
        raise ValueError("stream must be a non-empty string")
    stream_bytes = stream.encode("utf-8")
    if len(stream_bytes) > 65535:
        raise ValueError("UTF-8 stream name must be at most 65535 bytes")
    if isinstance(index, bool) or not isinstance(index, int) or not 0 <= index <= _MAX_U64:
        raise ValueError("index must be an unsigned 64-bit integer")
    if isinstance(size, bool) or not isinstance(size, int) or size < 0:
        raise ValueError("size must be a non-negative integer")
    return stream_bytes


def generate_payload(
    size: int,
    *,
    seed: int = DEFAULT_SEED,
    stream: str = "default",
    index: int = 0,
) -> bytes:
    """Generate stable bytes addressed by seed, stream, index, and size."""
    stream_bytes = _validate_inputs(seed, stream, index, size)
    prefix = b"".join(
        (
            _PERSONALIZATION,
            seed.to_bytes(8, "big"),
            len(stream_bytes).to_bytes(2, "big"),
            stream_bytes,
            index.to_bytes(8, "big"),
        )
    )
    output = bytearray()
    block = 0
    while len(output) < size:
        output.extend(hashlib.sha256(prefix + block.to_bytes(8, "big")).digest())
        block += 1
    return bytes(output[:size])


def payload_envelope(
    size: int,
    *,
    seed: int = DEFAULT_SEED,
    stream: str = "default",
    index: int = 0,
) -> PayloadEnvelope:
    """Generate a base64 payload with explicit size and digest metadata."""
    payload = generate_payload(size, seed=seed, stream=stream, index=index)
    return {
        "encoding": "base64",
        "size": len(payload),
        "sha256": hashlib.sha256(payload).hexdigest(),
        "data": base64.b64encode(payload).decode("ascii"),
    }


def verify_payload_envelope(envelope: PayloadEnvelope) -> bytes:
    """Decode an envelope and verify its declared size and SHA-256 digest."""
    if envelope.get("encoding") != "base64":
        raise ValueError("payload encoding must be 'base64'")
    try:
        payload = base64.b64decode(envelope["data"], validate=True)
    except (ValueError, KeyError) as error:
        raise ValueError("payload data is not valid base64") from error
    if len(payload) != envelope.get("size"):
        raise ValueError("payload size does not match decoded data")
    digest = hashlib.sha256(payload).hexdigest()
    if not hmac.compare_digest(digest, envelope.get("sha256", "")):
        raise ValueError("payload SHA-256 does not match decoded data")
    return payload
