// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: rti/v1/admin_mutating.proto

package rtiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MutatingProbeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WireVersion   WireVersion            `protobuf:"varint,1,opt,name=wire_version,json=wireVersion,proto3,enum=rti.v1.WireVersion" json:"wire_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MutatingProbeRequest) Reset() {
	*x = MutatingProbeRequest{}
	mi := &file_rti_v1_admin_mutating_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MutatingProbeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutatingProbeRequest) ProtoMessage() {}

func (x *MutatingProbeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_admin_mutating_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MutatingProbeRequest.ProtoReflect.Descriptor instead.
func (*MutatingProbeRequest) Descriptor() ([]byte, []int) {
	return file_rti_v1_admin_mutating_proto_rawDescGZIP(), []int{0}
}

func (x *MutatingProbeRequest) GetWireVersion() WireVersion {
	if x != nil {
		return x.WireVersion
	}
	return WireVersion_WIRE_VERSION_UNSPECIFIED
}

type MutatingProbeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// rtid_version is the build identifier of the running daemon.
	RtidVersion string `protobuf:"bytes,1,opt,name=rtid_version,json=rtidVersion,proto3" json:"rtid_version,omitempty"`
	// mutating_enabled is always true on a successful probe — the field
	// exists for forward compatibility (a future cut may register a
	// disabled stub that returns false instead of Unimplemented).
	MutatingEnabled bool `protobuf:"varint,2,opt,name=mutating_enabled,json=mutatingEnabled,proto3" json:"mutating_enabled,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MutatingProbeResponse) Reset() {
	*x = MutatingProbeResponse{}
	mi := &file_rti_v1_admin_mutating_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MutatingProbeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutatingProbeResponse) ProtoMessage() {}

func (x *MutatingProbeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_admin_mutating_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MutatingProbeResponse.ProtoReflect.Descriptor instead.
func (*MutatingProbeResponse) Descriptor() ([]byte, []int) {
	return file_rti_v1_admin_mutating_proto_rawDescGZIP(), []int{1}
}

func (x *MutatingProbeResponse) GetRtidVersion() string {
	if x != nil {
		return x.RtidVersion
	}
	return ""
}

func (x *MutatingProbeResponse) GetMutatingEnabled() bool {
	if x != nil {
		return x.MutatingEnabled
	}
	return false
}

type ForceResignRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	WireVersion WireVersion            `protobuf:"varint,1,opt,name=wire_version,json=wireVersion,proto3,enum=rti.v1.WireVersion" json:"wire_version,omitempty"`
	// federation_name is the federation hosting the federate.
	FederationName string `protobuf:"bytes,2,opt,name=federation_name,json=federationName,proto3" json:"federation_name,omitempty"`
	// federate_handle is the federate to evict.
	FederateHandle uint64 `protobuf:"varint,3,opt,name=federate_handle,json=federateHandle,proto3" json:"federate_handle,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ForceResignRequest) Reset() {
	*x = ForceResignRequest{}
	mi := &file_rti_v1_admin_mutating_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForceResignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForceResignRequest) ProtoMessage() {}

func (x *ForceResignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_admin_mutating_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForceResignRequest.ProtoReflect.Descriptor instead.
func (*ForceResignRequest) Descriptor() ([]byte, []int) {
	return file_rti_v1_admin_mutating_proto_rawDescGZIP(), []int{2}
}

func (x *ForceResignRequest) GetWireVersion() WireVersion {
	if x != nil {
		return x.WireVersion
	}
	return WireVersion_WIRE_VERSION_UNSPECIFIED
}

func (x *ForceResignRequest) GetFederationName() string {
	if x != nil {
		return x.FederationName
	}
	return ""
}

func (x *ForceResignRequest) GetFederateHandle() uint64 {
	if x != nil {
		return x.FederateHandle
	}
	return 0
}

type ForceResignResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// already_resigned is true when the federate had already left the
	// federation between the operator's confirmation prompt and the
	// RPC arriving. The handler treats this as success-equivalent so
	// rti-top can render the same "OK" status either way.
	AlreadyResigned bool `protobuf:"varint,1,opt,name=already_resigned,json=alreadyResigned,proto3" json:"already_resigned,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ForceResignResponse) Reset() {
	*x = ForceResignResponse{}
	mi := &file_rti_v1_admin_mutating_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForceResignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForceResignResponse) ProtoMessage() {}

func (x *ForceResignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_admin_mutating_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForceResignResponse.ProtoReflect.Descriptor instead.
func (*ForceResignResponse) Descriptor() ([]byte, []int) {
	return file_rti_v1_admin_mutating_proto_rawDescGZIP(), []int{3}
}

func (x *ForceResignResponse) GetAlreadyResigned() bool {
	if x != nil {
		return x.AlreadyResigned
	}
	return false
}

type AdminDestroyFederationRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	WireVersion WireVersion            `protobuf:"varint,1,opt,name=wire_version,json=wireVersion,proto3,enum=rti.v1.WireVersion" json:"wire_version,omitempty"`
	// federation_name is the federation to destroy.
	FederationName string `protobuf:"bytes,2,opt,name=federation_name,json=federationName,proto3" json:"federation_name,omitempty"`
	// Fences a delayed administrative command from a replacement execution.
	ExpectedFederationGeneration *uint64 `protobuf:"varint,4,opt,name=expected_federation_generation,json=expectedFederationGeneration,proto3,oneof" json:"expected_federation_generation,omitempty"`
	// evict_joined_federates is true when the operator asked the
	// handler to first force-resign every joined federate before
	// destroying. False (the default) instructs the handler to refuse
	// when any federate is still joined, matching the federate-facing
	// DestroyFederation contract (FR-FM-5).
	EvictJoinedFederates bool `protobuf:"varint,3,opt,name=evict_joined_federates,json=evictJoinedFederates,proto3" json:"evict_joined_federates,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *AdminDestroyFederationRequest) Reset() {
	*x = AdminDestroyFederationRequest{}
	mi := &file_rti_v1_admin_mutating_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminDestroyFederationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminDestroyFederationRequest) ProtoMessage() {}

func (x *AdminDestroyFederationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_admin_mutating_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminDestroyFederationRequest.ProtoReflect.Descriptor instead.
func (*AdminDestroyFederationRequest) Descriptor() ([]byte, []int) {
	return file_rti_v1_admin_mutating_proto_rawDescGZIP(), []int{4}
}

func (x *AdminDestroyFederationRequest) GetWireVersion() WireVersion {
	if x != nil {
		return x.WireVersion
	}
	return WireVersion_WIRE_VERSION_UNSPECIFIED
}

func (x *AdminDestroyFederationRequest) GetFederationName() string {
	if x != nil {
		return x.FederationName
	}
	return ""
}

func (x *AdminDestroyFederationRequest) GetExpectedFederationGeneration() uint64 {
	if x != nil && x.ExpectedFederationGeneration != nil {
		return *x.ExpectedFederationGeneration
	}
	return 0
}

func (x *AdminDestroyFederationRequest) GetEvictJoinedFederates() bool {
	if x != nil {
		return x.EvictJoinedFederates
	}
	return false
}

type AdminDestroyFederationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// evicted_handles lists the federate handles the handler had to
	// force-resign before destroying (empty when
	// evict_joined_federates was false or the federation was already
	// empty).
	EvictedHandles []uint64 `protobuf:"varint,1,rep,packed,name=evicted_handles,json=evictedHandles,proto3" json:"evicted_handles,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AdminDestroyFederationResponse) Reset() {
	*x = AdminDestroyFederationResponse{}
	mi := &file_rti_v1_admin_mutating_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminDestroyFederationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminDestroyFederationResponse) ProtoMessage() {}

func (x *AdminDestroyFederationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_admin_mutating_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminDestroyFederationResponse.ProtoReflect.Descriptor instead.
func (*AdminDestroyFederationResponse) Descriptor() ([]byte, []int) {
	return file_rti_v1_admin_mutating_proto_rawDescGZIP(), []int{5}
}

func (x *AdminDestroyFederationResponse) GetEvictedHandles() []uint64 {
	if x != nil {
		return x.EvictedHandles
	}
	return nil
}

// PromoteFederationRequest — M16.1 demo. “target_node_id“ is the
// cluster node that should host the federation after the promote
// completes. The receiving rtid validates that the target is a
// known peer (via cluster.Manager) and rejects with InvalidArgument
// if not.
type PromoteFederationRequest struct {
	state                        protoimpl.MessageState `protogen:"open.v1"`
	WireVersion                  WireVersion            `protobuf:"varint,1,opt,name=wire_version,json=wireVersion,proto3,enum=rti.v1.WireVersion" json:"wire_version,omitempty"`
	FederationName               string                 `protobuf:"bytes,2,opt,name=federation_name,json=federationName,proto3" json:"federation_name,omitempty"`
	ExpectedFederationGeneration *uint64                `protobuf:"varint,4,opt,name=expected_federation_generation,json=expectedFederationGeneration,proto3,oneof" json:"expected_federation_generation,omitempty"`
	TargetNodeId                 string                 `protobuf:"bytes,3,opt,name=target_node_id,json=targetNodeId,proto3" json:"target_node_id,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *PromoteFederationRequest) Reset() {
	*x = PromoteFederationRequest{}
	mi := &file_rti_v1_admin_mutating_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromoteFederationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromoteFederationRequest) ProtoMessage() {}

func (x *PromoteFederationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_admin_mutating_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromoteFederationRequest.ProtoReflect.Descriptor instead.
func (*PromoteFederationRequest) Descriptor() ([]byte, []int) {
	return file_rti_v1_admin_mutating_proto_rawDescGZIP(), []int{6}
}

func (x *PromoteFederationRequest) GetWireVersion() WireVersion {
	if x != nil {
		return x.WireVersion
	}
	return WireVersion_WIRE_VERSION_UNSPECIFIED
}

func (x *PromoteFederationRequest) GetFederationName() string {
	if x != nil {
		return x.FederationName
	}
	return ""
}

func (x *PromoteFederationRequest) GetExpectedFederationGeneration() uint64 {
	if x != nil && x.ExpectedFederationGeneration != nil {
		return *x.ExpectedFederationGeneration
	}
	return 0
}

func (x *PromoteFederationRequest) GetTargetNodeId() string {
	if x != nil {
		return x.TargetNodeId
	}
	return ""
}

// PromoteFederationResponse carries the prior host's node_id so
// the operator can verify the swap. Empty prior_node_id means the
// federation had no prior assignment (newly promoted).
type PromoteFederationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PriorNodeId   string                 `protobuf:"bytes,1,opt,name=prior_node_id,json=priorNodeId,proto3" json:"prior_node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromoteFederationResponse) Reset() {
	*x = PromoteFederationResponse{}
	mi := &file_rti_v1_admin_mutating_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromoteFederationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromoteFederationResponse) ProtoMessage() {}

func (x *PromoteFederationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_admin_mutating_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromoteFederationResponse.ProtoReflect.Descriptor instead.
func (*PromoteFederationResponse) Descriptor() ([]byte, []int) {
	return file_rti_v1_admin_mutating_proto_rawDescGZIP(), []int{7}
}

func (x *PromoteFederationResponse) GetPriorNodeId() string {
	if x != nil {
		return x.PriorNodeId
	}
	return ""
}

var File_rti_v1_admin_mutating_proto protoreflect.FileDescriptor

const file_rti_v1_admin_mutating_proto_rawDesc = "" +
	"\n" +
	"\x1brti/v1/admin_mutating.proto\x12\x06rti.v1\x1a\x13rti/v1/common.proto\"N\n" +
	"\x14MutatingProbeRequest\x126\n" +
	"\fwire_version\x18\x01 \x01(\x0e2\x13.rti.v1.WireVersionR\vwireVersion\"e\n" +
	"\x15MutatingProbeResponse\x12!\n" +
	"\frtid_version\x18\x01 \x01(\tR\vrtidVersion\x12)\n" +
	"\x10mutating_enabled\x18\x02 \x01(\bR\x0fmutatingEnabled\"\x9e\x01\n" +
	"\x12ForceResignRequest\x126\n" +
	"\fwire_version\x18\x01 \x01(\x0e2\x13.rti.v1.WireVersionR\vwireVersion\x12'\n" +
	"\x0ffederation_name\x18\x02 \x01(\tR\x0efederationName\x12'\n" +
	"\x0ffederate_handle\x18\x03 \x01(\x04R\x0efederateHandle\"@\n" +
	"\x13ForceResignResponse\x12)\n" +
	"\x10already_resigned\x18\x01 \x01(\bR\x0falreadyResigned\"\xa4\x02\n" +
	"\x1dAdminDestroyFederationRequest\x126\n" +
	"\fwire_version\x18\x01 \x01(\x0e2\x13.rti.v1.WireVersionR\vwireVersion\x12'\n" +
	"\x0ffederation_name\x18\x02 \x01(\tR\x0efederationName\x12I\n" +
	"\x1eexpected_federation_generation\x18\x04 \x01(\x04H\x00R\x1cexpectedFederationGeneration\x88\x01\x01\x124\n" +
	"\x16evict_joined_federates\x18\x03 \x01(\bR\x14evictJoinedFederatesB!\n" +
	"\x1f_expected_federation_generation\"I\n" +
	"\x1eAdminDestroyFederationResponse\x12'\n" +
	"\x0fevicted_handles\x18\x01 \x03(\x04R\x0eevictedHandles\"\x8f\x02\n" +
	"\x18PromoteFederationRequest\x126\n" +
	"\fwire_version\x18\x01 \x01(\x0e2\x13.rti.v1.WireVersionR\vwireVersion\x12'\n" +
	"\x0ffederation_name\x18\x02 \x01(\tR\x0efederationName\x12I\n" +
	"\x1eexpected_federation_generation\x18\x04 \x01(\x04H\x00R\x1cexpectedFederationGeneration\x88\x01\x01\x12$\n" +
	"\x0etarget_node_id\x18\x03 \x01(\tR\ftargetNodeIdB!\n" +
	"\x1f_expected_federation_generation\"?\n" +
	"\x19PromoteFederationResponse\x12\"\n" +
	"\rprior_node_id\x18\x01 \x01(\tR\vpriorNodeId2\xdd\x02\n" +
	"\x0fMutatingService\x12D\n" +
	"\x05Probe\x12\x1c.rti.v1.MutatingProbeRequest\x1a\x1d.rti.v1.MutatingProbeResponse\x12F\n" +
	"\vForceResign\x12\x1a.rti.v1.ForceResignRequest\x1a\x1b.rti.v1.ForceResignResponse\x12b\n" +
	"\x11DestroyFederation\x12%.rti.v1.AdminDestroyFederationRequest\x1a&.rti.v1.AdminDestroyFederationResponse\x12X\n" +
	"\x11PromoteFederation\x12 .rti.v1.PromoteFederationRequest\x1a!.rti.v1.PromoteFederationResponseB<Z:github.com/cbchoi/gorti/rti/internal/genproto/rti/v1;rtiv1b\x06proto3"

var (
	file_rti_v1_admin_mutating_proto_rawDescOnce sync.Once
	file_rti_v1_admin_mutating_proto_rawDescData []byte
)

func file_rti_v1_admin_mutating_proto_rawDescGZIP() []byte {
	file_rti_v1_admin_mutating_proto_rawDescOnce.Do(func() {
		file_rti_v1_admin_mutating_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rti_v1_admin_mutating_proto_rawDesc), len(file_rti_v1_admin_mutating_proto_rawDesc)))
	})
	return file_rti_v1_admin_mutating_proto_rawDescData
}

var file_rti_v1_admin_mutating_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_rti_v1_admin_mutating_proto_goTypes = []any{
	(*MutatingProbeRequest)(nil),           // 0: rti.v1.MutatingProbeRequest
	(*MutatingProbeResponse)(nil),          // 1: rti.v1.MutatingProbeResponse
	(*ForceResignRequest)(nil),             // 2: rti.v1.ForceResignRequest
	(*ForceResignResponse)(nil),            // 3: rti.v1.ForceResignResponse
	(*AdminDestroyFederationRequest)(nil),  // 4: rti.v1.AdminDestroyFederationRequest
	(*AdminDestroyFederationResponse)(nil), // 5: rti.v1.AdminDestroyFederationResponse
	(*PromoteFederationRequest)(nil),       // 6: rti.v1.PromoteFederationRequest
	(*PromoteFederationResponse)(nil),      // 7: rti.v1.PromoteFederationResponse
	(WireVersion)(0),                       // 8: rti.v1.WireVersion
}
var file_rti_v1_admin_mutating_proto_depIdxs = []int32{
	8, // 0: rti.v1.MutatingProbeRequest.wire_version:type_name -> rti.v1.WireVersion
	8, // 1: rti.v1.ForceResignRequest.wire_version:type_name -> rti.v1.WireVersion
	8, // 2: rti.v1.AdminDestroyFederationRequest.wire_version:type_name -> rti.v1.WireVersion
	8, // 3: rti.v1.PromoteFederationRequest.wire_version:type_name -> rti.v1.WireVersion
	0, // 4: rti.v1.MutatingService.Probe:input_type -> rti.v1.MutatingProbeRequest
	2, // 5: rti.v1.MutatingService.ForceResign:input_type -> rti.v1.ForceResignRequest
	4, // 6: rti.v1.MutatingService.DestroyFederation:input_type -> rti.v1.AdminDestroyFederationRequest
	6, // 7: rti.v1.MutatingService.PromoteFederation:input_type -> rti.v1.PromoteFederationRequest
	1, // 8: rti.v1.MutatingService.Probe:output_type -> rti.v1.MutatingProbeResponse
	3, // 9: rti.v1.MutatingService.ForceResign:output_type -> rti.v1.ForceResignResponse
	5, // 10: rti.v1.MutatingService.DestroyFederation:output_type -> rti.v1.AdminDestroyFederationResponse
	7, // 11: rti.v1.MutatingService.PromoteFederation:output_type -> rti.v1.PromoteFederationResponse
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_rti_v1_admin_mutating_proto_init() }
func file_rti_v1_admin_mutating_proto_init() {
	if File_rti_v1_admin_mutating_proto != nil {
		return
	}
	file_rti_v1_common_proto_init()
	file_rti_v1_admin_mutating_proto_msgTypes[4].OneofWrappers = []any{}
	file_rti_v1_admin_mutating_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rti_v1_admin_mutating_proto_rawDesc), len(file_rti_v1_admin_mutating_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rti_v1_admin_mutating_proto_goTypes,
		DependencyIndexes: file_rti_v1_admin_mutating_proto_depIdxs,
		MessageInfos:      file_rti_v1_admin_mutating_proto_msgTypes,
	}.Build()
	File_rti_v1_admin_mutating_proto = out.File
	file_rti_v1_admin_mutating_proto_goTypes = nil
	file_rti_v1_admin_mutating_proto_depIdxs = nil
}
