// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: rti/v1/admin.proto

package rtiv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AdminService_Snapshot_FullMethodName   = "/rti.v1.AdminService/Snapshot"
	AdminService_TailEvents_FullMethodName = "/rti.v1.AdminService/TailEvents"
	AdminService_Status_FullMethodName     = "/rti.v1.AdminService/Status"
)

// AdminServiceClient is the client API for AdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AdminService — read-only introspection plane for `rti-top` and other
// live-observability tools (docs/rtid-tui.md Phase 1).
//
// Bound to a SEPARATE listener (`--admin-listen`, default
// localhost:8443) — independent from the federate-facing RPC plane on
// `--listen`. Plaintext only in Phase 1; mTLS / RBAC are explicitly
// out of scope.
//
// Every RPC is read-only. The handler MUST NOT call any Manager method
// that mutates state. Mutating control-plane operations (force-resign,
// kill, drain) are deferred to Phase 5+ and require a separate design
// review.
type AdminServiceClient interface {
	// Snapshot returns one consistent point-in-time snapshot of every
	// federation hosted by this rtid. Cheap enough for ~1Hz polling
	// (the TUI's default cadence).
	Snapshot(ctx context.Context, in *SnapshotRequest, opts ...grpc.CallOption) (*SnapshotResponse, error)
	// TailEvents server-streams event-log entries for a single federation
	// as they are appended. Cancelled via the stream context.
	TailEvents(ctx context.Context, in *TailEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TailEventsResponse], error)
	// Status is a lightweight liveness probe — rtid version + uptime.
	// Used by clients to verify the admin endpoint is reachable before
	// committing to a Snapshot poll loop.
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
}

type adminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminServiceClient(cc grpc.ClientConnInterface) AdminServiceClient {
	return &adminServiceClient{cc}
}

func (c *adminServiceClient) Snapshot(ctx context.Context, in *SnapshotRequest, opts ...grpc.CallOption) (*SnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SnapshotResponse)
	err := c.cc.Invoke(ctx, AdminService_Snapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) TailEvents(ctx context.Context, in *TailEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TailEventsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AdminService_ServiceDesc.Streams[0], AdminService_TailEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TailEventsRequest, TailEventsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AdminService_TailEventsClient = grpc.ServerStreamingClient[TailEventsResponse]

func (c *adminServiceClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, AdminService_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminServiceServer is the server API for AdminService service.
// All implementations must embed UnimplementedAdminServiceServer
// for forward compatibility.
//
// AdminService — read-only introspection plane for `rti-top` and other
// live-observability tools (docs/rtid-tui.md Phase 1).
//
// Bound to a SEPARATE listener (`--admin-listen`, default
// localhost:8443) — independent from the federate-facing RPC plane on
// `--listen`. Plaintext only in Phase 1; mTLS / RBAC are explicitly
// out of scope.
//
// Every RPC is read-only. The handler MUST NOT call any Manager method
// that mutates state. Mutating control-plane operations (force-resign,
// kill, drain) are deferred to Phase 5+ and require a separate design
// review.
type AdminServiceServer interface {
	// Snapshot returns one consistent point-in-time snapshot of every
	// federation hosted by this rtid. Cheap enough for ~1Hz polling
	// (the TUI's default cadence).
	Snapshot(context.Context, *SnapshotRequest) (*SnapshotResponse, error)
	// TailEvents server-streams event-log entries for a single federation
	// as they are appended. Cancelled via the stream context.
	TailEvents(*TailEventsRequest, grpc.ServerStreamingServer[TailEventsResponse]) error
	// Status is a lightweight liveness probe — rtid version + uptime.
	// Used by clients to verify the admin endpoint is reachable before
	// committing to a Snapshot poll loop.
	Status(context.Context, *StatusRequest) (*StatusResponse, error)
	mustEmbedUnimplementedAdminServiceServer()
}

// UnimplementedAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminServiceServer struct{}

func (UnimplementedAdminServiceServer) Snapshot(context.Context, *SnapshotRequest) (*SnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Snapshot not implemented")
}
func (UnimplementedAdminServiceServer) TailEvents(*TailEventsRequest, grpc.ServerStreamingServer[TailEventsResponse]) error {
	return status.Error(codes.Unimplemented, "method TailEvents not implemented")
}
func (UnimplementedAdminServiceServer) Status(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedAdminServiceServer) mustEmbedUnimplementedAdminServiceServer() {}
func (UnimplementedAdminServiceServer) testEmbeddedByValue()                      {}

// UnsafeAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminServiceServer will
// result in compilation errors.
type UnsafeAdminServiceServer interface {
	mustEmbedUnimplementedAdminServiceServer()
}

func RegisterAdminServiceServer(s grpc.ServiceRegistrar, srv AdminServiceServer) {
	// If the following call panics, it indicates UnimplementedAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdminService_ServiceDesc, srv)
}

func _AdminService_Snapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).Snapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_Snapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).Snapshot(ctx, req.(*SnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_TailEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TailEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AdminServiceServer).TailEvents(m, &grpc.GenericServerStream[TailEventsRequest, TailEventsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AdminService_TailEventsServer = grpc.ServerStreamingServer[TailEventsResponse]

func _AdminService_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminService_ServiceDesc is the grpc.ServiceDesc for AdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rti.v1.AdminService",
	HandlerType: (*AdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Snapshot",
			Handler:    _AdminService_Snapshot_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _AdminService_Status_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "TailEvents",
			Handler:       _AdminService_TailEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "rti/v1/admin.proto",
}
