// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: rti/v1/cluster.proto

package rtiv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ClusterService_ListClusterNodes_FullMethodName     = "/rti.v1.ClusterService/ListClusterNodes"
	ClusterService_LookupFederationHost_FullMethodName = "/rti.v1.ClusterService/LookupFederationHost"
	ClusterService_ReportNodeHealth_FullMethodName     = "/rti.v1.ClusterService/ReportNodeHealth"
	ClusterService_NotifyAssignment_FullMethodName     = "/rti.v1.ClusterService/NotifyAssignment"
)

// ClusterServiceClient is the client API for ClusterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ClusterService — distributed RTI cluster surface (M15 cut-1).
//
// Cut-1 (single-node): every node returns ListClusterNodes = [self];
// LookupFederationHost returns CURRENT for known federations.
// Cut-2 (multi-node, deferred): Raft-backed federation-to-node
// assignments + cross-node redirect.
type ClusterServiceClient interface {
	// ListClusterNodes returns the live cluster membership view from
	// this node's perspective.
	ListClusterNodes(ctx context.Context, in *ListClusterNodesRequest, opts ...grpc.CallOption) (*ListClusterNodesResponse, error)
	// LookupFederationHost — given a federation name, returns the
	// address of the rtid that hosts it. CURRENT means this node
	// hosts; REDIRECT carries the host's address; NOT_FOUND when the
	// federation does not exist anywhere in the cluster.
	LookupFederationHost(ctx context.Context, in *LookupFederationHostRequest, opts ...grpc.CallOption) (*LookupFederationHostResponse, error)
	// ReportNodeHealth — peer-to-peer heartbeat (multi-node only).
	// Cut-1 implementation rejects with FailedPrecondition.
	ReportNodeHealth(ctx context.Context, in *ReportNodeHealthRequest, opts ...grpc.CallOption) (*Empty, error)
	// NotifyAssignment — peer-to-peer notification that a federation
	// has been assigned to a specific node. The receiver updates its
	// in-memory assignment table so subsequent LookupFederationHost
	// calls return REDIRECT to the host. M15 cut-2 demo (best-effort
	// gossip; production replaces with Raft).
	NotifyAssignment(ctx context.Context, in *NotifyAssignmentRequest, opts ...grpc.CallOption) (*Empty, error)
}

type clusterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClusterServiceClient(cc grpc.ClientConnInterface) ClusterServiceClient {
	return &clusterServiceClient{cc}
}

func (c *clusterServiceClient) ListClusterNodes(ctx context.Context, in *ListClusterNodesRequest, opts ...grpc.CallOption) (*ListClusterNodesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListClusterNodesResponse)
	err := c.cc.Invoke(ctx, ClusterService_ListClusterNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterServiceClient) LookupFederationHost(ctx context.Context, in *LookupFederationHostRequest, opts ...grpc.CallOption) (*LookupFederationHostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LookupFederationHostResponse)
	err := c.cc.Invoke(ctx, ClusterService_LookupFederationHost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterServiceClient) ReportNodeHealth(ctx context.Context, in *ReportNodeHealthRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ClusterService_ReportNodeHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterServiceClient) NotifyAssignment(ctx context.Context, in *NotifyAssignmentRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ClusterService_NotifyAssignment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClusterServiceServer is the server API for ClusterService service.
// All implementations must embed UnimplementedClusterServiceServer
// for forward compatibility.
//
// ClusterService — distributed RTI cluster surface (M15 cut-1).
//
// Cut-1 (single-node): every node returns ListClusterNodes = [self];
// LookupFederationHost returns CURRENT for known federations.
// Cut-2 (multi-node, deferred): Raft-backed federation-to-node
// assignments + cross-node redirect.
type ClusterServiceServer interface {
	// ListClusterNodes returns the live cluster membership view from
	// this node's perspective.
	ListClusterNodes(context.Context, *ListClusterNodesRequest) (*ListClusterNodesResponse, error)
	// LookupFederationHost — given a federation name, returns the
	// address of the rtid that hosts it. CURRENT means this node
	// hosts; REDIRECT carries the host's address; NOT_FOUND when the
	// federation does not exist anywhere in the cluster.
	LookupFederationHost(context.Context, *LookupFederationHostRequest) (*LookupFederationHostResponse, error)
	// ReportNodeHealth — peer-to-peer heartbeat (multi-node only).
	// Cut-1 implementation rejects with FailedPrecondition.
	ReportNodeHealth(context.Context, *ReportNodeHealthRequest) (*Empty, error)
	// NotifyAssignment — peer-to-peer notification that a federation
	// has been assigned to a specific node. The receiver updates its
	// in-memory assignment table so subsequent LookupFederationHost
	// calls return REDIRECT to the host. M15 cut-2 demo (best-effort
	// gossip; production replaces with Raft).
	NotifyAssignment(context.Context, *NotifyAssignmentRequest) (*Empty, error)
	mustEmbedUnimplementedClusterServiceServer()
}

// UnimplementedClusterServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClusterServiceServer struct{}

func (UnimplementedClusterServiceServer) ListClusterNodes(context.Context, *ListClusterNodesRequest) (*ListClusterNodesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListClusterNodes not implemented")
}
func (UnimplementedClusterServiceServer) LookupFederationHost(context.Context, *LookupFederationHostRequest) (*LookupFederationHostResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LookupFederationHost not implemented")
}
func (UnimplementedClusterServiceServer) ReportNodeHealth(context.Context, *ReportNodeHealthRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportNodeHealth not implemented")
}
func (UnimplementedClusterServiceServer) NotifyAssignment(context.Context, *NotifyAssignmentRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method NotifyAssignment not implemented")
}
func (UnimplementedClusterServiceServer) mustEmbedUnimplementedClusterServiceServer() {}
func (UnimplementedClusterServiceServer) testEmbeddedByValue()                        {}

// UnsafeClusterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClusterServiceServer will
// result in compilation errors.
type UnsafeClusterServiceServer interface {
	mustEmbedUnimplementedClusterServiceServer()
}

func RegisterClusterServiceServer(s grpc.ServiceRegistrar, srv ClusterServiceServer) {
	// If the following call panics, it indicates UnimplementedClusterServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClusterService_ServiceDesc, srv)
}

func _ClusterService_ListClusterNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListClusterNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServiceServer).ListClusterNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClusterService_ListClusterNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServiceServer).ListClusterNodes(ctx, req.(*ListClusterNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClusterService_LookupFederationHost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookupFederationHostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServiceServer).LookupFederationHost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClusterService_LookupFederationHost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServiceServer).LookupFederationHost(ctx, req.(*LookupFederationHostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClusterService_ReportNodeHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportNodeHealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServiceServer).ReportNodeHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClusterService_ReportNodeHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServiceServer).ReportNodeHealth(ctx, req.(*ReportNodeHealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClusterService_NotifyAssignment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyAssignmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServiceServer).NotifyAssignment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClusterService_NotifyAssignment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServiceServer).NotifyAssignment(ctx, req.(*NotifyAssignmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ClusterService_ServiceDesc is the grpc.ServiceDesc for ClusterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClusterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rti.v1.ClusterService",
	HandlerType: (*ClusterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListClusterNodes",
			Handler:    _ClusterService_ListClusterNodes_Handler,
		},
		{
			MethodName: "LookupFederationHost",
			Handler:    _ClusterService_LookupFederationHost_Handler,
		},
		{
			MethodName: "ReportNodeHealth",
			Handler:    _ClusterService_ReportNodeHealth_Handler,
		},
		{
			MethodName: "NotifyAssignment",
			Handler:    _ClusterService_NotifyAssignment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rti/v1/cluster.proto",
}
