// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: rti/v1/common.proto

package rtiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WireVersion identifies the wire protocol version. Bumped when breaking
// changes occur (pre-1.0: freely; post-1.0: with migration plan).
type WireVersion int32

const (
	WireVersion_WIRE_VERSION_UNSPECIFIED WireVersion = 0
	WireVersion_WIRE_VERSION_V1          WireVersion = 1
)

// Enum value maps for WireVersion.
var (
	WireVersion_name = map[int32]string{
		0: "WIRE_VERSION_UNSPECIFIED",
		1: "WIRE_VERSION_V1",
	}
	WireVersion_value = map[string]int32{
		"WIRE_VERSION_UNSPECIFIED": 0,
		"WIRE_VERSION_V1":          1,
	}
)

func (x WireVersion) Enum() *WireVersion {
	p := new(WireVersion)
	*p = x
	return p
}

func (x WireVersion) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WireVersion) Descriptor() protoreflect.EnumDescriptor {
	return file_rti_v1_common_proto_enumTypes[0].Descriptor()
}

func (WireVersion) Type() protoreflect.EnumType {
	return &file_rti_v1_common_proto_enumTypes[0]
}

func (x WireVersion) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WireVersion.Descriptor instead.
func (WireVersion) EnumDescriptor() ([]byte, []int) {
	return file_rti_v1_common_proto_rawDescGZIP(), []int{0}
}

// Mode is the federation operating mode, fixed at federation create time.
//
//	VERBOSE: TSO for everything, full event log, target <=100 msg/s/federate.
//	BEST_EFFORT: per-attribute reliability per FOM declaration; minimal log;
//	             target >1k msg/s/federate.
type Mode int32

const (
	Mode_MODE_UNSPECIFIED Mode = 0
	Mode_MODE_VERBOSE     Mode = 1
	Mode_MODE_BEST_EFFORT Mode = 2
)

// Enum value maps for Mode.
var (
	Mode_name = map[int32]string{
		0: "MODE_UNSPECIFIED",
		1: "MODE_VERBOSE",
		2: "MODE_BEST_EFFORT",
	}
	Mode_value = map[string]int32{
		"MODE_UNSPECIFIED": 0,
		"MODE_VERBOSE":     1,
		"MODE_BEST_EFFORT": 2,
	}
)

func (x Mode) Enum() *Mode {
	p := new(Mode)
	*p = x
	return p
}

func (x Mode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Mode) Descriptor() protoreflect.EnumDescriptor {
	return file_rti_v1_common_proto_enumTypes[1].Descriptor()
}

func (Mode) Type() protoreflect.EnumType {
	return &file_rti_v1_common_proto_enumTypes[1]
}

func (x Mode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Mode.Descriptor instead.
func (Mode) EnumDescriptor() ([]byte, []int) {
	return file_rti_v1_common_proto_rawDescGZIP(), []int{1}
}

// ResignAction — IEEE 1516.1-2010 §4.10. M24 expanded the accepted
// set from 1 (UNCONDITIONALLY_DIVEST_ATTRIBUTES) to all 6 spec values.
type ResignAction int32

const (
	ResignAction_RESIGN_ACTION_UNSPECIFIED                       ResignAction = 0
	ResignAction_RESIGN_ACTION_UNCONDITIONALLY_DIVEST_ATTRIBUTES ResignAction = 1
	ResignAction_RESIGN_ACTION_DELETE_THEN_DIVEST                ResignAction = 2 // M24
	ResignAction_RESIGN_ACTION_CANCEL_THEN_DELETE                ResignAction = 3 // M24 — cancel pending acquires + delete owned objects
	ResignAction_RESIGN_ACTION_CANCEL_PENDING_OWNERSHIP          ResignAction = 4 // M24
	ResignAction_RESIGN_ACTION_NO_ACTION                         ResignAction = 5 // M24 — leave ownership/objects in place
	ResignAction_RESIGN_ACTION_DELETE_OBJECTS                    ResignAction = 6 // M24 — delete owned objects without divest
)

// Enum value maps for ResignAction.
var (
	ResignAction_name = map[int32]string{
		0: "RESIGN_ACTION_UNSPECIFIED",
		1: "RESIGN_ACTION_UNCONDITIONALLY_DIVEST_ATTRIBUTES",
		2: "RESIGN_ACTION_DELETE_THEN_DIVEST",
		3: "RESIGN_ACTION_CANCEL_THEN_DELETE",
		4: "RESIGN_ACTION_CANCEL_PENDING_OWNERSHIP",
		5: "RESIGN_ACTION_NO_ACTION",
		6: "RESIGN_ACTION_DELETE_OBJECTS",
	}
	ResignAction_value = map[string]int32{
		"RESIGN_ACTION_UNSPECIFIED":                       0,
		"RESIGN_ACTION_UNCONDITIONALLY_DIVEST_ATTRIBUTES": 1,
		"RESIGN_ACTION_DELETE_THEN_DIVEST":                2,
		"RESIGN_ACTION_CANCEL_THEN_DELETE":                3,
		"RESIGN_ACTION_CANCEL_PENDING_OWNERSHIP":          4,
		"RESIGN_ACTION_NO_ACTION":                         5,
		"RESIGN_ACTION_DELETE_OBJECTS":                    6,
	}
)

func (x ResignAction) Enum() *ResignAction {
	p := new(ResignAction)
	*p = x
	return p
}

func (x ResignAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResignAction) Descriptor() protoreflect.EnumDescriptor {
	return file_rti_v1_common_proto_enumTypes[2].Descriptor()
}

func (ResignAction) Type() protoreflect.EnumType {
	return &file_rti_v1_common_proto_enumTypes[2]
}

func (x ResignAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResignAction.Descriptor instead.
func (ResignAction) EnumDescriptor() ([]byte, []int) {
	return file_rti_v1_common_proto_rawDescGZIP(), []int{2}
}

// TransportationType — IEEE 1516.1-2010 §6.20-6.22 (M23). Per-instance
// or per-class transport selection. Default (unspecified at the wire
// level) inherits the FOM-declared transport.
type TransportationType int32

const (
	TransportationType_TRANSPORTATION_TYPE_UNSPECIFIED TransportationType = 0
	TransportationType_TRANSPORTATION_TYPE_RELIABLE    TransportationType = 1
	TransportationType_TRANSPORTATION_TYPE_BEST_EFFORT TransportationType = 2
)

// Enum value maps for TransportationType.
var (
	TransportationType_name = map[int32]string{
		0: "TRANSPORTATION_TYPE_UNSPECIFIED",
		1: "TRANSPORTATION_TYPE_RELIABLE",
		2: "TRANSPORTATION_TYPE_BEST_EFFORT",
	}
	TransportationType_value = map[string]int32{
		"TRANSPORTATION_TYPE_UNSPECIFIED": 0,
		"TRANSPORTATION_TYPE_RELIABLE":    1,
		"TRANSPORTATION_TYPE_BEST_EFFORT": 2,
	}
)

func (x TransportationType) Enum() *TransportationType {
	p := new(TransportationType)
	*p = x
	return p
}

func (x TransportationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransportationType) Descriptor() protoreflect.EnumDescriptor {
	return file_rti_v1_common_proto_enumTypes[3].Descriptor()
}

func (TransportationType) Type() protoreflect.EnumType {
	return &file_rti_v1_common_proto_enumTypes[3]
}

func (x TransportationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransportationType.Descriptor instead.
func (TransportationType) EnumDescriptor() ([]byte, []int) {
	return file_rti_v1_common_proto_rawDescGZIP(), []int{3}
}

// Empty is used as a request or response when no payload is needed.
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_rti_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_rti_v1_common_proto_rawDescGZIP(), []int{0}
}

// LogicalTime is HLA logical time. IEEE 1516.2-2010 leaves the representation
// implementation-defined; this RTI uses IEEE 754 double.
type LogicalTime struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         float64                `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogicalTime) Reset() {
	*x = LogicalTime{}
	mi := &file_rti_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogicalTime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogicalTime) ProtoMessage() {}

func (x *LogicalTime) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogicalTime.ProtoReflect.Descriptor instead.
func (*LogicalTime) Descriptor() ([]byte, []int) {
	return file_rti_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *LogicalTime) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

// FOMModule represents one FOM XML module submitted at federation create.
type FOMModule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional: source path or filename, for diagnostics. Not used for parsing.
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// The XML bytes. Validated strictly per IEEE 1516.2-2010 DIF.
	Xml           []byte `protobuf:"bytes,2,opt,name=xml,proto3" json:"xml,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FOMModule) Reset() {
	*x = FOMModule{}
	mi := &file_rti_v1_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FOMModule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FOMModule) ProtoMessage() {}

func (x *FOMModule) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FOMModule.ProtoReflect.Descriptor instead.
func (*FOMModule) Descriptor() ([]byte, []int) {
	return file_rti_v1_common_proto_rawDescGZIP(), []int{2}
}

func (x *FOMModule) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FOMModule) GetXml() []byte {
	if x != nil {
		return x.Xml
	}
	return nil
}

var File_rti_v1_common_proto protoreflect.FileDescriptor

const file_rti_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x13rti/v1/common.proto\x12\x06rti.v1\"\a\n" +
	"\x05Empty\"#\n" +
	"\vLogicalTime\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x01R\x05value\"1\n" +
	"\tFOMModule\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x10\n" +
	"\x03xml\x18\x02 \x01(\fR\x03xml*@\n" +
	"\vWireVersion\x12\x1c\n" +
	"\x18WIRE_VERSION_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fWIRE_VERSION_V1\x10\x01*D\n" +
	"\x04Mode\x12\x14\n" +
	"\x10MODE_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fMODE_VERBOSE\x10\x01\x12\x14\n" +
	"\x10MODE_BEST_EFFORT\x10\x02*\x99\x02\n" +
	"\fResignAction\x12\x1d\n" +
	"\x19RESIGN_ACTION_UNSPECIFIED\x10\x00\x123\n" +
	"/RESIGN_ACTION_UNCONDITIONALLY_DIVEST_ATTRIBUTES\x10\x01\x12$\n" +
	" RESIGN_ACTION_DELETE_THEN_DIVEST\x10\x02\x12$\n" +
	" RESIGN_ACTION_CANCEL_THEN_DELETE\x10\x03\x12*\n" +
	"&RESIGN_ACTION_CANCEL_PENDING_OWNERSHIP\x10\x04\x12\x1b\n" +
	"\x17RESIGN_ACTION_NO_ACTION\x10\x05\x12 \n" +
	"\x1cRESIGN_ACTION_DELETE_OBJECTS\x10\x06*\x80\x01\n" +
	"\x12TransportationType\x12#\n" +
	"\x1fTRANSPORTATION_TYPE_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cTRANSPORTATION_TYPE_RELIABLE\x10\x01\x12#\n" +
	"\x1fTRANSPORTATION_TYPE_BEST_EFFORT\x10\x02B<Z:github.com/cbchoi/gorti/rti/internal/genproto/rti/v1;rtiv1b\x06proto3"

var (
	file_rti_v1_common_proto_rawDescOnce sync.Once
	file_rti_v1_common_proto_rawDescData []byte
)

func file_rti_v1_common_proto_rawDescGZIP() []byte {
	file_rti_v1_common_proto_rawDescOnce.Do(func() {
		file_rti_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rti_v1_common_proto_rawDesc), len(file_rti_v1_common_proto_rawDesc)))
	})
	return file_rti_v1_common_proto_rawDescData
}

var file_rti_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_rti_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_rti_v1_common_proto_goTypes = []any{
	(WireVersion)(0),        // 0: rti.v1.WireVersion
	(Mode)(0),               // 1: rti.v1.Mode
	(ResignAction)(0),       // 2: rti.v1.ResignAction
	(TransportationType)(0), // 3: rti.v1.TransportationType
	(*Empty)(nil),           // 4: rti.v1.Empty
	(*LogicalTime)(nil),     // 5: rti.v1.LogicalTime
	(*FOMModule)(nil),       // 6: rti.v1.FOMModule
}
var file_rti_v1_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rti_v1_common_proto_init() }
func file_rti_v1_common_proto_init() {
	if File_rti_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rti_v1_common_proto_rawDesc), len(file_rti_v1_common_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rti_v1_common_proto_goTypes,
		DependencyIndexes: file_rti_v1_common_proto_depIdxs,
		EnumInfos:         file_rti_v1_common_proto_enumTypes,
		MessageInfos:      file_rti_v1_common_proto_msgTypes,
	}.Build()
	File_rti_v1_common_proto = out.File
	file_rti_v1_common_proto_goTypes = nil
	file_rti_v1_common_proto_depIdxs = nil
}
