// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: rti/v1/confirmed_object.proto

package rtiv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConfirmedObjectService_Exchange_FullMethodName = "/rti.v1.ConfirmedObjectService/Exchange"
)

// ConfirmedObjectServiceClient is the client API for ConfirmedObjectService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ConfirmedObjectService preserves the synchronous Object Management
// completion boundary while reusing one bidirectional HTTP/2 stream. Every
// request receives exactly one same-sequence result before the next request is
// accepted from that federate's Go SDK.
type ConfirmedObjectServiceClient interface {
	Exchange(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ConfirmedObjectRequest, ConfirmedObjectResult], error)
}

type confirmedObjectServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewConfirmedObjectServiceClient(cc grpc.ClientConnInterface) ConfirmedObjectServiceClient {
	return &confirmedObjectServiceClient{cc}
}

func (c *confirmedObjectServiceClient) Exchange(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ConfirmedObjectRequest, ConfirmedObjectResult], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ConfirmedObjectService_ServiceDesc.Streams[0], ConfirmedObjectService_Exchange_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ConfirmedObjectRequest, ConfirmedObjectResult]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConfirmedObjectService_ExchangeClient = grpc.BidiStreamingClient[ConfirmedObjectRequest, ConfirmedObjectResult]

// ConfirmedObjectServiceServer is the server API for ConfirmedObjectService service.
// All implementations must embed UnimplementedConfirmedObjectServiceServer
// for forward compatibility.
//
// ConfirmedObjectService preserves the synchronous Object Management
// completion boundary while reusing one bidirectional HTTP/2 stream. Every
// request receives exactly one same-sequence result before the next request is
// accepted from that federate's Go SDK.
type ConfirmedObjectServiceServer interface {
	Exchange(grpc.BidiStreamingServer[ConfirmedObjectRequest, ConfirmedObjectResult]) error
	mustEmbedUnimplementedConfirmedObjectServiceServer()
}

// UnimplementedConfirmedObjectServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConfirmedObjectServiceServer struct{}

func (UnimplementedConfirmedObjectServiceServer) Exchange(grpc.BidiStreamingServer[ConfirmedObjectRequest, ConfirmedObjectResult]) error {
	return status.Error(codes.Unimplemented, "method Exchange not implemented")
}
func (UnimplementedConfirmedObjectServiceServer) mustEmbedUnimplementedConfirmedObjectServiceServer() {
}
func (UnimplementedConfirmedObjectServiceServer) testEmbeddedByValue() {}

// UnsafeConfirmedObjectServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConfirmedObjectServiceServer will
// result in compilation errors.
type UnsafeConfirmedObjectServiceServer interface {
	mustEmbedUnimplementedConfirmedObjectServiceServer()
}

func RegisterConfirmedObjectServiceServer(s grpc.ServiceRegistrar, srv ConfirmedObjectServiceServer) {
	// If the following call panics, it indicates UnimplementedConfirmedObjectServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConfirmedObjectService_ServiceDesc, srv)
}

func _ConfirmedObjectService_Exchange_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ConfirmedObjectServiceServer).Exchange(&grpc.GenericServerStream[ConfirmedObjectRequest, ConfirmedObjectResult]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConfirmedObjectService_ExchangeServer = grpc.BidiStreamingServer[ConfirmedObjectRequest, ConfirmedObjectResult]

// ConfirmedObjectService_ServiceDesc is the grpc.ServiceDesc for ConfirmedObjectService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConfirmedObjectService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rti.v1.ConfirmedObjectService",
	HandlerType: (*ConfirmedObjectServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Exchange",
			Handler:       _ConfirmedObjectService_Exchange_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "rti/v1/confirmed_object.proto",
}
