// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: rti/v1/declaration.proto

package rtiv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DeclarationService_PublishObjectClassAttributes_FullMethodName     = "/rti.v1.DeclarationService/PublishObjectClassAttributes"
	DeclarationService_UnpublishObjectClassAttributes_FullMethodName   = "/rti.v1.DeclarationService/UnpublishObjectClassAttributes"
	DeclarationService_SubscribeObjectClassAttributes_FullMethodName   = "/rti.v1.DeclarationService/SubscribeObjectClassAttributes"
	DeclarationService_UnsubscribeObjectClassAttributes_FullMethodName = "/rti.v1.DeclarationService/UnsubscribeObjectClassAttributes"
	DeclarationService_PublishInteractionClass_FullMethodName          = "/rti.v1.DeclarationService/PublishInteractionClass"
	DeclarationService_UnpublishInteractionClass_FullMethodName        = "/rti.v1.DeclarationService/UnpublishInteractionClass"
	DeclarationService_SubscribeInteractionClass_FullMethodName        = "/rti.v1.DeclarationService/SubscribeInteractionClass"
	DeclarationService_UnsubscribeInteractionClass_FullMethodName      = "/rti.v1.DeclarationService/UnsubscribeInteractionClass"
)

// DeclarationServiceClient is the client API for DeclarationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DeclarationService — pub/sub declarations.
// See docs/srs.md §5.2.
type DeclarationServiceClient interface {
	PublishObjectClassAttributes(ctx context.Context, in *PubObjAttrsRequest, opts ...grpc.CallOption) (*Empty, error)
	UnpublishObjectClassAttributes(ctx context.Context, in *UnpubObjAttrsRequest, opts ...grpc.CallOption) (*Empty, error)
	SubscribeObjectClassAttributes(ctx context.Context, in *SubObjAttrsRequest, opts ...grpc.CallOption) (*Empty, error)
	UnsubscribeObjectClassAttributes(ctx context.Context, in *UnsubObjAttrsRequest, opts ...grpc.CallOption) (*Empty, error)
	PublishInteractionClass(ctx context.Context, in *PubInterRequest, opts ...grpc.CallOption) (*Empty, error)
	UnpublishInteractionClass(ctx context.Context, in *UnpubInterRequest, opts ...grpc.CallOption) (*Empty, error)
	SubscribeInteractionClass(ctx context.Context, in *SubInterRequest, opts ...grpc.CallOption) (*Empty, error)
	UnsubscribeInteractionClass(ctx context.Context, in *UnsubInterRequest, opts ...grpc.CallOption) (*Empty, error)
}

type declarationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDeclarationServiceClient(cc grpc.ClientConnInterface) DeclarationServiceClient {
	return &declarationServiceClient{cc}
}

func (c *declarationServiceClient) PublishObjectClassAttributes(ctx context.Context, in *PubObjAttrsRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, DeclarationService_PublishObjectClassAttributes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *declarationServiceClient) UnpublishObjectClassAttributes(ctx context.Context, in *UnpubObjAttrsRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, DeclarationService_UnpublishObjectClassAttributes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *declarationServiceClient) SubscribeObjectClassAttributes(ctx context.Context, in *SubObjAttrsRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, DeclarationService_SubscribeObjectClassAttributes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *declarationServiceClient) UnsubscribeObjectClassAttributes(ctx context.Context, in *UnsubObjAttrsRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, DeclarationService_UnsubscribeObjectClassAttributes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *declarationServiceClient) PublishInteractionClass(ctx context.Context, in *PubInterRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, DeclarationService_PublishInteractionClass_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *declarationServiceClient) UnpublishInteractionClass(ctx context.Context, in *UnpubInterRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, DeclarationService_UnpublishInteractionClass_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *declarationServiceClient) SubscribeInteractionClass(ctx context.Context, in *SubInterRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, DeclarationService_SubscribeInteractionClass_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *declarationServiceClient) UnsubscribeInteractionClass(ctx context.Context, in *UnsubInterRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, DeclarationService_UnsubscribeInteractionClass_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeclarationServiceServer is the server API for DeclarationService service.
// All implementations must embed UnimplementedDeclarationServiceServer
// for forward compatibility.
//
// DeclarationService — pub/sub declarations.
// See docs/srs.md §5.2.
type DeclarationServiceServer interface {
	PublishObjectClassAttributes(context.Context, *PubObjAttrsRequest) (*Empty, error)
	UnpublishObjectClassAttributes(context.Context, *UnpubObjAttrsRequest) (*Empty, error)
	SubscribeObjectClassAttributes(context.Context, *SubObjAttrsRequest) (*Empty, error)
	UnsubscribeObjectClassAttributes(context.Context, *UnsubObjAttrsRequest) (*Empty, error)
	PublishInteractionClass(context.Context, *PubInterRequest) (*Empty, error)
	UnpublishInteractionClass(context.Context, *UnpubInterRequest) (*Empty, error)
	SubscribeInteractionClass(context.Context, *SubInterRequest) (*Empty, error)
	UnsubscribeInteractionClass(context.Context, *UnsubInterRequest) (*Empty, error)
	mustEmbedUnimplementedDeclarationServiceServer()
}

// UnimplementedDeclarationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDeclarationServiceServer struct{}

func (UnimplementedDeclarationServiceServer) PublishObjectClassAttributes(context.Context, *PubObjAttrsRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishObjectClassAttributes not implemented")
}
func (UnimplementedDeclarationServiceServer) UnpublishObjectClassAttributes(context.Context, *UnpubObjAttrsRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UnpublishObjectClassAttributes not implemented")
}
func (UnimplementedDeclarationServiceServer) SubscribeObjectClassAttributes(context.Context, *SubObjAttrsRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SubscribeObjectClassAttributes not implemented")
}
func (UnimplementedDeclarationServiceServer) UnsubscribeObjectClassAttributes(context.Context, *UnsubObjAttrsRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UnsubscribeObjectClassAttributes not implemented")
}
func (UnimplementedDeclarationServiceServer) PublishInteractionClass(context.Context, *PubInterRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishInteractionClass not implemented")
}
func (UnimplementedDeclarationServiceServer) UnpublishInteractionClass(context.Context, *UnpubInterRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UnpublishInteractionClass not implemented")
}
func (UnimplementedDeclarationServiceServer) SubscribeInteractionClass(context.Context, *SubInterRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SubscribeInteractionClass not implemented")
}
func (UnimplementedDeclarationServiceServer) UnsubscribeInteractionClass(context.Context, *UnsubInterRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UnsubscribeInteractionClass not implemented")
}
func (UnimplementedDeclarationServiceServer) mustEmbedUnimplementedDeclarationServiceServer() {}
func (UnimplementedDeclarationServiceServer) testEmbeddedByValue()                            {}

// UnsafeDeclarationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeclarationServiceServer will
// result in compilation errors.
type UnsafeDeclarationServiceServer interface {
	mustEmbedUnimplementedDeclarationServiceServer()
}

func RegisterDeclarationServiceServer(s grpc.ServiceRegistrar, srv DeclarationServiceServer) {
	// If the following call panics, it indicates UnimplementedDeclarationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DeclarationService_ServiceDesc, srv)
}

func _DeclarationService_PublishObjectClassAttributes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PubObjAttrsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeclarationServiceServer).PublishObjectClassAttributes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeclarationService_PublishObjectClassAttributes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeclarationServiceServer).PublishObjectClassAttributes(ctx, req.(*PubObjAttrsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeclarationService_UnpublishObjectClassAttributes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnpubObjAttrsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeclarationServiceServer).UnpublishObjectClassAttributes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeclarationService_UnpublishObjectClassAttributes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeclarationServiceServer).UnpublishObjectClassAttributes(ctx, req.(*UnpubObjAttrsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeclarationService_SubscribeObjectClassAttributes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubObjAttrsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeclarationServiceServer).SubscribeObjectClassAttributes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeclarationService_SubscribeObjectClassAttributes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeclarationServiceServer).SubscribeObjectClassAttributes(ctx, req.(*SubObjAttrsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeclarationService_UnsubscribeObjectClassAttributes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnsubObjAttrsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeclarationServiceServer).UnsubscribeObjectClassAttributes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeclarationService_UnsubscribeObjectClassAttributes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeclarationServiceServer).UnsubscribeObjectClassAttributes(ctx, req.(*UnsubObjAttrsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeclarationService_PublishInteractionClass_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PubInterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeclarationServiceServer).PublishInteractionClass(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeclarationService_PublishInteractionClass_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeclarationServiceServer).PublishInteractionClass(ctx, req.(*PubInterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeclarationService_UnpublishInteractionClass_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnpubInterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeclarationServiceServer).UnpublishInteractionClass(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeclarationService_UnpublishInteractionClass_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeclarationServiceServer).UnpublishInteractionClass(ctx, req.(*UnpubInterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeclarationService_SubscribeInteractionClass_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubInterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeclarationServiceServer).SubscribeInteractionClass(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeclarationService_SubscribeInteractionClass_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeclarationServiceServer).SubscribeInteractionClass(ctx, req.(*SubInterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeclarationService_UnsubscribeInteractionClass_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnsubInterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeclarationServiceServer).UnsubscribeInteractionClass(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeclarationService_UnsubscribeInteractionClass_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeclarationServiceServer).UnsubscribeInteractionClass(ctx, req.(*UnsubInterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DeclarationService_ServiceDesc is the grpc.ServiceDesc for DeclarationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeclarationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rti.v1.DeclarationService",
	HandlerType: (*DeclarationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PublishObjectClassAttributes",
			Handler:    _DeclarationService_PublishObjectClassAttributes_Handler,
		},
		{
			MethodName: "UnpublishObjectClassAttributes",
			Handler:    _DeclarationService_UnpublishObjectClassAttributes_Handler,
		},
		{
			MethodName: "SubscribeObjectClassAttributes",
			Handler:    _DeclarationService_SubscribeObjectClassAttributes_Handler,
		},
		{
			MethodName: "UnsubscribeObjectClassAttributes",
			Handler:    _DeclarationService_UnsubscribeObjectClassAttributes_Handler,
		},
		{
			MethodName: "PublishInteractionClass",
			Handler:    _DeclarationService_PublishInteractionClass_Handler,
		},
		{
			MethodName: "UnpublishInteractionClass",
			Handler:    _DeclarationService_UnpublishInteractionClass_Handler,
		},
		{
			MethodName: "SubscribeInteractionClass",
			Handler:    _DeclarationService_SubscribeInteractionClass_Handler,
		},
		{
			MethodName: "UnsubscribeInteractionClass",
			Handler:    _DeclarationService_UnsubscribeInteractionClass_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rti/v1/declaration.proto",
}
