// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: rti/v1/errors.proto

package rtiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ErrorCode is a CLOSED set. Agents may NOT add codes locally; new codes
// require an orchestrator-approved contract change.
//
// Codes are namespaced by domain (FED_*, FOM_*, OBJ_*, TIME_*, ENC_*, WIRE_*).
// See docs/idd.md §1.1.3.
type ErrorCode int32

const (
	ErrorCode_ERROR_CODE_UNSPECIFIED ErrorCode = 0
	// Federation Management (1-99)
	ErrorCode_ERR_FED_NOT_FOUND            ErrorCode = 1
	ErrorCode_ERR_FED_ALREADY_EXISTS       ErrorCode = 2
	ErrorCode_ERR_FED_NOT_JOINED           ErrorCode = 3
	ErrorCode_ERR_FED_ALREADY_JOINED       ErrorCode = 4
	ErrorCode_ERR_FED_HAS_FEDERATES_JOINED ErrorCode = 5
	ErrorCode_ERR_FED_HALTED               ErrorCode = 6
	ErrorCode_ERR_FED_INVALID_NAME         ErrorCode = 7
	// FOM (100-199)
	ErrorCode_ERR_FOM_VALIDATION_FAILED ErrorCode = 100
	ErrorCode_ERR_FOM_MIM_REDEFINITION  ErrorCode = 101
	// Object Management (200-299)
	ErrorCode_ERR_OBJ_NOT_FOUND                 ErrorCode = 200
	ErrorCode_ERR_OBJ_CLASS_NOT_PUBLISHED       ErrorCode = 201
	ErrorCode_ERR_OBJ_ATTR_NOT_OWNED            ErrorCode = 202
	ErrorCode_ERR_OBJ_HANDLE_INVALID            ErrorCode = 203
	ErrorCode_ERR_OBJ_INTERACTION_NOT_PUBLISHED ErrorCode = 204
	ErrorCode_ERR_OBJ_CLASS_NOT_FOUND           ErrorCode = 205
	ErrorCode_ERR_OBJ_ATTR_NOT_FOUND            ErrorCode = 206
	// Time Management (300-399)
	ErrorCode_ERR_TIME_NOT_REGULATING      ErrorCode = 300
	ErrorCode_ERR_TIME_NOT_CONSTRAINED     ErrorCode = 301
	ErrorCode_ERR_TIME_INVALID_LOOKAHEAD   ErrorCode = 302
	ErrorCode_ERR_TIME_REQUEST_IN_PAST     ErrorCode = 303
	ErrorCode_ERR_TIME_ALREADY_REGULATING  ErrorCode = 304
	ErrorCode_ERR_TIME_ALREADY_CONSTRAINED ErrorCode = 305
	// Encoding (400-499)
	ErrorCode_ERR_ENC_INSUFFICIENT_BYTES ErrorCode = 400
	ErrorCode_ERR_ENC_TYPE_MISMATCH      ErrorCode = 401
	ErrorCode_ERR_ENC_PADDING_VIOLATION  ErrorCode = 402
	// Wire / Transport (500-599)
	ErrorCode_ERR_WIRE_VERSION_MISMATCH  ErrorCode = 500
	ErrorCode_ERR_WIRE_MALFORMED_MESSAGE ErrorCode = 501
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0:   "ERROR_CODE_UNSPECIFIED",
		1:   "ERR_FED_NOT_FOUND",
		2:   "ERR_FED_ALREADY_EXISTS",
		3:   "ERR_FED_NOT_JOINED",
		4:   "ERR_FED_ALREADY_JOINED",
		5:   "ERR_FED_HAS_FEDERATES_JOINED",
		6:   "ERR_FED_HALTED",
		7:   "ERR_FED_INVALID_NAME",
		100: "ERR_FOM_VALIDATION_FAILED",
		101: "ERR_FOM_MIM_REDEFINITION",
		200: "ERR_OBJ_NOT_FOUND",
		201: "ERR_OBJ_CLASS_NOT_PUBLISHED",
		202: "ERR_OBJ_ATTR_NOT_OWNED",
		203: "ERR_OBJ_HANDLE_INVALID",
		204: "ERR_OBJ_INTERACTION_NOT_PUBLISHED",
		205: "ERR_OBJ_CLASS_NOT_FOUND",
		206: "ERR_OBJ_ATTR_NOT_FOUND",
		300: "ERR_TIME_NOT_REGULATING",
		301: "ERR_TIME_NOT_CONSTRAINED",
		302: "ERR_TIME_INVALID_LOOKAHEAD",
		303: "ERR_TIME_REQUEST_IN_PAST",
		304: "ERR_TIME_ALREADY_REGULATING",
		305: "ERR_TIME_ALREADY_CONSTRAINED",
		400: "ERR_ENC_INSUFFICIENT_BYTES",
		401: "ERR_ENC_TYPE_MISMATCH",
		402: "ERR_ENC_PADDING_VIOLATION",
		500: "ERR_WIRE_VERSION_MISMATCH",
		501: "ERR_WIRE_MALFORMED_MESSAGE",
	}
	ErrorCode_value = map[string]int32{
		"ERROR_CODE_UNSPECIFIED":            0,
		"ERR_FED_NOT_FOUND":                 1,
		"ERR_FED_ALREADY_EXISTS":            2,
		"ERR_FED_NOT_JOINED":                3,
		"ERR_FED_ALREADY_JOINED":            4,
		"ERR_FED_HAS_FEDERATES_JOINED":      5,
		"ERR_FED_HALTED":                    6,
		"ERR_FED_INVALID_NAME":              7,
		"ERR_FOM_VALIDATION_FAILED":         100,
		"ERR_FOM_MIM_REDEFINITION":          101,
		"ERR_OBJ_NOT_FOUND":                 200,
		"ERR_OBJ_CLASS_NOT_PUBLISHED":       201,
		"ERR_OBJ_ATTR_NOT_OWNED":            202,
		"ERR_OBJ_HANDLE_INVALID":            203,
		"ERR_OBJ_INTERACTION_NOT_PUBLISHED": 204,
		"ERR_OBJ_CLASS_NOT_FOUND":           205,
		"ERR_OBJ_ATTR_NOT_FOUND":            206,
		"ERR_TIME_NOT_REGULATING":           300,
		"ERR_TIME_NOT_CONSTRAINED":          301,
		"ERR_TIME_INVALID_LOOKAHEAD":        302,
		"ERR_TIME_REQUEST_IN_PAST":          303,
		"ERR_TIME_ALREADY_REGULATING":       304,
		"ERR_TIME_ALREADY_CONSTRAINED":      305,
		"ERR_ENC_INSUFFICIENT_BYTES":        400,
		"ERR_ENC_TYPE_MISMATCH":             401,
		"ERR_ENC_PADDING_VIOLATION":         402,
		"ERR_WIRE_VERSION_MISMATCH":         500,
		"ERR_WIRE_MALFORMED_MESSAGE":        501,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_rti_v1_errors_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_rti_v1_errors_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_rti_v1_errors_proto_rawDescGZIP(), []int{0}
}

// ErrorInfo is attached to gRPC status details so federate SDKs can match
// deterministically across languages.
type ErrorInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Code  ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=rti.v1.ErrorCode" json:"code,omitempty"`
	// Human-readable message. Intended for logs, not user display.
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// FOM diagnostic code (e.g. "FOM-001"). Empty if not a FOM error.
	// Full list in docs/idd.md §1.2.1.
	FomCode string `protobuf:"bytes,3,opt,name=fom_code,json=fomCode,proto3" json:"fom_code,omitempty"`
	// 1-based line number when applicable; 0 if unknown.
	Line          int32 `protobuf:"varint,4,opt,name=line,proto3" json:"line,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorInfo) Reset() {
	*x = ErrorInfo{}
	mi := &file_rti_v1_errors_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorInfo) ProtoMessage() {}

func (x *ErrorInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_errors_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorInfo.ProtoReflect.Descriptor instead.
func (*ErrorInfo) Descriptor() ([]byte, []int) {
	return file_rti_v1_errors_proto_rawDescGZIP(), []int{0}
}

func (x *ErrorInfo) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_ERROR_CODE_UNSPECIFIED
}

func (x *ErrorInfo) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorInfo) GetFomCode() string {
	if x != nil {
		return x.FomCode
	}
	return ""
}

func (x *ErrorInfo) GetLine() int32 {
	if x != nil {
		return x.Line
	}
	return 0
}

var File_rti_v1_errors_proto protoreflect.FileDescriptor

const file_rti_v1_errors_proto_rawDesc = "" +
	"\n" +
	"\x13rti/v1/errors.proto\x12\x06rti.v1\"{\n" +
	"\tErrorInfo\x12%\n" +
	"\x04code\x18\x01 \x01(\x0e2\x11.rti.v1.ErrorCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x19\n" +
	"\bfom_code\x18\x03 \x01(\tR\afomCode\x12\x12\n" +
	"\x04line\x18\x04 \x01(\x05R\x04line*\xd2\x06\n" +
	"\tErrorCode\x12\x1a\n" +
	"\x16ERROR_CODE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11ERR_FED_NOT_FOUND\x10\x01\x12\x1a\n" +
	"\x16ERR_FED_ALREADY_EXISTS\x10\x02\x12\x16\n" +
	"\x12ERR_FED_NOT_JOINED\x10\x03\x12\x1a\n" +
	"\x16ERR_FED_ALREADY_JOINED\x10\x04\x12 \n" +
	"\x1cERR_FED_HAS_FEDERATES_JOINED\x10\x05\x12\x12\n" +
	"\x0eERR_FED_HALTED\x10\x06\x12\x18\n" +
	"\x14ERR_FED_INVALID_NAME\x10\a\x12\x1d\n" +
	"\x19ERR_FOM_VALIDATION_FAILED\x10d\x12\x1c\n" +
	"\x18ERR_FOM_MIM_REDEFINITION\x10e\x12\x16\n" +
	"\x11ERR_OBJ_NOT_FOUND\x10\xc8\x01\x12 \n" +
	"\x1bERR_OBJ_CLASS_NOT_PUBLISHED\x10\xc9\x01\x12\x1b\n" +
	"\x16ERR_OBJ_ATTR_NOT_OWNED\x10\xca\x01\x12\x1b\n" +
	"\x16ERR_OBJ_HANDLE_INVALID\x10\xcb\x01\x12&\n" +
	"!ERR_OBJ_INTERACTION_NOT_PUBLISHED\x10\xcc\x01\x12\x1c\n" +
	"\x17ERR_OBJ_CLASS_NOT_FOUND\x10\xcd\x01\x12\x1b\n" +
	"\x16ERR_OBJ_ATTR_NOT_FOUND\x10\xce\x01\x12\x1c\n" +
	"\x17ERR_TIME_NOT_REGULATING\x10\xac\x02\x12\x1d\n" +
	"\x18ERR_TIME_NOT_CONSTRAINED\x10\xad\x02\x12\x1f\n" +
	"\x1aERR_TIME_INVALID_LOOKAHEAD\x10\xae\x02\x12\x1d\n" +
	"\x18ERR_TIME_REQUEST_IN_PAST\x10\xaf\x02\x12 \n" +
	"\x1bERR_TIME_ALREADY_REGULATING\x10\xb0\x02\x12!\n" +
	"\x1cERR_TIME_ALREADY_CONSTRAINED\x10\xb1\x02\x12\x1f\n" +
	"\x1aERR_ENC_INSUFFICIENT_BYTES\x10\x90\x03\x12\x1a\n" +
	"\x15ERR_ENC_TYPE_MISMATCH\x10\x91\x03\x12\x1e\n" +
	"\x19ERR_ENC_PADDING_VIOLATION\x10\x92\x03\x12\x1e\n" +
	"\x19ERR_WIRE_VERSION_MISMATCH\x10\xf4\x03\x12\x1f\n" +
	"\x1aERR_WIRE_MALFORMED_MESSAGE\x10\xf5\x03B<Z:github.com/cbchoi/gorti/rti/internal/genproto/rti/v1;rtiv1b\x06proto3"

var (
	file_rti_v1_errors_proto_rawDescOnce sync.Once
	file_rti_v1_errors_proto_rawDescData []byte
)

func file_rti_v1_errors_proto_rawDescGZIP() []byte {
	file_rti_v1_errors_proto_rawDescOnce.Do(func() {
		file_rti_v1_errors_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rti_v1_errors_proto_rawDesc), len(file_rti_v1_errors_proto_rawDesc)))
	})
	return file_rti_v1_errors_proto_rawDescData
}

var file_rti_v1_errors_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_rti_v1_errors_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_rti_v1_errors_proto_goTypes = []any{
	(ErrorCode)(0),    // 0: rti.v1.ErrorCode
	(*ErrorInfo)(nil), // 1: rti.v1.ErrorInfo
}
var file_rti_v1_errors_proto_depIdxs = []int32{
	0, // 0: rti.v1.ErrorInfo.code:type_name -> rti.v1.ErrorCode
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rti_v1_errors_proto_init() }
func file_rti_v1_errors_proto_init() {
	if File_rti_v1_errors_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rti_v1_errors_proto_rawDesc), len(file_rti_v1_errors_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rti_v1_errors_proto_goTypes,
		DependencyIndexes: file_rti_v1_errors_proto_depIdxs,
		EnumInfos:         file_rti_v1_errors_proto_enumTypes,
		MessageInfos:      file_rti_v1_errors_proto_msgTypes,
	}.Build()
	File_rti_v1_errors_proto = out.File
	file_rti_v1_errors_proto_goTypes = nil
	file_rti_v1_errors_proto_depIdxs = nil
}
