// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: rti/v1/eventlog.proto

package rtiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Event is one record in the federation's event log file.
// Format: file header followed by length-prefixed Event records.
// See docs/idd.md §1.6 for the binary layout.
type Event struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Monotonic, gapless within a federation.
	Seq uint64 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	// Wall time in ns since epoch. INFORMATIONAL ONLY — never used for ordering.
	WallNs uint64 `protobuf:"varint,2,opt,name=wall_ns,json=wallNs,proto3" json:"wall_ns,omitempty"`
	// Types that are valid to be assigned to Body:
	//
	//	*Event_FedJoined
	//	*Event_FedResigned
	//	*Event_ObjRegistered
	//	*Event_ObjDeleted
	//	*Event_AttrUpdated
	//	*Event_InterSent
	//	*Event_TimeRequested
	//	*Event_TimeGranted
	//	*Event_Halted
	Body          isEvent_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_rti_v1_eventlog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_eventlog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_rti_v1_eventlog_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Event) GetWallNs() uint64 {
	if x != nil {
		return x.WallNs
	}
	return 0
}

func (x *Event) GetBody() isEvent_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Event) GetFedJoined() *FederateJoined {
	if x != nil {
		if x, ok := x.Body.(*Event_FedJoined); ok {
			return x.FedJoined
		}
	}
	return nil
}

func (x *Event) GetFedResigned() *FederateResigned {
	if x != nil {
		if x, ok := x.Body.(*Event_FedResigned); ok {
			return x.FedResigned
		}
	}
	return nil
}

func (x *Event) GetObjRegistered() *ObjectRegistered {
	if x != nil {
		if x, ok := x.Body.(*Event_ObjRegistered); ok {
			return x.ObjRegistered
		}
	}
	return nil
}

func (x *Event) GetObjDeleted() *ObjectDeleted {
	if x != nil {
		if x, ok := x.Body.(*Event_ObjDeleted); ok {
			return x.ObjDeleted
		}
	}
	return nil
}

func (x *Event) GetAttrUpdated() *AttributeUpdated {
	if x != nil {
		if x, ok := x.Body.(*Event_AttrUpdated); ok {
			return x.AttrUpdated
		}
	}
	return nil
}

func (x *Event) GetInterSent() *InteractionSent {
	if x != nil {
		if x, ok := x.Body.(*Event_InterSent); ok {
			return x.InterSent
		}
	}
	return nil
}

func (x *Event) GetTimeRequested() *TimeAdvanceRequested {
	if x != nil {
		if x, ok := x.Body.(*Event_TimeRequested); ok {
			return x.TimeRequested
		}
	}
	return nil
}

func (x *Event) GetTimeGranted() *TimeAdvanceGranted {
	if x != nil {
		if x, ok := x.Body.(*Event_TimeGranted); ok {
			return x.TimeGranted
		}
	}
	return nil
}

func (x *Event) GetHalted() *EventFederationHalted {
	if x != nil {
		if x, ok := x.Body.(*Event_Halted); ok {
			return x.Halted
		}
	}
	return nil
}

type isEvent_Body interface {
	isEvent_Body()
}

type Event_FedJoined struct {
	FedJoined *FederateJoined `protobuf:"bytes,10,opt,name=fed_joined,json=fedJoined,proto3,oneof"`
}

type Event_FedResigned struct {
	FedResigned *FederateResigned `protobuf:"bytes,11,opt,name=fed_resigned,json=fedResigned,proto3,oneof"`
}

type Event_ObjRegistered struct {
	ObjRegistered *ObjectRegistered `protobuf:"bytes,12,opt,name=obj_registered,json=objRegistered,proto3,oneof"`
}

type Event_ObjDeleted struct {
	ObjDeleted *ObjectDeleted `protobuf:"bytes,13,opt,name=obj_deleted,json=objDeleted,proto3,oneof"`
}

type Event_AttrUpdated struct {
	AttrUpdated *AttributeUpdated `protobuf:"bytes,14,opt,name=attr_updated,json=attrUpdated,proto3,oneof"`
}

type Event_InterSent struct {
	InterSent *InteractionSent `protobuf:"bytes,15,opt,name=inter_sent,json=interSent,proto3,oneof"`
}

type Event_TimeRequested struct {
	TimeRequested *TimeAdvanceRequested `protobuf:"bytes,16,opt,name=time_requested,json=timeRequested,proto3,oneof"`
}

type Event_TimeGranted struct {
	TimeGranted *TimeAdvanceGranted `protobuf:"bytes,17,opt,name=time_granted,json=timeGranted,proto3,oneof"`
}

type Event_Halted struct {
	Halted *EventFederationHalted `protobuf:"bytes,99,opt,name=halted,proto3,oneof"`
}

func (*Event_FedJoined) isEvent_Body() {}

func (*Event_FedResigned) isEvent_Body() {}

func (*Event_ObjRegistered) isEvent_Body() {}

func (*Event_ObjDeleted) isEvent_Body() {}

func (*Event_AttrUpdated) isEvent_Body() {}

func (*Event_InterSent) isEvent_Body() {}

func (*Event_TimeRequested) isEvent_Body() {}

func (*Event_TimeGranted) isEvent_Body() {}

func (*Event_Halted) isEvent_Body() {}

type FederateJoined struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FederateHandle uint64                 `protobuf:"varint,1,opt,name=federate_handle,json=federateHandle,proto3" json:"federate_handle,omitempty"`
	FederateName   string                 `protobuf:"bytes,2,opt,name=federate_name,json=federateName,proto3" json:"federate_name,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FederateJoined) Reset() {
	*x = FederateJoined{}
	mi := &file_rti_v1_eventlog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FederateJoined) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FederateJoined) ProtoMessage() {}

func (x *FederateJoined) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_eventlog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FederateJoined.ProtoReflect.Descriptor instead.
func (*FederateJoined) Descriptor() ([]byte, []int) {
	return file_rti_v1_eventlog_proto_rawDescGZIP(), []int{1}
}

func (x *FederateJoined) GetFederateHandle() uint64 {
	if x != nil {
		return x.FederateHandle
	}
	return 0
}

func (x *FederateJoined) GetFederateName() string {
	if x != nil {
		return x.FederateName
	}
	return ""
}

type FederateResigned struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FederateHandle uint64                 `protobuf:"varint,1,opt,name=federate_handle,json=federateHandle,proto3" json:"federate_handle,omitempty"`
	Action         ResignAction           `protobuf:"varint,2,opt,name=action,proto3,enum=rti.v1.ResignAction" json:"action,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FederateResigned) Reset() {
	*x = FederateResigned{}
	mi := &file_rti_v1_eventlog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FederateResigned) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FederateResigned) ProtoMessage() {}

func (x *FederateResigned) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_eventlog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FederateResigned.ProtoReflect.Descriptor instead.
func (*FederateResigned) Descriptor() ([]byte, []int) {
	return file_rti_v1_eventlog_proto_rawDescGZIP(), []int{2}
}

func (x *FederateResigned) GetFederateHandle() uint64 {
	if x != nil {
		return x.FederateHandle
	}
	return 0
}

func (x *FederateResigned) GetAction() ResignAction {
	if x != nil {
		return x.Action
	}
	return ResignAction_RESIGN_ACTION_UNSPECIFIED
}

type ObjectRegistered struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ObjectHandle        uint64                 `protobuf:"varint,1,opt,name=object_handle,json=objectHandle,proto3" json:"object_handle,omitempty"`
	ObjectClassHandle   uint64                 `protobuf:"varint,2,opt,name=object_class_handle,json=objectClassHandle,proto3" json:"object_class_handle,omitempty"`
	OwnerFederateHandle uint64                 `protobuf:"varint,3,opt,name=owner_federate_handle,json=ownerFederateHandle,proto3" json:"owner_federate_handle,omitempty"`
	ObjectName          string                 `protobuf:"bytes,4,opt,name=object_name,json=objectName,proto3" json:"object_name,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ObjectRegistered) Reset() {
	*x = ObjectRegistered{}
	mi := &file_rti_v1_eventlog_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectRegistered) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectRegistered) ProtoMessage() {}

func (x *ObjectRegistered) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_eventlog_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectRegistered.ProtoReflect.Descriptor instead.
func (*ObjectRegistered) Descriptor() ([]byte, []int) {
	return file_rti_v1_eventlog_proto_rawDescGZIP(), []int{3}
}

func (x *ObjectRegistered) GetObjectHandle() uint64 {
	if x != nil {
		return x.ObjectHandle
	}
	return 0
}

func (x *ObjectRegistered) GetObjectClassHandle() uint64 {
	if x != nil {
		return x.ObjectClassHandle
	}
	return 0
}

func (x *ObjectRegistered) GetOwnerFederateHandle() uint64 {
	if x != nil {
		return x.OwnerFederateHandle
	}
	return 0
}

func (x *ObjectRegistered) GetObjectName() string {
	if x != nil {
		return x.ObjectName
	}
	return ""
}

type ObjectDeleted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectHandle  uint64                 `protobuf:"varint,1,opt,name=object_handle,json=objectHandle,proto3" json:"object_handle,omitempty"`
	LogicalTime   *float64               `protobuf:"fixed64,2,opt,name=logical_time,json=logicalTime,proto3,oneof" json:"logical_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectDeleted) Reset() {
	*x = ObjectDeleted{}
	mi := &file_rti_v1_eventlog_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectDeleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectDeleted) ProtoMessage() {}

func (x *ObjectDeleted) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_eventlog_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectDeleted.ProtoReflect.Descriptor instead.
func (*ObjectDeleted) Descriptor() ([]byte, []int) {
	return file_rti_v1_eventlog_proto_rawDescGZIP(), []int{4}
}

func (x *ObjectDeleted) GetObjectHandle() uint64 {
	if x != nil {
		return x.ObjectHandle
	}
	return 0
}

func (x *ObjectDeleted) GetLogicalTime() float64 {
	if x != nil && x.LogicalTime != nil {
		return *x.LogicalTime
	}
	return 0
}

type AttributeUpdated struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	ObjectHandle           uint64                 `protobuf:"varint,1,opt,name=object_handle,json=objectHandle,proto3" json:"object_handle,omitempty"`
	ProducerFederateHandle uint64                 `protobuf:"varint,2,opt,name=producer_federate_handle,json=producerFederateHandle,proto3" json:"producer_federate_handle,omitempty"`
	Attributes             map[uint64][]byte      `protobuf:"bytes,3,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	LogicalTime            *float64               `protobuf:"fixed64,4,opt,name=logical_time,json=logicalTime,proto3,oneof" json:"logical_time,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AttributeUpdated) Reset() {
	*x = AttributeUpdated{}
	mi := &file_rti_v1_eventlog_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttributeUpdated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributeUpdated) ProtoMessage() {}

func (x *AttributeUpdated) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_eventlog_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributeUpdated.ProtoReflect.Descriptor instead.
func (*AttributeUpdated) Descriptor() ([]byte, []int) {
	return file_rti_v1_eventlog_proto_rawDescGZIP(), []int{5}
}

func (x *AttributeUpdated) GetObjectHandle() uint64 {
	if x != nil {
		return x.ObjectHandle
	}
	return 0
}

func (x *AttributeUpdated) GetProducerFederateHandle() uint64 {
	if x != nil {
		return x.ProducerFederateHandle
	}
	return 0
}

func (x *AttributeUpdated) GetAttributes() map[uint64][]byte {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *AttributeUpdated) GetLogicalTime() float64 {
	if x != nil && x.LogicalTime != nil {
		return *x.LogicalTime
	}
	return 0
}

type InteractionSent struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	InteractionClassHandle uint64                 `protobuf:"varint,1,opt,name=interaction_class_handle,json=interactionClassHandle,proto3" json:"interaction_class_handle,omitempty"`
	ProducerFederateHandle uint64                 `protobuf:"varint,2,opt,name=producer_federate_handle,json=producerFederateHandle,proto3" json:"producer_federate_handle,omitempty"`
	Parameters             map[uint64][]byte      `protobuf:"bytes,3,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	LogicalTime            *float64               `protobuf:"fixed64,4,opt,name=logical_time,json=logicalTime,proto3,oneof" json:"logical_time,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *InteractionSent) Reset() {
	*x = InteractionSent{}
	mi := &file_rti_v1_eventlog_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InteractionSent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InteractionSent) ProtoMessage() {}

func (x *InteractionSent) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_eventlog_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InteractionSent.ProtoReflect.Descriptor instead.
func (*InteractionSent) Descriptor() ([]byte, []int) {
	return file_rti_v1_eventlog_proto_rawDescGZIP(), []int{6}
}

func (x *InteractionSent) GetInteractionClassHandle() uint64 {
	if x != nil {
		return x.InteractionClassHandle
	}
	return 0
}

func (x *InteractionSent) GetProducerFederateHandle() uint64 {
	if x != nil {
		return x.ProducerFederateHandle
	}
	return 0
}

func (x *InteractionSent) GetParameters() map[uint64][]byte {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *InteractionSent) GetLogicalTime() float64 {
	if x != nil && x.LogicalTime != nil {
		return *x.LogicalTime
	}
	return 0
}

type TimeAdvanceRequested struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FederateHandle uint64                 `protobuf:"varint,1,opt,name=federate_handle,json=federateHandle,proto3" json:"federate_handle,omitempty"`
	LogicalTime    float64                `protobuf:"fixed64,2,opt,name=logical_time,json=logicalTime,proto3" json:"logical_time,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TimeAdvanceRequested) Reset() {
	*x = TimeAdvanceRequested{}
	mi := &file_rti_v1_eventlog_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeAdvanceRequested) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeAdvanceRequested) ProtoMessage() {}

func (x *TimeAdvanceRequested) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_eventlog_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeAdvanceRequested.ProtoReflect.Descriptor instead.
func (*TimeAdvanceRequested) Descriptor() ([]byte, []int) {
	return file_rti_v1_eventlog_proto_rawDescGZIP(), []int{7}
}

func (x *TimeAdvanceRequested) GetFederateHandle() uint64 {
	if x != nil {
		return x.FederateHandle
	}
	return 0
}

func (x *TimeAdvanceRequested) GetLogicalTime() float64 {
	if x != nil {
		return x.LogicalTime
	}
	return 0
}

type TimeAdvanceGranted struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FederateHandle uint64                 `protobuf:"varint,1,opt,name=federate_handle,json=federateHandle,proto3" json:"federate_handle,omitempty"`
	LogicalTime    float64                `protobuf:"fixed64,2,opt,name=logical_time,json=logicalTime,proto3" json:"logical_time,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TimeAdvanceGranted) Reset() {
	*x = TimeAdvanceGranted{}
	mi := &file_rti_v1_eventlog_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeAdvanceGranted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeAdvanceGranted) ProtoMessage() {}

func (x *TimeAdvanceGranted) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_eventlog_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeAdvanceGranted.ProtoReflect.Descriptor instead.
func (*TimeAdvanceGranted) Descriptor() ([]byte, []int) {
	return file_rti_v1_eventlog_proto_rawDescGZIP(), []int{8}
}

func (x *TimeAdvanceGranted) GetFederateHandle() uint64 {
	if x != nil {
		return x.FederateHandle
	}
	return 0
}

func (x *TimeAdvanceGranted) GetLogicalTime() float64 {
	if x != nil {
		return x.LogicalTime
	}
	return 0
}

type EventFederationHalted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cause         string                 `protobuf:"bytes,1,opt,name=cause,proto3" json:"cause,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventFederationHalted) Reset() {
	*x = EventFederationHalted{}
	mi := &file_rti_v1_eventlog_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventFederationHalted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventFederationHalted) ProtoMessage() {}

func (x *EventFederationHalted) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_eventlog_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventFederationHalted.ProtoReflect.Descriptor instead.
func (*EventFederationHalted) Descriptor() ([]byte, []int) {
	return file_rti_v1_eventlog_proto_rawDescGZIP(), []int{9}
}

func (x *EventFederationHalted) GetCause() string {
	if x != nil {
		return x.Cause
	}
	return ""
}

var File_rti_v1_eventlog_proto protoreflect.FileDescriptor

const file_rti_v1_eventlog_proto_rawDesc = "" +
	"\n" +
	"\x15rti/v1/eventlog.proto\x12\x06rti.v1\x1a\x13rti/v1/common.proto\"\xe9\x04\n" +
	"\x05Event\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x12\x17\n" +
	"\awall_ns\x18\x02 \x01(\x04R\x06wallNs\x127\n" +
	"\n" +
	"fed_joined\x18\n" +
	" \x01(\v2\x16.rti.v1.FederateJoinedH\x00R\tfedJoined\x12=\n" +
	"\ffed_resigned\x18\v \x01(\v2\x18.rti.v1.FederateResignedH\x00R\vfedResigned\x12A\n" +
	"\x0eobj_registered\x18\f \x01(\v2\x18.rti.v1.ObjectRegisteredH\x00R\robjRegistered\x128\n" +
	"\vobj_deleted\x18\r \x01(\v2\x15.rti.v1.ObjectDeletedH\x00R\n" +
	"objDeleted\x12=\n" +
	"\fattr_updated\x18\x0e \x01(\v2\x18.rti.v1.AttributeUpdatedH\x00R\vattrUpdated\x128\n" +
	"\n" +
	"inter_sent\x18\x0f \x01(\v2\x17.rti.v1.InteractionSentH\x00R\tinterSent\x12E\n" +
	"\x0etime_requested\x18\x10 \x01(\v2\x1c.rti.v1.TimeAdvanceRequestedH\x00R\rtimeRequested\x12?\n" +
	"\ftime_granted\x18\x11 \x01(\v2\x1a.rti.v1.TimeAdvanceGrantedH\x00R\vtimeGranted\x127\n" +
	"\x06halted\x18c \x01(\v2\x1d.rti.v1.EventFederationHaltedH\x00R\x06haltedB\x06\n" +
	"\x04body\"^\n" +
	"\x0eFederateJoined\x12'\n" +
	"\x0ffederate_handle\x18\x01 \x01(\x04R\x0efederateHandle\x12#\n" +
	"\rfederate_name\x18\x02 \x01(\tR\ffederateName\"i\n" +
	"\x10FederateResigned\x12'\n" +
	"\x0ffederate_handle\x18\x01 \x01(\x04R\x0efederateHandle\x12,\n" +
	"\x06action\x18\x02 \x01(\x0e2\x14.rti.v1.ResignActionR\x06action\"\xbc\x01\n" +
	"\x10ObjectRegistered\x12#\n" +
	"\robject_handle\x18\x01 \x01(\x04R\fobjectHandle\x12.\n" +
	"\x13object_class_handle\x18\x02 \x01(\x04R\x11objectClassHandle\x122\n" +
	"\x15owner_federate_handle\x18\x03 \x01(\x04R\x13ownerFederateHandle\x12\x1f\n" +
	"\vobject_name\x18\x04 \x01(\tR\n" +
	"objectName\"m\n" +
	"\rObjectDeleted\x12#\n" +
	"\robject_handle\x18\x01 \x01(\x04R\fobjectHandle\x12&\n" +
	"\flogical_time\x18\x02 \x01(\x01H\x00R\vlogicalTime\x88\x01\x01B\x0f\n" +
	"\r_logical_time\"\xb3\x02\n" +
	"\x10AttributeUpdated\x12#\n" +
	"\robject_handle\x18\x01 \x01(\x04R\fobjectHandle\x128\n" +
	"\x18producer_federate_handle\x18\x02 \x01(\x04R\x16producerFederateHandle\x12H\n" +
	"\n" +
	"attributes\x18\x03 \x03(\v2(.rti.v1.AttributeUpdated.AttributesEntryR\n" +
	"attributes\x12&\n" +
	"\flogical_time\x18\x04 \x01(\x01H\x00R\vlogicalTime\x88\x01\x01\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x04R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01B\x0f\n" +
	"\r_logical_time\"\xc6\x02\n" +
	"\x0fInteractionSent\x128\n" +
	"\x18interaction_class_handle\x18\x01 \x01(\x04R\x16interactionClassHandle\x128\n" +
	"\x18producer_federate_handle\x18\x02 \x01(\x04R\x16producerFederateHandle\x12G\n" +
	"\n" +
	"parameters\x18\x03 \x03(\v2'.rti.v1.InteractionSent.ParametersEntryR\n" +
	"parameters\x12&\n" +
	"\flogical_time\x18\x04 \x01(\x01H\x00R\vlogicalTime\x88\x01\x01\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x04R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01B\x0f\n" +
	"\r_logical_time\"b\n" +
	"\x14TimeAdvanceRequested\x12'\n" +
	"\x0ffederate_handle\x18\x01 \x01(\x04R\x0efederateHandle\x12!\n" +
	"\flogical_time\x18\x02 \x01(\x01R\vlogicalTime\"`\n" +
	"\x12TimeAdvanceGranted\x12'\n" +
	"\x0ffederate_handle\x18\x01 \x01(\x04R\x0efederateHandle\x12!\n" +
	"\flogical_time\x18\x02 \x01(\x01R\vlogicalTime\"-\n" +
	"\x15EventFederationHalted\x12\x14\n" +
	"\x05cause\x18\x01 \x01(\tR\x05causeB<Z:github.com/cbchoi/gorti/rti/internal/genproto/rti/v1;rtiv1b\x06proto3"

var (
	file_rti_v1_eventlog_proto_rawDescOnce sync.Once
	file_rti_v1_eventlog_proto_rawDescData []byte
)

func file_rti_v1_eventlog_proto_rawDescGZIP() []byte {
	file_rti_v1_eventlog_proto_rawDescOnce.Do(func() {
		file_rti_v1_eventlog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rti_v1_eventlog_proto_rawDesc), len(file_rti_v1_eventlog_proto_rawDesc)))
	})
	return file_rti_v1_eventlog_proto_rawDescData
}

var file_rti_v1_eventlog_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_rti_v1_eventlog_proto_goTypes = []any{
	(*Event)(nil),                 // 0: rti.v1.Event
	(*FederateJoined)(nil),        // 1: rti.v1.FederateJoined
	(*FederateResigned)(nil),      // 2: rti.v1.FederateResigned
	(*ObjectRegistered)(nil),      // 3: rti.v1.ObjectRegistered
	(*ObjectDeleted)(nil),         // 4: rti.v1.ObjectDeleted
	(*AttributeUpdated)(nil),      // 5: rti.v1.AttributeUpdated
	(*InteractionSent)(nil),       // 6: rti.v1.InteractionSent
	(*TimeAdvanceRequested)(nil),  // 7: rti.v1.TimeAdvanceRequested
	(*TimeAdvanceGranted)(nil),    // 8: rti.v1.TimeAdvanceGranted
	(*EventFederationHalted)(nil), // 9: rti.v1.EventFederationHalted
	nil,                           // 10: rti.v1.AttributeUpdated.AttributesEntry
	nil,                           // 11: rti.v1.InteractionSent.ParametersEntry
	(ResignAction)(0),             // 12: rti.v1.ResignAction
}
var file_rti_v1_eventlog_proto_depIdxs = []int32{
	1,  // 0: rti.v1.Event.fed_joined:type_name -> rti.v1.FederateJoined
	2,  // 1: rti.v1.Event.fed_resigned:type_name -> rti.v1.FederateResigned
	3,  // 2: rti.v1.Event.obj_registered:type_name -> rti.v1.ObjectRegistered
	4,  // 3: rti.v1.Event.obj_deleted:type_name -> rti.v1.ObjectDeleted
	5,  // 4: rti.v1.Event.attr_updated:type_name -> rti.v1.AttributeUpdated
	6,  // 5: rti.v1.Event.inter_sent:type_name -> rti.v1.InteractionSent
	7,  // 6: rti.v1.Event.time_requested:type_name -> rti.v1.TimeAdvanceRequested
	8,  // 7: rti.v1.Event.time_granted:type_name -> rti.v1.TimeAdvanceGranted
	9,  // 8: rti.v1.Event.halted:type_name -> rti.v1.EventFederationHalted
	12, // 9: rti.v1.FederateResigned.action:type_name -> rti.v1.ResignAction
	10, // 10: rti.v1.AttributeUpdated.attributes:type_name -> rti.v1.AttributeUpdated.AttributesEntry
	11, // 11: rti.v1.InteractionSent.parameters:type_name -> rti.v1.InteractionSent.ParametersEntry
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_rti_v1_eventlog_proto_init() }
func file_rti_v1_eventlog_proto_init() {
	if File_rti_v1_eventlog_proto != nil {
		return
	}
	file_rti_v1_common_proto_init()
	file_rti_v1_eventlog_proto_msgTypes[0].OneofWrappers = []any{
		(*Event_FedJoined)(nil),
		(*Event_FedResigned)(nil),
		(*Event_ObjRegistered)(nil),
		(*Event_ObjDeleted)(nil),
		(*Event_AttrUpdated)(nil),
		(*Event_InterSent)(nil),
		(*Event_TimeRequested)(nil),
		(*Event_TimeGranted)(nil),
		(*Event_Halted)(nil),
	}
	file_rti_v1_eventlog_proto_msgTypes[4].OneofWrappers = []any{}
	file_rti_v1_eventlog_proto_msgTypes[5].OneofWrappers = []any{}
	file_rti_v1_eventlog_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rti_v1_eventlog_proto_rawDesc), len(file_rti_v1_eventlog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rti_v1_eventlog_proto_goTypes,
		DependencyIndexes: file_rti_v1_eventlog_proto_depIdxs,
		MessageInfos:      file_rti_v1_eventlog_proto_msgTypes,
	}.Build()
	File_rti_v1_eventlog_proto = out.File
	file_rti_v1_eventlog_proto_goTypes = nil
	file_rti_v1_eventlog_proto_depIdxs = nil
}
