// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: rti/v1/federation.proto

package rtiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TransportMode selects the data-plane wire path for a federation.
// M19 Phase 1a — see docs/m19-dds-adapter.md §2.1 (two modes side by
// side) and §4.1 (proto changes). UNSPECIFIED is treated as GRPC for
// backward-compat with cut-2 wire clients.
type TransportMode int32

const (
	TransportMode_TRANSPORT_MODE_UNSPECIFIED TransportMode = 0
	TransportMode_TRANSPORT_MODE_GRPC        TransportMode = 1
	TransportMode_TRANSPORT_MODE_DDS         TransportMode = 2
)

// Enum value maps for TransportMode.
var (
	TransportMode_name = map[int32]string{
		0: "TRANSPORT_MODE_UNSPECIFIED",
		1: "TRANSPORT_MODE_GRPC",
		2: "TRANSPORT_MODE_DDS",
	}
	TransportMode_value = map[string]int32{
		"TRANSPORT_MODE_UNSPECIFIED": 0,
		"TRANSPORT_MODE_GRPC":        1,
		"TRANSPORT_MODE_DDS":         2,
	}
)

func (x TransportMode) Enum() *TransportMode {
	p := new(TransportMode)
	*p = x
	return p
}

func (x TransportMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransportMode) Descriptor() protoreflect.EnumDescriptor {
	return file_rti_v1_federation_proto_enumTypes[0].Descriptor()
}

func (TransportMode) Type() protoreflect.EnumType {
	return &file_rti_v1_federation_proto_enumTypes[0]
}

func (x TransportMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransportMode.Descriptor instead.
func (TransportMode) EnumDescriptor() ([]byte, []int) {
	return file_rti_v1_federation_proto_rawDescGZIP(), []int{0}
}

type CreateFederationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WireVersion    WireVersion            `protobuf:"varint,1,opt,name=wire_version,json=wireVersion,proto3,enum=rti.v1.WireVersion" json:"wire_version,omitempty"`
	FederationName string                 `protobuf:"bytes,2,opt,name=federation_name,json=federationName,proto3" json:"federation_name,omitempty"`
	FomModules     []*FOMModule           `protobuf:"bytes,3,rep,name=fom_modules,json=fomModules,proto3" json:"fom_modules,omitempty"`
	Mode           Mode                   `protobuf:"varint,4,opt,name=mode,proto3,enum=rti.v1.Mode" json:"mode,omitempty"`
	// Stall-detection timeout in seconds. 0 = use server default (60s).
	StallTimeoutSeconds float64 `protobuf:"fixed64,5,opt,name=stall_timeout_seconds,json=stallTimeoutSeconds,proto3" json:"stall_timeout_seconds,omitempty"`
	// Optional deterministic seed override. 0 = derive from name + creation time.
	Seed uint64 `protobuf:"varint,6,opt,name=seed,proto3" json:"seed,omitempty"`
	// M19 Phase 1a (docs/m19-dds-adapter.md §4.1): optional data-plane
	// transport mode. Absent / TRANSPORT_MODE_UNSPECIFIED → GRPC for
	// backward-compat (the cut-2 wire path). DDS requires the rtid
	// binary to have been built with `-tags=dds` AND the operator to
	// have started rtid with `--enable-dds=true`; otherwise the gRPC
	// handler rejects the create with FailedPrecondition + a clear
	// "this rtid was not built with DDS support" message. Append-only:
	// old federates that omit this field are treated as GRPC.
	TransportMode TransportMode `protobuf:"varint,7,opt,name=transport_mode,json=transportMode,proto3,enum=rti.v1.TransportMode" json:"transport_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFederationRequest) Reset() {
	*x = CreateFederationRequest{}
	mi := &file_rti_v1_federation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFederationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFederationRequest) ProtoMessage() {}

func (x *CreateFederationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_federation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFederationRequest.ProtoReflect.Descriptor instead.
func (*CreateFederationRequest) Descriptor() ([]byte, []int) {
	return file_rti_v1_federation_proto_rawDescGZIP(), []int{0}
}

func (x *CreateFederationRequest) GetWireVersion() WireVersion {
	if x != nil {
		return x.WireVersion
	}
	return WireVersion_WIRE_VERSION_UNSPECIFIED
}

func (x *CreateFederationRequest) GetFederationName() string {
	if x != nil {
		return x.FederationName
	}
	return ""
}

func (x *CreateFederationRequest) GetFomModules() []*FOMModule {
	if x != nil {
		return x.FomModules
	}
	return nil
}

func (x *CreateFederationRequest) GetMode() Mode {
	if x != nil {
		return x.Mode
	}
	return Mode_MODE_UNSPECIFIED
}

func (x *CreateFederationRequest) GetStallTimeoutSeconds() float64 {
	if x != nil {
		return x.StallTimeoutSeconds
	}
	return 0
}

func (x *CreateFederationRequest) GetSeed() uint64 {
	if x != nil {
		return x.Seed
	}
	return 0
}

func (x *CreateFederationRequest) GetTransportMode() TransportMode {
	if x != nil {
		return x.TransportMode
	}
	return TransportMode_TRANSPORT_MODE_UNSPECIFIED
}

type CreateFederationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Echo of the seed actually applied (useful when client supplied 0).
	EffectiveSeed uint64 `protobuf:"varint,1,opt,name=effective_seed,json=effectiveSeed,proto3" json:"effective_seed,omitempty"`
	// Generation assigned to this concrete federation execution.
	FederationGeneration uint64 `protobuf:"varint,2,opt,name=federation_generation,json=federationGeneration,proto3" json:"federation_generation,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CreateFederationResponse) Reset() {
	*x = CreateFederationResponse{}
	mi := &file_rti_v1_federation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFederationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFederationResponse) ProtoMessage() {}

func (x *CreateFederationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_federation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFederationResponse.ProtoReflect.Descriptor instead.
func (*CreateFederationResponse) Descriptor() ([]byte, []int) {
	return file_rti_v1_federation_proto_rawDescGZIP(), []int{1}
}

func (x *CreateFederationResponse) GetEffectiveSeed() uint64 {
	if x != nil {
		return x.EffectiveSeed
	}
	return 0
}

func (x *CreateFederationResponse) GetFederationGeneration() uint64 {
	if x != nil {
		return x.FederationGeneration
	}
	return 0
}

type DestroyFederationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WireVersion    WireVersion            `protobuf:"varint,1,opt,name=wire_version,json=wireVersion,proto3,enum=rti.v1.WireVersion" json:"wire_version,omitempty"`
	FederationName string                 `protobuf:"bytes,2,opt,name=federation_name,json=federationName,proto3" json:"federation_name,omitempty"`
	// Required by generation-aware servers; presence distinguishes generation
	// zero from a legacy client that omitted the fencing token.
	ExpectedFederationGeneration *uint64 `protobuf:"varint,3,opt,name=expected_federation_generation,json=expectedFederationGeneration,proto3,oneof" json:"expected_federation_generation,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *DestroyFederationRequest) Reset() {
	*x = DestroyFederationRequest{}
	mi := &file_rti_v1_federation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyFederationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyFederationRequest) ProtoMessage() {}

func (x *DestroyFederationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_federation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyFederationRequest.ProtoReflect.Descriptor instead.
func (*DestroyFederationRequest) Descriptor() ([]byte, []int) {
	return file_rti_v1_federation_proto_rawDescGZIP(), []int{2}
}

func (x *DestroyFederationRequest) GetWireVersion() WireVersion {
	if x != nil {
		return x.WireVersion
	}
	return WireVersion_WIRE_VERSION_UNSPECIFIED
}

func (x *DestroyFederationRequest) GetFederationName() string {
	if x != nil {
		return x.FederationName
	}
	return ""
}

func (x *DestroyFederationRequest) GetExpectedFederationGeneration() uint64 {
	if x != nil && x.ExpectedFederationGeneration != nil {
		return *x.ExpectedFederationGeneration
	}
	return 0
}

type JoinFederationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WireVersion    WireVersion            `protobuf:"varint,1,opt,name=wire_version,json=wireVersion,proto3,enum=rti.v1.WireVersion" json:"wire_version,omitempty"`
	FederationName string                 `protobuf:"bytes,2,opt,name=federation_name,json=federationName,proto3" json:"federation_name,omitempty"`
	FederateName   string                 `protobuf:"bytes,3,opt,name=federate_name,json=federateName,proto3" json:"federate_name,omitempty"`
	// M13 thread B (docs/srs.md §10.4): optional federate type designator.
	// Recorded by federation.Manager and surfaced via the MOM HLAfederate
	// attribute set as HLAfederateType. Wire-version compatible: an
	// unset / empty field is treated as "no type declared" (preserving
	// the cut-1 default behavior).
	FederateType string `protobuf:"bytes,4,opt,name=federate_type,json=federateType,proto3" json:"federate_type,omitempty"`
	// Fences a delayed join from entering a same-name replacement execution.
	ExpectedFederationGeneration *uint64 `protobuf:"varint,5,opt,name=expected_federation_generation,json=expectedFederationGeneration,proto3,oneof" json:"expected_federation_generation,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *JoinFederationRequest) Reset() {
	*x = JoinFederationRequest{}
	mi := &file_rti_v1_federation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinFederationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinFederationRequest) ProtoMessage() {}

func (x *JoinFederationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_federation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinFederationRequest.ProtoReflect.Descriptor instead.
func (*JoinFederationRequest) Descriptor() ([]byte, []int) {
	return file_rti_v1_federation_proto_rawDescGZIP(), []int{3}
}

func (x *JoinFederationRequest) GetWireVersion() WireVersion {
	if x != nil {
		return x.WireVersion
	}
	return WireVersion_WIRE_VERSION_UNSPECIFIED
}

func (x *JoinFederationRequest) GetFederationName() string {
	if x != nil {
		return x.FederationName
	}
	return ""
}

func (x *JoinFederationRequest) GetFederateName() string {
	if x != nil {
		return x.FederateName
	}
	return ""
}

func (x *JoinFederationRequest) GetFederateType() string {
	if x != nil {
		return x.FederateType
	}
	return ""
}

func (x *JoinFederationRequest) GetExpectedFederationGeneration() uint64 {
	if x != nil && x.ExpectedFederationGeneration != nil {
		return *x.ExpectedFederationGeneration
	}
	return 0
}

type JoinFederationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Federate handle assigned deterministically by join order.
	FederateHandle uint64 `protobuf:"varint,1,opt,name=federate_handle,json=federateHandle,proto3" json:"federate_handle,omitempty"`
	// M19 Phase 1a (docs/m19-dds-adapter.md §4.1): the federation's
	// data-plane transport mode. Echoes whatever was recorded at
	// CreateFederation time. UNSPECIFIED on responses from cut-2 rtid
	// binaries that pre-date this field — federates handle that as GRPC.
	TransportMode TransportMode `protobuf:"varint,2,opt,name=transport_mode,json=transportMode,proto3,enum=rti.v1.TransportMode" json:"transport_mode,omitempty"`
	// M19 Phase 1a: DDS domain ID for the federation. Only meaningful
	// when transport_mode == TRANSPORT_MODE_DDS; ignored otherwise.
	// Federates joining a DDS-mode federation use this to construct
	// their DomainParticipant. Zero is the DDS default domain.
	DdsDomainId   int32 `protobuf:"varint,3,opt,name=dds_domain_id,json=ddsDomainId,proto3" json:"dds_domain_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinFederationResponse) Reset() {
	*x = JoinFederationResponse{}
	mi := &file_rti_v1_federation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinFederationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinFederationResponse) ProtoMessage() {}

func (x *JoinFederationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_federation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinFederationResponse.ProtoReflect.Descriptor instead.
func (*JoinFederationResponse) Descriptor() ([]byte, []int) {
	return file_rti_v1_federation_proto_rawDescGZIP(), []int{4}
}

func (x *JoinFederationResponse) GetFederateHandle() uint64 {
	if x != nil {
		return x.FederateHandle
	}
	return 0
}

func (x *JoinFederationResponse) GetTransportMode() TransportMode {
	if x != nil {
		return x.TransportMode
	}
	return TransportMode_TRANSPORT_MODE_UNSPECIFIED
}

func (x *JoinFederationResponse) GetDdsDomainId() int32 {
	if x != nil {
		return x.DdsDomainId
	}
	return 0
}

type ResignFederationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WireVersion    WireVersion            `protobuf:"varint,1,opt,name=wire_version,json=wireVersion,proto3,enum=rti.v1.WireVersion" json:"wire_version,omitempty"`
	FederationName string                 `protobuf:"bytes,2,opt,name=federation_name,json=federationName,proto3" json:"federation_name,omitempty"`
	FederateHandle uint64                 `protobuf:"varint,3,opt,name=federate_handle,json=federateHandle,proto3" json:"federate_handle,omitempty"`
	Action         ResignAction           `protobuf:"varint,4,opt,name=action,proto3,enum=rti.v1.ResignAction" json:"action,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ResignFederationRequest) Reset() {
	*x = ResignFederationRequest{}
	mi := &file_rti_v1_federation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResignFederationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResignFederationRequest) ProtoMessage() {}

func (x *ResignFederationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_federation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResignFederationRequest.ProtoReflect.Descriptor instead.
func (*ResignFederationRequest) Descriptor() ([]byte, []int) {
	return file_rti_v1_federation_proto_rawDescGZIP(), []int{5}
}

func (x *ResignFederationRequest) GetWireVersion() WireVersion {
	if x != nil {
		return x.WireVersion
	}
	return WireVersion_WIRE_VERSION_UNSPECIFIED
}

func (x *ResignFederationRequest) GetFederationName() string {
	if x != nil {
		return x.FederationName
	}
	return ""
}

func (x *ResignFederationRequest) GetFederateHandle() uint64 {
	if x != nil {
		return x.FederateHandle
	}
	return 0
}

func (x *ResignFederationRequest) GetAction() ResignAction {
	if x != nil {
		return x.Action
	}
	return ResignAction_RESIGN_ACTION_UNSPECIFIED
}

type ListFederationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WireVersion   WireVersion            `protobuf:"varint,1,opt,name=wire_version,json=wireVersion,proto3,enum=rti.v1.WireVersion" json:"wire_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFederationsRequest) Reset() {
	*x = ListFederationsRequest{}
	mi := &file_rti_v1_federation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFederationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFederationsRequest) ProtoMessage() {}

func (x *ListFederationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_federation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFederationsRequest.ProtoReflect.Descriptor instead.
func (*ListFederationsRequest) Descriptor() ([]byte, []int) {
	return file_rti_v1_federation_proto_rawDescGZIP(), []int{6}
}

func (x *ListFederationsRequest) GetWireVersion() WireVersion {
	if x != nil {
		return x.WireVersion
	}
	return WireVersion_WIRE_VERSION_UNSPECIFIED
}

type ListFederationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Federations   []*FederationSummary   `protobuf:"bytes,1,rep,name=federations,proto3" json:"federations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFederationsResponse) Reset() {
	*x = ListFederationsResponse{}
	mi := &file_rti_v1_federation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFederationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFederationsResponse) ProtoMessage() {}

func (x *ListFederationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_federation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFederationsResponse.ProtoReflect.Descriptor instead.
func (*ListFederationsResponse) Descriptor() ([]byte, []int) {
	return file_rti_v1_federation_proto_rawDescGZIP(), []int{7}
}

func (x *ListFederationsResponse) GetFederations() []*FederationSummary {
	if x != nil {
		return x.Federations
	}
	return nil
}

type FederationSummary struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Name                 string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Mode                 Mode                   `protobuf:"varint,2,opt,name=mode,proto3,enum=rti.v1.Mode" json:"mode,omitempty"`
	FederatesJoined      uint32                 `protobuf:"varint,3,opt,name=federates_joined,json=federatesJoined,proto3" json:"federates_joined,omitempty"`
	FederationGeneration uint64                 `protobuf:"varint,4,opt,name=federation_generation,json=federationGeneration,proto3" json:"federation_generation,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *FederationSummary) Reset() {
	*x = FederationSummary{}
	mi := &file_rti_v1_federation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FederationSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FederationSummary) ProtoMessage() {}

func (x *FederationSummary) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_federation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FederationSummary.ProtoReflect.Descriptor instead.
func (*FederationSummary) Descriptor() ([]byte, []int) {
	return file_rti_v1_federation_proto_rawDescGZIP(), []int{8}
}

func (x *FederationSummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FederationSummary) GetMode() Mode {
	if x != nil {
		return x.Mode
	}
	return Mode_MODE_UNSPECIFIED
}

func (x *FederationSummary) GetFederatesJoined() uint32 {
	if x != nil {
		return x.FederatesJoined
	}
	return 0
}

func (x *FederationSummary) GetFederationGeneration() uint64 {
	if x != nil {
		return x.FederationGeneration
	}
	return 0
}

// ListFederationMembers — IEEE 1516.1-2010 §4.8 listFederationExecutionMembers.
// M24 W3.
type ListFederationMembersRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WireVersion    WireVersion            `protobuf:"varint,1,opt,name=wire_version,json=wireVersion,proto3,enum=rti.v1.WireVersion" json:"wire_version,omitempty"`
	FederationName string                 `protobuf:"bytes,2,opt,name=federation_name,json=federationName,proto3" json:"federation_name,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListFederationMembersRequest) Reset() {
	*x = ListFederationMembersRequest{}
	mi := &file_rti_v1_federation_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFederationMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFederationMembersRequest) ProtoMessage() {}

func (x *ListFederationMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_federation_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFederationMembersRequest.ProtoReflect.Descriptor instead.
func (*ListFederationMembersRequest) Descriptor() ([]byte, []int) {
	return file_rti_v1_federation_proto_rawDescGZIP(), []int{9}
}

func (x *ListFederationMembersRequest) GetWireVersion() WireVersion {
	if x != nil {
		return x.WireVersion
	}
	return WireVersion_WIRE_VERSION_UNSPECIFIED
}

func (x *ListFederationMembersRequest) GetFederationName() string {
	if x != nil {
		return x.FederationName
	}
	return ""
}

type ListFederationMembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Members       []*FederationMember    `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFederationMembersResponse) Reset() {
	*x = ListFederationMembersResponse{}
	mi := &file_rti_v1_federation_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFederationMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFederationMembersResponse) ProtoMessage() {}

func (x *ListFederationMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_federation_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFederationMembersResponse.ProtoReflect.Descriptor instead.
func (*ListFederationMembersResponse) Descriptor() ([]byte, []int) {
	return file_rti_v1_federation_proto_rawDescGZIP(), []int{10}
}

func (x *ListFederationMembersResponse) GetMembers() []*FederationMember {
	if x != nil {
		return x.Members
	}
	return nil
}

type FederationMember struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FederateHandle uint64                 `protobuf:"varint,1,opt,name=federate_handle,json=federateHandle,proto3" json:"federate_handle,omitempty"`
	FederateName   string                 `protobuf:"bytes,2,opt,name=federate_name,json=federateName,proto3" json:"federate_name,omitempty"`
	FederateType   string                 `protobuf:"bytes,3,opt,name=federate_type,json=federateType,proto3" json:"federate_type,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FederationMember) Reset() {
	*x = FederationMember{}
	mi := &file_rti_v1_federation_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FederationMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FederationMember) ProtoMessage() {}

func (x *FederationMember) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_federation_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FederationMember.ProtoReflect.Descriptor instead.
func (*FederationMember) Descriptor() ([]byte, []int) {
	return file_rti_v1_federation_proto_rawDescGZIP(), []int{11}
}

func (x *FederationMember) GetFederateHandle() uint64 {
	if x != nil {
		return x.FederateHandle
	}
	return 0
}

func (x *FederationMember) GetFederateName() string {
	if x != nil {
		return x.FederateName
	}
	return ""
}

func (x *FederationMember) GetFederateType() string {
	if x != nil {
		return x.FederateType
	}
	return ""
}

var File_rti_v1_federation_proto protoreflect.FileDescriptor

const file_rti_v1_federation_proto_rawDesc = "" +
	"\n" +
	"\x17rti/v1/federation.proto\x12\x06rti.v1\x1a\x13rti/v1/common.proto\"\xd6\x02\n" +
	"\x17CreateFederationRequest\x126\n" +
	"\fwire_version\x18\x01 \x01(\x0e2\x13.rti.v1.WireVersionR\vwireVersion\x12'\n" +
	"\x0ffederation_name\x18\x02 \x01(\tR\x0efederationName\x122\n" +
	"\vfom_modules\x18\x03 \x03(\v2\x11.rti.v1.FOMModuleR\n" +
	"fomModules\x12 \n" +
	"\x04mode\x18\x04 \x01(\x0e2\f.rti.v1.ModeR\x04mode\x122\n" +
	"\x15stall_timeout_seconds\x18\x05 \x01(\x01R\x13stallTimeoutSeconds\x12\x12\n" +
	"\x04seed\x18\x06 \x01(\x04R\x04seed\x12<\n" +
	"\x0etransport_mode\x18\a \x01(\x0e2\x15.rti.v1.TransportModeR\rtransportMode\"v\n" +
	"\x18CreateFederationResponse\x12%\n" +
	"\x0eeffective_seed\x18\x01 \x01(\x04R\reffectiveSeed\x123\n" +
	"\x15federation_generation\x18\x02 \x01(\x04R\x14federationGeneration\"\xe9\x01\n" +
	"\x18DestroyFederationRequest\x126\n" +
	"\fwire_version\x18\x01 \x01(\x0e2\x13.rti.v1.WireVersionR\vwireVersion\x12'\n" +
	"\x0ffederation_name\x18\x02 \x01(\tR\x0efederationName\x12I\n" +
	"\x1eexpected_federation_generation\x18\x03 \x01(\x04H\x00R\x1cexpectedFederationGeneration\x88\x01\x01B!\n" +
	"\x1f_expected_federation_generation\"\xb0\x02\n" +
	"\x15JoinFederationRequest\x126\n" +
	"\fwire_version\x18\x01 \x01(\x0e2\x13.rti.v1.WireVersionR\vwireVersion\x12'\n" +
	"\x0ffederation_name\x18\x02 \x01(\tR\x0efederationName\x12#\n" +
	"\rfederate_name\x18\x03 \x01(\tR\ffederateName\x12#\n" +
	"\rfederate_type\x18\x04 \x01(\tR\ffederateType\x12I\n" +
	"\x1eexpected_federation_generation\x18\x05 \x01(\x04H\x00R\x1cexpectedFederationGeneration\x88\x01\x01B!\n" +
	"\x1f_expected_federation_generation\"\xa3\x01\n" +
	"\x16JoinFederationResponse\x12'\n" +
	"\x0ffederate_handle\x18\x01 \x01(\x04R\x0efederateHandle\x12<\n" +
	"\x0etransport_mode\x18\x02 \x01(\x0e2\x15.rti.v1.TransportModeR\rtransportMode\x12\"\n" +
	"\rdds_domain_id\x18\x03 \x01(\x05R\vddsDomainId\"\xd1\x01\n" +
	"\x17ResignFederationRequest\x126\n" +
	"\fwire_version\x18\x01 \x01(\x0e2\x13.rti.v1.WireVersionR\vwireVersion\x12'\n" +
	"\x0ffederation_name\x18\x02 \x01(\tR\x0efederationName\x12'\n" +
	"\x0ffederate_handle\x18\x03 \x01(\x04R\x0efederateHandle\x12,\n" +
	"\x06action\x18\x04 \x01(\x0e2\x14.rti.v1.ResignActionR\x06action\"P\n" +
	"\x16ListFederationsRequest\x126\n" +
	"\fwire_version\x18\x01 \x01(\x0e2\x13.rti.v1.WireVersionR\vwireVersion\"V\n" +
	"\x17ListFederationsResponse\x12;\n" +
	"\vfederations\x18\x01 \x03(\v2\x19.rti.v1.FederationSummaryR\vfederations\"\xa9\x01\n" +
	"\x11FederationSummary\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\x04mode\x18\x02 \x01(\x0e2\f.rti.v1.ModeR\x04mode\x12)\n" +
	"\x10federates_joined\x18\x03 \x01(\rR\x0ffederatesJoined\x123\n" +
	"\x15federation_generation\x18\x04 \x01(\x04R\x14federationGeneration\"\x7f\n" +
	"\x1cListFederationMembersRequest\x126\n" +
	"\fwire_version\x18\x01 \x01(\x0e2\x13.rti.v1.WireVersionR\vwireVersion\x12'\n" +
	"\x0ffederation_name\x18\x02 \x01(\tR\x0efederationName\"S\n" +
	"\x1dListFederationMembersResponse\x122\n" +
	"\amembers\x18\x01 \x03(\v2\x18.rti.v1.FederationMemberR\amembers\"\x85\x01\n" +
	"\x10FederationMember\x12'\n" +
	"\x0ffederate_handle\x18\x01 \x01(\x04R\x0efederateHandle\x12#\n" +
	"\rfederate_name\x18\x02 \x01(\tR\ffederateName\x12#\n" +
	"\rfederate_type\x18\x03 \x01(\tR\ffederateType*`\n" +
	"\rTransportMode\x12\x1e\n" +
	"\x1aTRANSPORT_MODE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13TRANSPORT_MODE_GRPC\x10\x01\x12\x16\n" +
	"\x12TRANSPORT_MODE_DDS\x10\x022\xff\x03\n" +
	"\x11FederationService\x12U\n" +
	"\x10CreateFederation\x12\x1f.rti.v1.CreateFederationRequest\x1a .rti.v1.CreateFederationResponse\x12D\n" +
	"\x11DestroyFederation\x12 .rti.v1.DestroyFederationRequest\x1a\r.rti.v1.Empty\x12O\n" +
	"\x0eJoinFederation\x12\x1d.rti.v1.JoinFederationRequest\x1a\x1e.rti.v1.JoinFederationResponse\x12B\n" +
	"\x10ResignFederation\x12\x1f.rti.v1.ResignFederationRequest\x1a\r.rti.v1.Empty\x12R\n" +
	"\x0fListFederations\x12\x1e.rti.v1.ListFederationsRequest\x1a\x1f.rti.v1.ListFederationsResponse\x12d\n" +
	"\x15ListFederationMembers\x12$.rti.v1.ListFederationMembersRequest\x1a%.rti.v1.ListFederationMembersResponseB<Z:github.com/cbchoi/gorti/rti/internal/genproto/rti/v1;rtiv1b\x06proto3"

var (
	file_rti_v1_federation_proto_rawDescOnce sync.Once
	file_rti_v1_federation_proto_rawDescData []byte
)

func file_rti_v1_federation_proto_rawDescGZIP() []byte {
	file_rti_v1_federation_proto_rawDescOnce.Do(func() {
		file_rti_v1_federation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rti_v1_federation_proto_rawDesc), len(file_rti_v1_federation_proto_rawDesc)))
	})
	return file_rti_v1_federation_proto_rawDescData
}

var file_rti_v1_federation_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_rti_v1_federation_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_rti_v1_federation_proto_goTypes = []any{
	(TransportMode)(0),                    // 0: rti.v1.TransportMode
	(*CreateFederationRequest)(nil),       // 1: rti.v1.CreateFederationRequest
	(*CreateFederationResponse)(nil),      // 2: rti.v1.CreateFederationResponse
	(*DestroyFederationRequest)(nil),      // 3: rti.v1.DestroyFederationRequest
	(*JoinFederationRequest)(nil),         // 4: rti.v1.JoinFederationRequest
	(*JoinFederationResponse)(nil),        // 5: rti.v1.JoinFederationResponse
	(*ResignFederationRequest)(nil),       // 6: rti.v1.ResignFederationRequest
	(*ListFederationsRequest)(nil),        // 7: rti.v1.ListFederationsRequest
	(*ListFederationsResponse)(nil),       // 8: rti.v1.ListFederationsResponse
	(*FederationSummary)(nil),             // 9: rti.v1.FederationSummary
	(*ListFederationMembersRequest)(nil),  // 10: rti.v1.ListFederationMembersRequest
	(*ListFederationMembersResponse)(nil), // 11: rti.v1.ListFederationMembersResponse
	(*FederationMember)(nil),              // 12: rti.v1.FederationMember
	(WireVersion)(0),                      // 13: rti.v1.WireVersion
	(*FOMModule)(nil),                     // 14: rti.v1.FOMModule
	(Mode)(0),                             // 15: rti.v1.Mode
	(ResignAction)(0),                     // 16: rti.v1.ResignAction
	(*Empty)(nil),                         // 17: rti.v1.Empty
}
var file_rti_v1_federation_proto_depIdxs = []int32{
	13, // 0: rti.v1.CreateFederationRequest.wire_version:type_name -> rti.v1.WireVersion
	14, // 1: rti.v1.CreateFederationRequest.fom_modules:type_name -> rti.v1.FOMModule
	15, // 2: rti.v1.CreateFederationRequest.mode:type_name -> rti.v1.Mode
	0,  // 3: rti.v1.CreateFederationRequest.transport_mode:type_name -> rti.v1.TransportMode
	13, // 4: rti.v1.DestroyFederationRequest.wire_version:type_name -> rti.v1.WireVersion
	13, // 5: rti.v1.JoinFederationRequest.wire_version:type_name -> rti.v1.WireVersion
	0,  // 6: rti.v1.JoinFederationResponse.transport_mode:type_name -> rti.v1.TransportMode
	13, // 7: rti.v1.ResignFederationRequest.wire_version:type_name -> rti.v1.WireVersion
	16, // 8: rti.v1.ResignFederationRequest.action:type_name -> rti.v1.ResignAction
	13, // 9: rti.v1.ListFederationsRequest.wire_version:type_name -> rti.v1.WireVersion
	9,  // 10: rti.v1.ListFederationsResponse.federations:type_name -> rti.v1.FederationSummary
	15, // 11: rti.v1.FederationSummary.mode:type_name -> rti.v1.Mode
	13, // 12: rti.v1.ListFederationMembersRequest.wire_version:type_name -> rti.v1.WireVersion
	12, // 13: rti.v1.ListFederationMembersResponse.members:type_name -> rti.v1.FederationMember
	1,  // 14: rti.v1.FederationService.CreateFederation:input_type -> rti.v1.CreateFederationRequest
	3,  // 15: rti.v1.FederationService.DestroyFederation:input_type -> rti.v1.DestroyFederationRequest
	4,  // 16: rti.v1.FederationService.JoinFederation:input_type -> rti.v1.JoinFederationRequest
	6,  // 17: rti.v1.FederationService.ResignFederation:input_type -> rti.v1.ResignFederationRequest
	7,  // 18: rti.v1.FederationService.ListFederations:input_type -> rti.v1.ListFederationsRequest
	10, // 19: rti.v1.FederationService.ListFederationMembers:input_type -> rti.v1.ListFederationMembersRequest
	2,  // 20: rti.v1.FederationService.CreateFederation:output_type -> rti.v1.CreateFederationResponse
	17, // 21: rti.v1.FederationService.DestroyFederation:output_type -> rti.v1.Empty
	5,  // 22: rti.v1.FederationService.JoinFederation:output_type -> rti.v1.JoinFederationResponse
	17, // 23: rti.v1.FederationService.ResignFederation:output_type -> rti.v1.Empty
	8,  // 24: rti.v1.FederationService.ListFederations:output_type -> rti.v1.ListFederationsResponse
	11, // 25: rti.v1.FederationService.ListFederationMembers:output_type -> rti.v1.ListFederationMembersResponse
	20, // [20:26] is the sub-list for method output_type
	14, // [14:20] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_rti_v1_federation_proto_init() }
func file_rti_v1_federation_proto_init() {
	if File_rti_v1_federation_proto != nil {
		return
	}
	file_rti_v1_common_proto_init()
	file_rti_v1_federation_proto_msgTypes[2].OneofWrappers = []any{}
	file_rti_v1_federation_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rti_v1_federation_proto_rawDesc), len(file_rti_v1_federation_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rti_v1_federation_proto_goTypes,
		DependencyIndexes: file_rti_v1_federation_proto_depIdxs,
		EnumInfos:         file_rti_v1_federation_proto_enumTypes,
		MessageInfos:      file_rti_v1_federation_proto_msgTypes,
	}.Build()
	File_rti_v1_federation_proto = out.File
	file_rti_v1_federation_proto_goTypes = nil
	file_rti_v1_federation_proto_depIdxs = nil
}
