// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: rti/v1/federation.proto

package rtiv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FederationService_CreateFederation_FullMethodName      = "/rti.v1.FederationService/CreateFederation"
	FederationService_DestroyFederation_FullMethodName     = "/rti.v1.FederationService/DestroyFederation"
	FederationService_JoinFederation_FullMethodName        = "/rti.v1.FederationService/JoinFederation"
	FederationService_ResignFederation_FullMethodName      = "/rti.v1.FederationService/ResignFederation"
	FederationService_ListFederations_FullMethodName       = "/rti.v1.FederationService/ListFederations"
	FederationService_ListFederationMembers_FullMethodName = "/rti.v1.FederationService/ListFederationMembers"
)

// FederationServiceClient is the client API for FederationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// FederationService — federation lifecycle.
// See docs/srs.md §5.1, docs/idd.md §1.1.1.
type FederationServiceClient interface {
	CreateFederation(ctx context.Context, in *CreateFederationRequest, opts ...grpc.CallOption) (*CreateFederationResponse, error)
	DestroyFederation(ctx context.Context, in *DestroyFederationRequest, opts ...grpc.CallOption) (*Empty, error)
	JoinFederation(ctx context.Context, in *JoinFederationRequest, opts ...grpc.CallOption) (*JoinFederationResponse, error)
	ResignFederation(ctx context.Context, in *ResignFederationRequest, opts ...grpc.CallOption) (*Empty, error)
	ListFederations(ctx context.Context, in *ListFederationsRequest, opts ...grpc.CallOption) (*ListFederationsResponse, error)
	// M24 W3 — IEEE 1516.1-2010 §4.8.
	ListFederationMembers(ctx context.Context, in *ListFederationMembersRequest, opts ...grpc.CallOption) (*ListFederationMembersResponse, error)
}

type federationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFederationServiceClient(cc grpc.ClientConnInterface) FederationServiceClient {
	return &federationServiceClient{cc}
}

func (c *federationServiceClient) CreateFederation(ctx context.Context, in *CreateFederationRequest, opts ...grpc.CallOption) (*CreateFederationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateFederationResponse)
	err := c.cc.Invoke(ctx, FederationService_CreateFederation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *federationServiceClient) DestroyFederation(ctx context.Context, in *DestroyFederationRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, FederationService_DestroyFederation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *federationServiceClient) JoinFederation(ctx context.Context, in *JoinFederationRequest, opts ...grpc.CallOption) (*JoinFederationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JoinFederationResponse)
	err := c.cc.Invoke(ctx, FederationService_JoinFederation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *federationServiceClient) ResignFederation(ctx context.Context, in *ResignFederationRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, FederationService_ResignFederation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *federationServiceClient) ListFederations(ctx context.Context, in *ListFederationsRequest, opts ...grpc.CallOption) (*ListFederationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFederationsResponse)
	err := c.cc.Invoke(ctx, FederationService_ListFederations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *federationServiceClient) ListFederationMembers(ctx context.Context, in *ListFederationMembersRequest, opts ...grpc.CallOption) (*ListFederationMembersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFederationMembersResponse)
	err := c.cc.Invoke(ctx, FederationService_ListFederationMembers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FederationServiceServer is the server API for FederationService service.
// All implementations must embed UnimplementedFederationServiceServer
// for forward compatibility.
//
// FederationService — federation lifecycle.
// See docs/srs.md §5.1, docs/idd.md §1.1.1.
type FederationServiceServer interface {
	CreateFederation(context.Context, *CreateFederationRequest) (*CreateFederationResponse, error)
	DestroyFederation(context.Context, *DestroyFederationRequest) (*Empty, error)
	JoinFederation(context.Context, *JoinFederationRequest) (*JoinFederationResponse, error)
	ResignFederation(context.Context, *ResignFederationRequest) (*Empty, error)
	ListFederations(context.Context, *ListFederationsRequest) (*ListFederationsResponse, error)
	// M24 W3 — IEEE 1516.1-2010 §4.8.
	ListFederationMembers(context.Context, *ListFederationMembersRequest) (*ListFederationMembersResponse, error)
	mustEmbedUnimplementedFederationServiceServer()
}

// UnimplementedFederationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFederationServiceServer struct{}

func (UnimplementedFederationServiceServer) CreateFederation(context.Context, *CreateFederationRequest) (*CreateFederationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateFederation not implemented")
}
func (UnimplementedFederationServiceServer) DestroyFederation(context.Context, *DestroyFederationRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DestroyFederation not implemented")
}
func (UnimplementedFederationServiceServer) JoinFederation(context.Context, *JoinFederationRequest) (*JoinFederationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method JoinFederation not implemented")
}
func (UnimplementedFederationServiceServer) ResignFederation(context.Context, *ResignFederationRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ResignFederation not implemented")
}
func (UnimplementedFederationServiceServer) ListFederations(context.Context, *ListFederationsRequest) (*ListFederationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFederations not implemented")
}
func (UnimplementedFederationServiceServer) ListFederationMembers(context.Context, *ListFederationMembersRequest) (*ListFederationMembersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFederationMembers not implemented")
}
func (UnimplementedFederationServiceServer) mustEmbedUnimplementedFederationServiceServer() {}
func (UnimplementedFederationServiceServer) testEmbeddedByValue()                           {}

// UnsafeFederationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FederationServiceServer will
// result in compilation errors.
type UnsafeFederationServiceServer interface {
	mustEmbedUnimplementedFederationServiceServer()
}

func RegisterFederationServiceServer(s grpc.ServiceRegistrar, srv FederationServiceServer) {
	// If the following call panics, it indicates UnimplementedFederationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FederationService_ServiceDesc, srv)
}

func _FederationService_CreateFederation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFederationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FederationServiceServer).CreateFederation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FederationService_CreateFederation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FederationServiceServer).CreateFederation(ctx, req.(*CreateFederationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FederationService_DestroyFederation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DestroyFederationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FederationServiceServer).DestroyFederation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FederationService_DestroyFederation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FederationServiceServer).DestroyFederation(ctx, req.(*DestroyFederationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FederationService_JoinFederation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinFederationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FederationServiceServer).JoinFederation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FederationService_JoinFederation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FederationServiceServer).JoinFederation(ctx, req.(*JoinFederationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FederationService_ResignFederation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResignFederationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FederationServiceServer).ResignFederation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FederationService_ResignFederation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FederationServiceServer).ResignFederation(ctx, req.(*ResignFederationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FederationService_ListFederations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFederationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FederationServiceServer).ListFederations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FederationService_ListFederations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FederationServiceServer).ListFederations(ctx, req.(*ListFederationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FederationService_ListFederationMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFederationMembersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FederationServiceServer).ListFederationMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FederationService_ListFederationMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FederationServiceServer).ListFederationMembers(ctx, req.(*ListFederationMembersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FederationService_ServiceDesc is the grpc.ServiceDesc for FederationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FederationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rti.v1.FederationService",
	HandlerType: (*FederationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateFederation",
			Handler:    _FederationService_CreateFederation_Handler,
		},
		{
			MethodName: "DestroyFederation",
			Handler:    _FederationService_DestroyFederation_Handler,
		},
		{
			MethodName: "JoinFederation",
			Handler:    _FederationService_JoinFederation_Handler,
		},
		{
			MethodName: "ResignFederation",
			Handler:    _FederationService_ResignFederation_Handler,
		},
		{
			MethodName: "ListFederations",
			Handler:    _FederationService_ListFederations_Handler,
		},
		{
			MethodName: "ListFederationMembers",
			Handler:    _FederationService_ListFederationMembers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rti/v1/federation.proto",
}
