// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: rti/v1/local_lrc.proto

package rtiv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LocalLRCService_Exchange_FullMethodName = "/rti.v1.LocalLRCService/Exchange"
)

// LocalLRCServiceClient is the client API for LocalLRCService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// LocalLRCService is the ordered, receive-order Object Management fast path.
// The first request must be LocalLRCOpen. Later requests carry gapless local
// sequence numbers; each ACK commits every request through committed_through.
type LocalLRCServiceClient interface {
	Exchange(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[LocalLRCRequest, LocalLRCAck], error)
}

type localLRCServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLocalLRCServiceClient(cc grpc.ClientConnInterface) LocalLRCServiceClient {
	return &localLRCServiceClient{cc}
}

func (c *localLRCServiceClient) Exchange(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[LocalLRCRequest, LocalLRCAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LocalLRCService_ServiceDesc.Streams[0], LocalLRCService_Exchange_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LocalLRCRequest, LocalLRCAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LocalLRCService_ExchangeClient = grpc.BidiStreamingClient[LocalLRCRequest, LocalLRCAck]

// LocalLRCServiceServer is the server API for LocalLRCService service.
// All implementations must embed UnimplementedLocalLRCServiceServer
// for forward compatibility.
//
// LocalLRCService is the ordered, receive-order Object Management fast path.
// The first request must be LocalLRCOpen. Later requests carry gapless local
// sequence numbers; each ACK commits every request through committed_through.
type LocalLRCServiceServer interface {
	Exchange(grpc.BidiStreamingServer[LocalLRCRequest, LocalLRCAck]) error
	mustEmbedUnimplementedLocalLRCServiceServer()
}

// UnimplementedLocalLRCServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLocalLRCServiceServer struct{}

func (UnimplementedLocalLRCServiceServer) Exchange(grpc.BidiStreamingServer[LocalLRCRequest, LocalLRCAck]) error {
	return status.Error(codes.Unimplemented, "method Exchange not implemented")
}
func (UnimplementedLocalLRCServiceServer) mustEmbedUnimplementedLocalLRCServiceServer() {}
func (UnimplementedLocalLRCServiceServer) testEmbeddedByValue()                         {}

// UnsafeLocalLRCServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LocalLRCServiceServer will
// result in compilation errors.
type UnsafeLocalLRCServiceServer interface {
	mustEmbedUnimplementedLocalLRCServiceServer()
}

func RegisterLocalLRCServiceServer(s grpc.ServiceRegistrar, srv LocalLRCServiceServer) {
	// If the following call panics, it indicates UnimplementedLocalLRCServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LocalLRCService_ServiceDesc, srv)
}

func _LocalLRCService_Exchange_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(LocalLRCServiceServer).Exchange(&grpc.GenericServerStream[LocalLRCRequest, LocalLRCAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LocalLRCService_ExchangeServer = grpc.BidiStreamingServer[LocalLRCRequest, LocalLRCAck]

// LocalLRCService_ServiceDesc is the grpc.ServiceDesc for LocalLRCService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LocalLRCService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rti.v1.LocalLRCService",
	HandlerType: (*LocalLRCServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Exchange",
			Handler:       _LocalLRCService_Exchange_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "rti/v1/local_lrc.proto",
}
