// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: rti/v1/local_lrc.proto

package rtiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LocalLRCRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*LocalLRCRequest_Open
	//	*LocalLRCRequest_AttributeUpdate
	//	*LocalLRCRequest_Interaction
	//	*LocalLRCRequest_Flush
	//	*LocalLRCRequest_Batch
	Body          isLocalLRCRequest_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalLRCRequest) Reset() {
	*x = LocalLRCRequest{}
	mi := &file_rti_v1_local_lrc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalLRCRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalLRCRequest) ProtoMessage() {}

func (x *LocalLRCRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_local_lrc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalLRCRequest.ProtoReflect.Descriptor instead.
func (*LocalLRCRequest) Descriptor() ([]byte, []int) {
	return file_rti_v1_local_lrc_proto_rawDescGZIP(), []int{0}
}

func (x *LocalLRCRequest) GetBody() isLocalLRCRequest_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *LocalLRCRequest) GetOpen() *LocalLRCOpen {
	if x != nil {
		if x, ok := x.Body.(*LocalLRCRequest_Open); ok {
			return x.Open
		}
	}
	return nil
}

func (x *LocalLRCRequest) GetAttributeUpdate() *LocalLRCAttributeUpdate {
	if x != nil {
		if x, ok := x.Body.(*LocalLRCRequest_AttributeUpdate); ok {
			return x.AttributeUpdate
		}
	}
	return nil
}

func (x *LocalLRCRequest) GetInteraction() *LocalLRCInteraction {
	if x != nil {
		if x, ok := x.Body.(*LocalLRCRequest_Interaction); ok {
			return x.Interaction
		}
	}
	return nil
}

func (x *LocalLRCRequest) GetFlush() *LocalLRCFlush {
	if x != nil {
		if x, ok := x.Body.(*LocalLRCRequest_Flush); ok {
			return x.Flush
		}
	}
	return nil
}

func (x *LocalLRCRequest) GetBatch() *LocalLRCBatch {
	if x != nil {
		if x, ok := x.Body.(*LocalLRCRequest_Batch); ok {
			return x.Batch
		}
	}
	return nil
}

type isLocalLRCRequest_Body interface {
	isLocalLRCRequest_Body()
}

type LocalLRCRequest_Open struct {
	Open *LocalLRCOpen `protobuf:"bytes,1,opt,name=open,proto3,oneof"`
}

type LocalLRCRequest_AttributeUpdate struct {
	AttributeUpdate *LocalLRCAttributeUpdate `protobuf:"bytes,2,opt,name=attribute_update,json=attributeUpdate,proto3,oneof"`
}

type LocalLRCRequest_Interaction struct {
	Interaction *LocalLRCInteraction `protobuf:"bytes,3,opt,name=interaction,proto3,oneof"`
}

type LocalLRCRequest_Flush struct {
	Flush *LocalLRCFlush `protobuf:"bytes,4,opt,name=flush,proto3,oneof"`
}

type LocalLRCRequest_Batch struct {
	Batch *LocalLRCBatch `protobuf:"bytes,5,opt,name=batch,proto3,oneof"`
}

func (*LocalLRCRequest_Open) isLocalLRCRequest_Body() {}

func (*LocalLRCRequest_AttributeUpdate) isLocalLRCRequest_Body() {}

func (*LocalLRCRequest_Interaction) isLocalLRCRequest_Body() {}

func (*LocalLRCRequest_Flush) isLocalLRCRequest_Body() {}

func (*LocalLRCRequest_Batch) isLocalLRCRequest_Body() {}

type LocalLRCOpen struct {
	state                        protoimpl.MessageState `protogen:"open.v1"`
	WireVersion                  WireVersion            `protobuf:"varint,1,opt,name=wire_version,json=wireVersion,proto3,enum=rti.v1.WireVersion" json:"wire_version,omitempty"`
	FederationName               string                 `protobuf:"bytes,2,opt,name=federation_name,json=federationName,proto3" json:"federation_name,omitempty"`
	FederateHandle               uint64                 `protobuf:"varint,3,opt,name=federate_handle,json=federateHandle,proto3" json:"federate_handle,omitempty"`
	ExpectedFederationGeneration uint64                 `protobuf:"varint,4,opt,name=expected_federation_generation,json=expectedFederationGeneration,proto3" json:"expected_federation_generation,omitempty"`
	// Requested cumulative ACK interval. The server clamps this value.
	AckEvery uint32 `protobuf:"varint,5,opt,name=ack_every,json=ackEvery,proto3" json:"ack_every,omitempty"`
	// Requested operation count per batch. Zero preserves the legacy default.
	// The server reports the negotiated limit in the opening ACK.
	RequestedMaxBatchOperations uint32 `protobuf:"varint,6,opt,name=requested_max_batch_operations,json=requestedMaxBatchOperations,proto3" json:"requested_max_batch_operations,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *LocalLRCOpen) Reset() {
	*x = LocalLRCOpen{}
	mi := &file_rti_v1_local_lrc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalLRCOpen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalLRCOpen) ProtoMessage() {}

func (x *LocalLRCOpen) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_local_lrc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalLRCOpen.ProtoReflect.Descriptor instead.
func (*LocalLRCOpen) Descriptor() ([]byte, []int) {
	return file_rti_v1_local_lrc_proto_rawDescGZIP(), []int{1}
}

func (x *LocalLRCOpen) GetWireVersion() WireVersion {
	if x != nil {
		return x.WireVersion
	}
	return WireVersion_WIRE_VERSION_UNSPECIFIED
}

func (x *LocalLRCOpen) GetFederationName() string {
	if x != nil {
		return x.FederationName
	}
	return ""
}

func (x *LocalLRCOpen) GetFederateHandle() uint64 {
	if x != nil {
		return x.FederateHandle
	}
	return 0
}

func (x *LocalLRCOpen) GetExpectedFederationGeneration() uint64 {
	if x != nil {
		return x.ExpectedFederationGeneration
	}
	return 0
}

func (x *LocalLRCOpen) GetAckEvery() uint32 {
	if x != nil {
		return x.AckEvery
	}
	return 0
}

func (x *LocalLRCOpen) GetRequestedMaxBatchOperations() uint32 {
	if x != nil {
		return x.RequestedMaxBatchOperations
	}
	return 0
}

// LocalLRCAttributeUpdate intentionally has no logical-time field. TSO
// operations retain the confirmed unary path until their failure and grant
// semantics have an equivalent pipelined contract.
type LocalLRCAttributeUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sequence      uint64                 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	ObjectHandle  uint64                 `protobuf:"varint,2,opt,name=object_handle,json=objectHandle,proto3" json:"object_handle,omitempty"`
	Attributes    map[uint64][]byte      `protobuf:"bytes,3,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalLRCAttributeUpdate) Reset() {
	*x = LocalLRCAttributeUpdate{}
	mi := &file_rti_v1_local_lrc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalLRCAttributeUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalLRCAttributeUpdate) ProtoMessage() {}

func (x *LocalLRCAttributeUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_local_lrc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalLRCAttributeUpdate.ProtoReflect.Descriptor instead.
func (*LocalLRCAttributeUpdate) Descriptor() ([]byte, []int) {
	return file_rti_v1_local_lrc_proto_rawDescGZIP(), []int{2}
}

func (x *LocalLRCAttributeUpdate) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *LocalLRCAttributeUpdate) GetObjectHandle() uint64 {
	if x != nil {
		return x.ObjectHandle
	}
	return 0
}

func (x *LocalLRCAttributeUpdate) GetAttributes() map[uint64][]byte {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type LocalLRCInteraction struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Sequence               uint64                 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	InteractionClassHandle uint64                 `protobuf:"varint,2,opt,name=interaction_class_handle,json=interactionClassHandle,proto3" json:"interaction_class_handle,omitempty"`
	Parameters             map[uint64][]byte      `protobuf:"bytes,3,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *LocalLRCInteraction) Reset() {
	*x = LocalLRCInteraction{}
	mi := &file_rti_v1_local_lrc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalLRCInteraction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalLRCInteraction) ProtoMessage() {}

func (x *LocalLRCInteraction) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_local_lrc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalLRCInteraction.ProtoReflect.Descriptor instead.
func (*LocalLRCInteraction) Descriptor() ([]byte, []int) {
	return file_rti_v1_local_lrc_proto_rawDescGZIP(), []int{3}
}

func (x *LocalLRCInteraction) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *LocalLRCInteraction) GetInteractionClassHandle() uint64 {
	if x != nil {
		return x.InteractionClassHandle
	}
	return 0
}

func (x *LocalLRCInteraction) GetParameters() map[uint64][]byte {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type LocalLRCOperation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*LocalLRCOperation_AttributeUpdate
	//	*LocalLRCOperation_Interaction
	Body          isLocalLRCOperation_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalLRCOperation) Reset() {
	*x = LocalLRCOperation{}
	mi := &file_rti_v1_local_lrc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalLRCOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalLRCOperation) ProtoMessage() {}

func (x *LocalLRCOperation) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_local_lrc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalLRCOperation.ProtoReflect.Descriptor instead.
func (*LocalLRCOperation) Descriptor() ([]byte, []int) {
	return file_rti_v1_local_lrc_proto_rawDescGZIP(), []int{4}
}

func (x *LocalLRCOperation) GetBody() isLocalLRCOperation_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *LocalLRCOperation) GetAttributeUpdate() *LocalLRCAttributeUpdate {
	if x != nil {
		if x, ok := x.Body.(*LocalLRCOperation_AttributeUpdate); ok {
			return x.AttributeUpdate
		}
	}
	return nil
}

func (x *LocalLRCOperation) GetInteraction() *LocalLRCInteraction {
	if x != nil {
		if x, ok := x.Body.(*LocalLRCOperation_Interaction); ok {
			return x.Interaction
		}
	}
	return nil
}

type isLocalLRCOperation_Body interface {
	isLocalLRCOperation_Body()
}

type LocalLRCOperation_AttributeUpdate struct {
	AttributeUpdate *LocalLRCAttributeUpdate `protobuf:"bytes,1,opt,name=attribute_update,json=attributeUpdate,proto3,oneof"`
}

type LocalLRCOperation_Interaction struct {
	Interaction *LocalLRCInteraction `protobuf:"bytes,2,opt,name=interaction,proto3,oneof"`
}

func (*LocalLRCOperation_AttributeUpdate) isLocalLRCOperation_Body() {}

func (*LocalLRCOperation_Interaction) isLocalLRCOperation_Body() {}

// Operations in a batch are processed in list order. A terminal service error
// commits only the gapless prefix acknowledged by the server.
type LocalLRCBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operations    []*LocalLRCOperation   `protobuf:"bytes,1,rep,name=operations,proto3" json:"operations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalLRCBatch) Reset() {
	*x = LocalLRCBatch{}
	mi := &file_rti_v1_local_lrc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalLRCBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalLRCBatch) ProtoMessage() {}

func (x *LocalLRCBatch) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_local_lrc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalLRCBatch.ProtoReflect.Descriptor instead.
func (*LocalLRCBatch) Descriptor() ([]byte, []int) {
	return file_rti_v1_local_lrc_proto_rawDescGZIP(), []int{5}
}

func (x *LocalLRCBatch) GetOperations() []*LocalLRCOperation {
	if x != nil {
		return x.Operations
	}
	return nil
}

type LocalLRCFlush struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ThroughSequence uint64                 `protobuf:"varint,1,opt,name=through_sequence,json=throughSequence,proto3" json:"through_sequence,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LocalLRCFlush) Reset() {
	*x = LocalLRCFlush{}
	mi := &file_rti_v1_local_lrc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalLRCFlush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalLRCFlush) ProtoMessage() {}

func (x *LocalLRCFlush) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_local_lrc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalLRCFlush.ProtoReflect.Descriptor instead.
func (*LocalLRCFlush) Descriptor() ([]byte, []int) {
	return file_rti_v1_local_lrc_proto_rawDescGZIP(), []int{6}
}

func (x *LocalLRCFlush) GetThroughSequence() uint64 {
	if x != nil {
		return x.ThroughSequence
	}
	return 0
}

type LocalLRCAck struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Every operation with sequence <= committed_through completed the normal
	// server-side service path. Stream failure leaves larger sequences
	// indeterminate and permanently fails the local queue.
	CommittedThrough uint64 `protobuf:"varint,1,opt,name=committed_through,json=committedThrough,proto3" json:"committed_through,omitempty"`
	// Set on the opening ACK so the client can record the negotiated interval.
	AckEvery uint32 `protobuf:"varint,2,opt,name=ack_every,json=ackEvery,proto3" json:"ack_every,omitempty"`
	// Set on the opening ACK. Zero means that the peer supports only one
	// operation per request, preserving compatibility with pre-batch servers.
	MaxBatchOperations uint32 `protobuf:"varint,3,opt,name=max_batch_operations,json=maxBatchOperations,proto3" json:"max_batch_operations,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *LocalLRCAck) Reset() {
	*x = LocalLRCAck{}
	mi := &file_rti_v1_local_lrc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalLRCAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalLRCAck) ProtoMessage() {}

func (x *LocalLRCAck) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_local_lrc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalLRCAck.ProtoReflect.Descriptor instead.
func (*LocalLRCAck) Descriptor() ([]byte, []int) {
	return file_rti_v1_local_lrc_proto_rawDescGZIP(), []int{7}
}

func (x *LocalLRCAck) GetCommittedThrough() uint64 {
	if x != nil {
		return x.CommittedThrough
	}
	return 0
}

func (x *LocalLRCAck) GetAckEvery() uint32 {
	if x != nil {
		return x.AckEvery
	}
	return 0
}

func (x *LocalLRCAck) GetMaxBatchOperations() uint32 {
	if x != nil {
		return x.MaxBatchOperations
	}
	return 0
}

var File_rti_v1_local_lrc_proto protoreflect.FileDescriptor

const file_rti_v1_local_lrc_proto_rawDesc = "" +
	"\n" +
	"\x16rti/v1/local_lrc.proto\x12\x06rti.v1\x1a\x13rti/v1/common.proto\"\xb2\x02\n" +
	"\x0fLocalLRCRequest\x12*\n" +
	"\x04open\x18\x01 \x01(\v2\x14.rti.v1.LocalLRCOpenH\x00R\x04open\x12L\n" +
	"\x10attribute_update\x18\x02 \x01(\v2\x1f.rti.v1.LocalLRCAttributeUpdateH\x00R\x0fattributeUpdate\x12?\n" +
	"\vinteraction\x18\x03 \x01(\v2\x1b.rti.v1.LocalLRCInteractionH\x00R\vinteraction\x12-\n" +
	"\x05flush\x18\x04 \x01(\v2\x15.rti.v1.LocalLRCFlushH\x00R\x05flush\x12-\n" +
	"\x05batch\x18\x05 \x01(\v2\x15.rti.v1.LocalLRCBatchH\x00R\x05batchB\x06\n" +
	"\x04body\"\xc0\x02\n" +
	"\fLocalLRCOpen\x126\n" +
	"\fwire_version\x18\x01 \x01(\x0e2\x13.rti.v1.WireVersionR\vwireVersion\x12'\n" +
	"\x0ffederation_name\x18\x02 \x01(\tR\x0efederationName\x12'\n" +
	"\x0ffederate_handle\x18\x03 \x01(\x04R\x0efederateHandle\x12D\n" +
	"\x1eexpected_federation_generation\x18\x04 \x01(\x04R\x1cexpectedFederationGeneration\x12\x1b\n" +
	"\tack_every\x18\x05 \x01(\rR\backEvery\x12C\n" +
	"\x1erequested_max_batch_operations\x18\x06 \x01(\rR\x1brequestedMaxBatchOperations\"\xea\x01\n" +
	"\x17LocalLRCAttributeUpdate\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x04R\bsequence\x12#\n" +
	"\robject_handle\x18\x02 \x01(\x04R\fobjectHandle\x12O\n" +
	"\n" +
	"attributes\x18\x03 \x03(\v2/.rti.v1.LocalLRCAttributeUpdate.AttributesEntryR\n" +
	"attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x04R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"\xf7\x01\n" +
	"\x13LocalLRCInteraction\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x04R\bsequence\x128\n" +
	"\x18interaction_class_handle\x18\x02 \x01(\x04R\x16interactionClassHandle\x12K\n" +
	"\n" +
	"parameters\x18\x03 \x03(\v2+.rti.v1.LocalLRCInteraction.ParametersEntryR\n" +
	"parameters\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x04R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"\xaa\x01\n" +
	"\x11LocalLRCOperation\x12L\n" +
	"\x10attribute_update\x18\x01 \x01(\v2\x1f.rti.v1.LocalLRCAttributeUpdateH\x00R\x0fattributeUpdate\x12?\n" +
	"\vinteraction\x18\x02 \x01(\v2\x1b.rti.v1.LocalLRCInteractionH\x00R\vinteractionB\x06\n" +
	"\x04body\"J\n" +
	"\rLocalLRCBatch\x129\n" +
	"\n" +
	"operations\x18\x01 \x03(\v2\x19.rti.v1.LocalLRCOperationR\n" +
	"operations\":\n" +
	"\rLocalLRCFlush\x12)\n" +
	"\x10through_sequence\x18\x01 \x01(\x04R\x0fthroughSequence\"\x89\x01\n" +
	"\vLocalLRCAck\x12+\n" +
	"\x11committed_through\x18\x01 \x01(\x04R\x10committedThrough\x12\x1b\n" +
	"\tack_every\x18\x02 \x01(\rR\backEvery\x120\n" +
	"\x14max_batch_operations\x18\x03 \x01(\rR\x12maxBatchOperations2O\n" +
	"\x0fLocalLRCService\x12<\n" +
	"\bExchange\x12\x17.rti.v1.LocalLRCRequest\x1a\x13.rti.v1.LocalLRCAck(\x010\x01B<Z:github.com/cbchoi/gorti/rti/internal/genproto/rti/v1;rtiv1b\x06proto3"

var (
	file_rti_v1_local_lrc_proto_rawDescOnce sync.Once
	file_rti_v1_local_lrc_proto_rawDescData []byte
)

func file_rti_v1_local_lrc_proto_rawDescGZIP() []byte {
	file_rti_v1_local_lrc_proto_rawDescOnce.Do(func() {
		file_rti_v1_local_lrc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rti_v1_local_lrc_proto_rawDesc), len(file_rti_v1_local_lrc_proto_rawDesc)))
	})
	return file_rti_v1_local_lrc_proto_rawDescData
}

var file_rti_v1_local_lrc_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_rti_v1_local_lrc_proto_goTypes = []any{
	(*LocalLRCRequest)(nil),         // 0: rti.v1.LocalLRCRequest
	(*LocalLRCOpen)(nil),            // 1: rti.v1.LocalLRCOpen
	(*LocalLRCAttributeUpdate)(nil), // 2: rti.v1.LocalLRCAttributeUpdate
	(*LocalLRCInteraction)(nil),     // 3: rti.v1.LocalLRCInteraction
	(*LocalLRCOperation)(nil),       // 4: rti.v1.LocalLRCOperation
	(*LocalLRCBatch)(nil),           // 5: rti.v1.LocalLRCBatch
	(*LocalLRCFlush)(nil),           // 6: rti.v1.LocalLRCFlush
	(*LocalLRCAck)(nil),             // 7: rti.v1.LocalLRCAck
	nil,                             // 8: rti.v1.LocalLRCAttributeUpdate.AttributesEntry
	nil,                             // 9: rti.v1.LocalLRCInteraction.ParametersEntry
	(WireVersion)(0),                // 10: rti.v1.WireVersion
}
var file_rti_v1_local_lrc_proto_depIdxs = []int32{
	1,  // 0: rti.v1.LocalLRCRequest.open:type_name -> rti.v1.LocalLRCOpen
	2,  // 1: rti.v1.LocalLRCRequest.attribute_update:type_name -> rti.v1.LocalLRCAttributeUpdate
	3,  // 2: rti.v1.LocalLRCRequest.interaction:type_name -> rti.v1.LocalLRCInteraction
	6,  // 3: rti.v1.LocalLRCRequest.flush:type_name -> rti.v1.LocalLRCFlush
	5,  // 4: rti.v1.LocalLRCRequest.batch:type_name -> rti.v1.LocalLRCBatch
	10, // 5: rti.v1.LocalLRCOpen.wire_version:type_name -> rti.v1.WireVersion
	8,  // 6: rti.v1.LocalLRCAttributeUpdate.attributes:type_name -> rti.v1.LocalLRCAttributeUpdate.AttributesEntry
	9,  // 7: rti.v1.LocalLRCInteraction.parameters:type_name -> rti.v1.LocalLRCInteraction.ParametersEntry
	2,  // 8: rti.v1.LocalLRCOperation.attribute_update:type_name -> rti.v1.LocalLRCAttributeUpdate
	3,  // 9: rti.v1.LocalLRCOperation.interaction:type_name -> rti.v1.LocalLRCInteraction
	4,  // 10: rti.v1.LocalLRCBatch.operations:type_name -> rti.v1.LocalLRCOperation
	0,  // 11: rti.v1.LocalLRCService.Exchange:input_type -> rti.v1.LocalLRCRequest
	7,  // 12: rti.v1.LocalLRCService.Exchange:output_type -> rti.v1.LocalLRCAck
	12, // [12:13] is the sub-list for method output_type
	11, // [11:12] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_rti_v1_local_lrc_proto_init() }
func file_rti_v1_local_lrc_proto_init() {
	if File_rti_v1_local_lrc_proto != nil {
		return
	}
	file_rti_v1_common_proto_init()
	file_rti_v1_local_lrc_proto_msgTypes[0].OneofWrappers = []any{
		(*LocalLRCRequest_Open)(nil),
		(*LocalLRCRequest_AttributeUpdate)(nil),
		(*LocalLRCRequest_Interaction)(nil),
		(*LocalLRCRequest_Flush)(nil),
		(*LocalLRCRequest_Batch)(nil),
	}
	file_rti_v1_local_lrc_proto_msgTypes[4].OneofWrappers = []any{
		(*LocalLRCOperation_AttributeUpdate)(nil),
		(*LocalLRCOperation_Interaction)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rti_v1_local_lrc_proto_rawDesc), len(file_rti_v1_local_lrc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rti_v1_local_lrc_proto_goTypes,
		DependencyIndexes: file_rti_v1_local_lrc_proto_depIdxs,
		MessageInfos:      file_rti_v1_local_lrc_proto_msgTypes,
	}.Build()
	File_rti_v1_local_lrc_proto = out.File
	file_rti_v1_local_lrc_proto_goTypes = nil
	file_rti_v1_local_lrc_proto_depIdxs = nil
}
