// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: rti/v1/mom.proto

package rtiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryFederationAttributesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WireVersion    WireVersion            `protobuf:"varint,1,opt,name=wire_version,json=wireVersion,proto3,enum=rti.v1.WireVersion" json:"wire_version,omitempty"`
	FederationName string                 `protobuf:"bytes,2,opt,name=federation_name,json=federationName,proto3" json:"federation_name,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *QueryFederationAttributesRequest) Reset() {
	*x = QueryFederationAttributesRequest{}
	mi := &file_rti_v1_mom_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryFederationAttributesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryFederationAttributesRequest) ProtoMessage() {}

func (x *QueryFederationAttributesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_mom_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryFederationAttributesRequest.ProtoReflect.Descriptor instead.
func (*QueryFederationAttributesRequest) Descriptor() ([]byte, []int) {
	return file_rti_v1_mom_proto_rawDescGZIP(), []int{0}
}

func (x *QueryFederationAttributesRequest) GetWireVersion() WireVersion {
	if x != nil {
		return x.WireVersion
	}
	return WireVersion_WIRE_VERSION_UNSPECIFIED
}

func (x *QueryFederationAttributesRequest) GetFederationName() string {
	if x != nil {
		return x.FederationName
	}
	return ""
}

// FederationAttributes is the wire-format snapshot of the
// HLAfederation MOM object's attributes per IEEE 1516.1-2010 §10.2.
//
// Cut-3 fields populated:
//   - federation_name (HLAfederationName)
//   - federate_handles (HLAfederatesInFederation, list of federate
//     handles currently joined)
//   - fom_module_names (HLAFOMmoduleDesignatorList)
//
// Cut-3 fields placeholdered for forward-compat (nil/unset):
//   - last_save_name / last_save_time — populated when the
//     savepoint manager fires its "saved" hook; empty until then.
//   - sync_points_state / save_state — currently absent because
//     the cut-2 MOM manager does not subscribe to SyncCoordinator /
//     SavepointCoordinator state. A cut-4 hook composition adds
//     these without proto changes (new field tags reserved).
type QueryFederationAttributesResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	FederationName  string                 `protobuf:"bytes,1,opt,name=federation_name,json=federationName,proto3" json:"federation_name,omitempty"`
	FederateHandles []uint64               `protobuf:"varint,2,rep,packed,name=federate_handles,json=federateHandles,proto3" json:"federate_handles,omitempty"`
	FomModuleNames  []string               `protobuf:"bytes,3,rep,name=fom_module_names,json=fomModuleNames,proto3" json:"fom_module_names,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *QueryFederationAttributesResponse) Reset() {
	*x = QueryFederationAttributesResponse{}
	mi := &file_rti_v1_mom_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryFederationAttributesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryFederationAttributesResponse) ProtoMessage() {}

func (x *QueryFederationAttributesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_mom_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryFederationAttributesResponse.ProtoReflect.Descriptor instead.
func (*QueryFederationAttributesResponse) Descriptor() ([]byte, []int) {
	return file_rti_v1_mom_proto_rawDescGZIP(), []int{1}
}

func (x *QueryFederationAttributesResponse) GetFederationName() string {
	if x != nil {
		return x.FederationName
	}
	return ""
}

func (x *QueryFederationAttributesResponse) GetFederateHandles() []uint64 {
	if x != nil {
		return x.FederateHandles
	}
	return nil
}

func (x *QueryFederationAttributesResponse) GetFomModuleNames() []string {
	if x != nil {
		return x.FomModuleNames
	}
	return nil
}

type QueryFederateAttributesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WireVersion    WireVersion            `protobuf:"varint,1,opt,name=wire_version,json=wireVersion,proto3,enum=rti.v1.WireVersion" json:"wire_version,omitempty"`
	FederationName string                 `protobuf:"bytes,2,opt,name=federation_name,json=federationName,proto3" json:"federation_name,omitempty"`
	FederateHandle uint64                 `protobuf:"varint,3,opt,name=federate_handle,json=federateHandle,proto3" json:"federate_handle,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *QueryFederateAttributesRequest) Reset() {
	*x = QueryFederateAttributesRequest{}
	mi := &file_rti_v1_mom_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryFederateAttributesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryFederateAttributesRequest) ProtoMessage() {}

func (x *QueryFederateAttributesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_mom_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryFederateAttributesRequest.ProtoReflect.Descriptor instead.
func (*QueryFederateAttributesRequest) Descriptor() ([]byte, []int) {
	return file_rti_v1_mom_proto_rawDescGZIP(), []int{2}
}

func (x *QueryFederateAttributesRequest) GetWireVersion() WireVersion {
	if x != nil {
		return x.WireVersion
	}
	return WireVersion_WIRE_VERSION_UNSPECIFIED
}

func (x *QueryFederateAttributesRequest) GetFederationName() string {
	if x != nil {
		return x.FederationName
	}
	return ""
}

func (x *QueryFederateAttributesRequest) GetFederateHandle() uint64 {
	if x != nil {
		return x.FederateHandle
	}
	return 0
}

// FederateAttributes is the wire-format snapshot of one HLAfederate
// MOM object's attributes per IEEE 1516.1-2010 §10.3.
//
// Cut-3 fields populated:
//   - federate_handle, federate_name, federate_type
//   - time_regulating, time_constrained
//   - logical_time, lookahead — populated from time.Manager state
//     transitions via the OnTimeStateChanged → mom.TimeStateChanged
//     hook wired in cmd/rtid main.go (M17.26, 2026-05-24).
//   - per-federate counters: interactions_sent / interactions_received /
//     updates_sent / reflections_received
type QueryFederateAttributesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True iff the runtime is currently tracking this (federation,
	// federate_handle). False indicates the federate has resigned or
	// never joined; remaining fields are zero-valued.
	Found          bool   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	FederateHandle uint64 `protobuf:"varint,2,opt,name=federate_handle,json=federateHandle,proto3" json:"federate_handle,omitempty"`
	FederateName   string `protobuf:"bytes,3,opt,name=federate_name,json=federateName,proto3" json:"federate_name,omitempty"`
	FederateType   string `protobuf:"bytes,4,opt,name=federate_type,json=federateType,proto3" json:"federate_type,omitempty"`
	// Time state.
	TimeRegulating  bool         `protobuf:"varint,10,opt,name=time_regulating,json=timeRegulating,proto3" json:"time_regulating,omitempty"`
	TimeConstrained bool         `protobuf:"varint,11,opt,name=time_constrained,json=timeConstrained,proto3" json:"time_constrained,omitempty"`
	LogicalTime     *LogicalTime `protobuf:"bytes,12,opt,name=logical_time,json=logicalTime,proto3" json:"logical_time,omitempty"`
	Lookahead       *LogicalTime `protobuf:"bytes,13,opt,name=lookahead,proto3" json:"lookahead,omitempty"`
	// Per-federate counters (FR-MOM-1).
	InteractionsSent     uint32 `protobuf:"varint,20,opt,name=interactions_sent,json=interactionsSent,proto3" json:"interactions_sent,omitempty"`
	InteractionsReceived uint32 `protobuf:"varint,21,opt,name=interactions_received,json=interactionsReceived,proto3" json:"interactions_received,omitempty"`
	UpdatesSent          uint32 `protobuf:"varint,22,opt,name=updates_sent,json=updatesSent,proto3" json:"updates_sent,omitempty"`
	ReflectionsReceived  uint32 `protobuf:"varint,23,opt,name=reflections_received,json=reflectionsReceived,proto3" json:"reflections_received,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *QueryFederateAttributesResponse) Reset() {
	*x = QueryFederateAttributesResponse{}
	mi := &file_rti_v1_mom_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryFederateAttributesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryFederateAttributesResponse) ProtoMessage() {}

func (x *QueryFederateAttributesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_mom_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryFederateAttributesResponse.ProtoReflect.Descriptor instead.
func (*QueryFederateAttributesResponse) Descriptor() ([]byte, []int) {
	return file_rti_v1_mom_proto_rawDescGZIP(), []int{3}
}

func (x *QueryFederateAttributesResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *QueryFederateAttributesResponse) GetFederateHandle() uint64 {
	if x != nil {
		return x.FederateHandle
	}
	return 0
}

func (x *QueryFederateAttributesResponse) GetFederateName() string {
	if x != nil {
		return x.FederateName
	}
	return ""
}

func (x *QueryFederateAttributesResponse) GetFederateType() string {
	if x != nil {
		return x.FederateType
	}
	return ""
}

func (x *QueryFederateAttributesResponse) GetTimeRegulating() bool {
	if x != nil {
		return x.TimeRegulating
	}
	return false
}

func (x *QueryFederateAttributesResponse) GetTimeConstrained() bool {
	if x != nil {
		return x.TimeConstrained
	}
	return false
}

func (x *QueryFederateAttributesResponse) GetLogicalTime() *LogicalTime {
	if x != nil {
		return x.LogicalTime
	}
	return nil
}

func (x *QueryFederateAttributesResponse) GetLookahead() *LogicalTime {
	if x != nil {
		return x.Lookahead
	}
	return nil
}

func (x *QueryFederateAttributesResponse) GetInteractionsSent() uint32 {
	if x != nil {
		return x.InteractionsSent
	}
	return 0
}

func (x *QueryFederateAttributesResponse) GetInteractionsReceived() uint32 {
	if x != nil {
		return x.InteractionsReceived
	}
	return 0
}

func (x *QueryFederateAttributesResponse) GetUpdatesSent() uint32 {
	if x != nil {
		return x.UpdatesSent
	}
	return 0
}

func (x *QueryFederateAttributesResponse) GetReflectionsReceived() uint32 {
	if x != nil {
		return x.ReflectionsReceived
	}
	return 0
}

type EnumerateMomInstancesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WireVersion    WireVersion            `protobuf:"varint,1,opt,name=wire_version,json=wireVersion,proto3,enum=rti.v1.WireVersion" json:"wire_version,omitempty"`
	FederationName string                 `protobuf:"bytes,2,opt,name=federation_name,json=federationName,proto3" json:"federation_name,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EnumerateMomInstancesRequest) Reset() {
	*x = EnumerateMomInstancesRequest{}
	mi := &file_rti_v1_mom_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumerateMomInstancesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumerateMomInstancesRequest) ProtoMessage() {}

func (x *EnumerateMomInstancesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_mom_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumerateMomInstancesRequest.ProtoReflect.Descriptor instead.
func (*EnumerateMomInstancesRequest) Descriptor() ([]byte, []int) {
	return file_rti_v1_mom_proto_rawDescGZIP(), []int{4}
}

func (x *EnumerateMomInstancesRequest) GetWireVersion() WireVersion {
	if x != nil {
		return x.WireVersion
	}
	return WireVersion_WIRE_VERSION_UNSPECIFIED
}

func (x *EnumerateMomInstancesRequest) GetFederationName() string {
	if x != nil {
		return x.FederationName
	}
	return ""
}

// MomInstance describes one MOM-tracked object instance: either the
// HLAfederation singleton or one HLAfederate per joined federate.
type MomInstance struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Class name per IEEE 1516.1-2010 §10:
	//
	//	"HLAobjectRoot.HLAmanager.HLAfederation"  — singleton per fed
	//	"HLAobjectRoot.HLAmanager.HLAfederate"    — one per joined federate
	ClassName string `protobuf:"bytes,1,opt,name=class_name,json=className,proto3" json:"class_name,omitempty"`
	// For HLAfederate, the federate handle this instance refers to.
	// For HLAfederation, zero (the federation singleton has no
	// federate-handle).
	FederateHandle uint64 `protobuf:"varint,2,opt,name=federate_handle,json=federateHandle,proto3" json:"federate_handle,omitempty"`
	// Human-readable instance name. For HLAfederate this is the
	// federate name (passed at join time); for HLAfederation it is
	// the federation name.
	InstanceName  string `protobuf:"bytes,3,opt,name=instance_name,json=instanceName,proto3" json:"instance_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MomInstance) Reset() {
	*x = MomInstance{}
	mi := &file_rti_v1_mom_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MomInstance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MomInstance) ProtoMessage() {}

func (x *MomInstance) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_mom_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MomInstance.ProtoReflect.Descriptor instead.
func (*MomInstance) Descriptor() ([]byte, []int) {
	return file_rti_v1_mom_proto_rawDescGZIP(), []int{5}
}

func (x *MomInstance) GetClassName() string {
	if x != nil {
		return x.ClassName
	}
	return ""
}

func (x *MomInstance) GetFederateHandle() uint64 {
	if x != nil {
		return x.FederateHandle
	}
	return 0
}

func (x *MomInstance) GetInstanceName() string {
	if x != nil {
		return x.InstanceName
	}
	return ""
}

type EnumerateMomInstancesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instances     []*MomInstance         `protobuf:"bytes,1,rep,name=instances,proto3" json:"instances,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnumerateMomInstancesResponse) Reset() {
	*x = EnumerateMomInstancesResponse{}
	mi := &file_rti_v1_mom_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumerateMomInstancesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumerateMomInstancesResponse) ProtoMessage() {}

func (x *EnumerateMomInstancesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_mom_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumerateMomInstancesResponse.ProtoReflect.Descriptor instead.
func (*EnumerateMomInstancesResponse) Descriptor() ([]byte, []int) {
	return file_rti_v1_mom_proto_rawDescGZIP(), []int{6}
}

func (x *EnumerateMomInstancesResponse) GetInstances() []*MomInstance {
	if x != nil {
		return x.Instances
	}
	return nil
}

// MOMFederateRecord is one HLAfederate live attribute snapshot used
// inside MOMManagerState. M13 thread C (docs/srs.md §10.4).
type MOMFederateRecord struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Handle               uint64                 `protobuf:"varint,1,opt,name=handle,proto3" json:"handle,omitempty"`
	Name                 string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	FederateType         string                 `protobuf:"bytes,3,opt,name=federate_type,json=federateType,proto3" json:"federate_type,omitempty"`
	TimeRegulating       bool                   `protobuf:"varint,4,opt,name=time_regulating,json=timeRegulating,proto3" json:"time_regulating,omitempty"`
	TimeConstrained      bool                   `protobuf:"varint,5,opt,name=time_constrained,json=timeConstrained,proto3" json:"time_constrained,omitempty"`
	Lookahead            float64                `protobuf:"fixed64,6,opt,name=lookahead,proto3" json:"lookahead,omitempty"`
	LogicalTime          float64                `protobuf:"fixed64,7,opt,name=logical_time,json=logicalTime,proto3" json:"logical_time,omitempty"`
	InteractionsSent     uint32                 `protobuf:"varint,10,opt,name=interactions_sent,json=interactionsSent,proto3" json:"interactions_sent,omitempty"`
	InteractionsReceived uint32                 `protobuf:"varint,11,opt,name=interactions_received,json=interactionsReceived,proto3" json:"interactions_received,omitempty"`
	UpdatesSent          uint32                 `protobuf:"varint,12,opt,name=updates_sent,json=updatesSent,proto3" json:"updates_sent,omitempty"`
	ReflectionsReceived  uint32                 `protobuf:"varint,13,opt,name=reflections_received,json=reflectionsReceived,proto3" json:"reflections_received,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *MOMFederateRecord) Reset() {
	*x = MOMFederateRecord{}
	mi := &file_rti_v1_mom_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MOMFederateRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MOMFederateRecord) ProtoMessage() {}

func (x *MOMFederateRecord) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_mom_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MOMFederateRecord.ProtoReflect.Descriptor instead.
func (*MOMFederateRecord) Descriptor() ([]byte, []int) {
	return file_rti_v1_mom_proto_rawDescGZIP(), []int{7}
}

func (x *MOMFederateRecord) GetHandle() uint64 {
	if x != nil {
		return x.Handle
	}
	return 0
}

func (x *MOMFederateRecord) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MOMFederateRecord) GetFederateType() string {
	if x != nil {
		return x.FederateType
	}
	return ""
}

func (x *MOMFederateRecord) GetTimeRegulating() bool {
	if x != nil {
		return x.TimeRegulating
	}
	return false
}

func (x *MOMFederateRecord) GetTimeConstrained() bool {
	if x != nil {
		return x.TimeConstrained
	}
	return false
}

func (x *MOMFederateRecord) GetLookahead() float64 {
	if x != nil {
		return x.Lookahead
	}
	return 0
}

func (x *MOMFederateRecord) GetLogicalTime() float64 {
	if x != nil {
		return x.LogicalTime
	}
	return 0
}

func (x *MOMFederateRecord) GetInteractionsSent() uint32 {
	if x != nil {
		return x.InteractionsSent
	}
	return 0
}

func (x *MOMFederateRecord) GetInteractionsReceived() uint32 {
	if x != nil {
		return x.InteractionsReceived
	}
	return 0
}

func (x *MOMFederateRecord) GetUpdatesSent() uint32 {
	if x != nil {
		return x.UpdatesSent
	}
	return 0
}

func (x *MOMFederateRecord) GetReflectionsReceived() uint32 {
	if x != nil {
		return x.ReflectionsReceived
	}
	return 0
}

// MOMFederationRecord is the HLAfederation singleton's live attribute
// snapshot — name + sorted handles + FOM module names.
type MOMFederationRecord struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	FederateHandles []uint64               `protobuf:"varint,2,rep,packed,name=federate_handles,json=federateHandles,proto3" json:"federate_handles,omitempty"` // sorted ascending
	FomModuleNames  []string               `protobuf:"bytes,3,rep,name=fom_module_names,json=fomModuleNames,proto3" json:"fom_module_names,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MOMFederationRecord) Reset() {
	*x = MOMFederationRecord{}
	mi := &file_rti_v1_mom_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MOMFederationRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MOMFederationRecord) ProtoMessage() {}

func (x *MOMFederationRecord) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_mom_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MOMFederationRecord.ProtoReflect.Descriptor instead.
func (*MOMFederationRecord) Descriptor() ([]byte, []int) {
	return file_rti_v1_mom_proto_rawDescGZIP(), []int{8}
}

func (x *MOMFederationRecord) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MOMFederationRecord) GetFederateHandles() []uint64 {
	if x != nil {
		return x.FederateHandles
	}
	return nil
}

func (x *MOMFederationRecord) GetFomModuleNames() []string {
	if x != nil {
		return x.FomModuleNames
	}
	return nil
}

// MOMManagerState is the per-federation snapshot persisted into the
// save manifest under key "mom". M13 thread C (docs/srs.md §10.4).
// On Marshal, federates are sorted by handle ascending.
type MOMManagerState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Federation    *MOMFederationRecord   `protobuf:"bytes,1,opt,name=federation,proto3" json:"federation,omitempty"`
	Federates     []*MOMFederateRecord   `protobuf:"bytes,2,rep,name=federates,proto3" json:"federates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MOMManagerState) Reset() {
	*x = MOMManagerState{}
	mi := &file_rti_v1_mom_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MOMManagerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MOMManagerState) ProtoMessage() {}

func (x *MOMManagerState) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_mom_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MOMManagerState.ProtoReflect.Descriptor instead.
func (*MOMManagerState) Descriptor() ([]byte, []int) {
	return file_rti_v1_mom_proto_rawDescGZIP(), []int{9}
}

func (x *MOMManagerState) GetFederation() *MOMFederationRecord {
	if x != nil {
		return x.Federation
	}
	return nil
}

func (x *MOMManagerState) GetFederates() []*MOMFederateRecord {
	if x != nil {
		return x.Federates
	}
	return nil
}

var File_rti_v1_mom_proto protoreflect.FileDescriptor

const file_rti_v1_mom_proto_rawDesc = "" +
	"\n" +
	"\x10rti/v1/mom.proto\x12\x06rti.v1\x1a\x13rti/v1/common.proto\"\x83\x01\n" +
	" QueryFederationAttributesRequest\x126\n" +
	"\fwire_version\x18\x01 \x01(\x0e2\x13.rti.v1.WireVersionR\vwireVersion\x12'\n" +
	"\x0ffederation_name\x18\x02 \x01(\tR\x0efederationName\"\xa1\x01\n" +
	"!QueryFederationAttributesResponse\x12'\n" +
	"\x0ffederation_name\x18\x01 \x01(\tR\x0efederationName\x12)\n" +
	"\x10federate_handles\x18\x02 \x03(\x04R\x0ffederateHandles\x12(\n" +
	"\x10fom_module_names\x18\x03 \x03(\tR\x0efomModuleNames\"\xaa\x01\n" +
	"\x1eQueryFederateAttributesRequest\x126\n" +
	"\fwire_version\x18\x01 \x01(\x0e2\x13.rti.v1.WireVersionR\vwireVersion\x12'\n" +
	"\x0ffederation_name\x18\x02 \x01(\tR\x0efederationName\x12'\n" +
	"\x0ffederate_handle\x18\x03 \x01(\x04R\x0efederateHandle\"\xa1\x04\n" +
	"\x1fQueryFederateAttributesResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12'\n" +
	"\x0ffederate_handle\x18\x02 \x01(\x04R\x0efederateHandle\x12#\n" +
	"\rfederate_name\x18\x03 \x01(\tR\ffederateName\x12#\n" +
	"\rfederate_type\x18\x04 \x01(\tR\ffederateType\x12'\n" +
	"\x0ftime_regulating\x18\n" +
	" \x01(\bR\x0etimeRegulating\x12)\n" +
	"\x10time_constrained\x18\v \x01(\bR\x0ftimeConstrained\x126\n" +
	"\flogical_time\x18\f \x01(\v2\x13.rti.v1.LogicalTimeR\vlogicalTime\x121\n" +
	"\tlookahead\x18\r \x01(\v2\x13.rti.v1.LogicalTimeR\tlookahead\x12+\n" +
	"\x11interactions_sent\x18\x14 \x01(\rR\x10interactionsSent\x123\n" +
	"\x15interactions_received\x18\x15 \x01(\rR\x14interactionsReceived\x12!\n" +
	"\fupdates_sent\x18\x16 \x01(\rR\vupdatesSent\x121\n" +
	"\x14reflections_received\x18\x17 \x01(\rR\x13reflectionsReceived\"\x7f\n" +
	"\x1cEnumerateMomInstancesRequest\x126\n" +
	"\fwire_version\x18\x01 \x01(\x0e2\x13.rti.v1.WireVersionR\vwireVersion\x12'\n" +
	"\x0ffederation_name\x18\x02 \x01(\tR\x0efederationName\"z\n" +
	"\vMomInstance\x12\x1d\n" +
	"\n" +
	"class_name\x18\x01 \x01(\tR\tclassName\x12'\n" +
	"\x0ffederate_handle\x18\x02 \x01(\x04R\x0efederateHandle\x12#\n" +
	"\rinstance_name\x18\x03 \x01(\tR\finstanceName\"R\n" +
	"\x1dEnumerateMomInstancesResponse\x121\n" +
	"\tinstances\x18\x01 \x03(\v2\x13.rti.v1.MomInstanceR\tinstances\"\xb1\x03\n" +
	"\x11MOMFederateRecord\x12\x16\n" +
	"\x06handle\x18\x01 \x01(\x04R\x06handle\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12#\n" +
	"\rfederate_type\x18\x03 \x01(\tR\ffederateType\x12'\n" +
	"\x0ftime_regulating\x18\x04 \x01(\bR\x0etimeRegulating\x12)\n" +
	"\x10time_constrained\x18\x05 \x01(\bR\x0ftimeConstrained\x12\x1c\n" +
	"\tlookahead\x18\x06 \x01(\x01R\tlookahead\x12!\n" +
	"\flogical_time\x18\a \x01(\x01R\vlogicalTime\x12+\n" +
	"\x11interactions_sent\x18\n" +
	" \x01(\rR\x10interactionsSent\x123\n" +
	"\x15interactions_received\x18\v \x01(\rR\x14interactionsReceived\x12!\n" +
	"\fupdates_sent\x18\f \x01(\rR\vupdatesSent\x121\n" +
	"\x14reflections_received\x18\r \x01(\rR\x13reflectionsReceived\"~\n" +
	"\x13MOMFederationRecord\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12)\n" +
	"\x10federate_handles\x18\x02 \x03(\x04R\x0ffederateHandles\x12(\n" +
	"\x10fom_module_names\x18\x03 \x03(\tR\x0efomModuleNames\"\x87\x01\n" +
	"\x0fMOMManagerState\x12;\n" +
	"\n" +
	"federation\x18\x01 \x01(\v2\x1b.rti.v1.MOMFederationRecordR\n" +
	"federation\x127\n" +
	"\tfederates\x18\x02 \x03(\v2\x19.rti.v1.MOMFederateRecordR\tfederates2\xd0\x02\n" +
	"\n" +
	"MomService\x12p\n" +
	"\x19QueryFederationAttributes\x12(.rti.v1.QueryFederationAttributesRequest\x1a).rti.v1.QueryFederationAttributesResponse\x12j\n" +
	"\x17QueryFederateAttributes\x12&.rti.v1.QueryFederateAttributesRequest\x1a'.rti.v1.QueryFederateAttributesResponse\x12d\n" +
	"\x15EnumerateMomInstances\x12$.rti.v1.EnumerateMomInstancesRequest\x1a%.rti.v1.EnumerateMomInstancesResponseB<Z:github.com/cbchoi/gorti/rti/internal/genproto/rti/v1;rtiv1b\x06proto3"

var (
	file_rti_v1_mom_proto_rawDescOnce sync.Once
	file_rti_v1_mom_proto_rawDescData []byte
)

func file_rti_v1_mom_proto_rawDescGZIP() []byte {
	file_rti_v1_mom_proto_rawDescOnce.Do(func() {
		file_rti_v1_mom_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rti_v1_mom_proto_rawDesc), len(file_rti_v1_mom_proto_rawDesc)))
	})
	return file_rti_v1_mom_proto_rawDescData
}

var file_rti_v1_mom_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_rti_v1_mom_proto_goTypes = []any{
	(*QueryFederationAttributesRequest)(nil),  // 0: rti.v1.QueryFederationAttributesRequest
	(*QueryFederationAttributesResponse)(nil), // 1: rti.v1.QueryFederationAttributesResponse
	(*QueryFederateAttributesRequest)(nil),    // 2: rti.v1.QueryFederateAttributesRequest
	(*QueryFederateAttributesResponse)(nil),   // 3: rti.v1.QueryFederateAttributesResponse
	(*EnumerateMomInstancesRequest)(nil),      // 4: rti.v1.EnumerateMomInstancesRequest
	(*MomInstance)(nil),                       // 5: rti.v1.MomInstance
	(*EnumerateMomInstancesResponse)(nil),     // 6: rti.v1.EnumerateMomInstancesResponse
	(*MOMFederateRecord)(nil),                 // 7: rti.v1.MOMFederateRecord
	(*MOMFederationRecord)(nil),               // 8: rti.v1.MOMFederationRecord
	(*MOMManagerState)(nil),                   // 9: rti.v1.MOMManagerState
	(WireVersion)(0),                          // 10: rti.v1.WireVersion
	(*LogicalTime)(nil),                       // 11: rti.v1.LogicalTime
}
var file_rti_v1_mom_proto_depIdxs = []int32{
	10, // 0: rti.v1.QueryFederationAttributesRequest.wire_version:type_name -> rti.v1.WireVersion
	10, // 1: rti.v1.QueryFederateAttributesRequest.wire_version:type_name -> rti.v1.WireVersion
	11, // 2: rti.v1.QueryFederateAttributesResponse.logical_time:type_name -> rti.v1.LogicalTime
	11, // 3: rti.v1.QueryFederateAttributesResponse.lookahead:type_name -> rti.v1.LogicalTime
	10, // 4: rti.v1.EnumerateMomInstancesRequest.wire_version:type_name -> rti.v1.WireVersion
	5,  // 5: rti.v1.EnumerateMomInstancesResponse.instances:type_name -> rti.v1.MomInstance
	8,  // 6: rti.v1.MOMManagerState.federation:type_name -> rti.v1.MOMFederationRecord
	7,  // 7: rti.v1.MOMManagerState.federates:type_name -> rti.v1.MOMFederateRecord
	0,  // 8: rti.v1.MomService.QueryFederationAttributes:input_type -> rti.v1.QueryFederationAttributesRequest
	2,  // 9: rti.v1.MomService.QueryFederateAttributes:input_type -> rti.v1.QueryFederateAttributesRequest
	4,  // 10: rti.v1.MomService.EnumerateMomInstances:input_type -> rti.v1.EnumerateMomInstancesRequest
	1,  // 11: rti.v1.MomService.QueryFederationAttributes:output_type -> rti.v1.QueryFederationAttributesResponse
	3,  // 12: rti.v1.MomService.QueryFederateAttributes:output_type -> rti.v1.QueryFederateAttributesResponse
	6,  // 13: rti.v1.MomService.EnumerateMomInstances:output_type -> rti.v1.EnumerateMomInstancesResponse
	11, // [11:14] is the sub-list for method output_type
	8,  // [8:11] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_rti_v1_mom_proto_init() }
func file_rti_v1_mom_proto_init() {
	if File_rti_v1_mom_proto != nil {
		return
	}
	file_rti_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rti_v1_mom_proto_rawDesc), len(file_rti_v1_mom_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rti_v1_mom_proto_goTypes,
		DependencyIndexes: file_rti_v1_mom_proto_depIdxs,
		MessageInfos:      file_rti_v1_mom_proto_msgTypes,
	}.Build()
	File_rti_v1_mom_proto = out.File
	file_rti_v1_mom_proto_goTypes = nil
	file_rti_v1_mom_proto_depIdxs = nil
}
