// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: rti/v1/ownership.proto

package rtiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UnconditionalDivestRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	WireVersion      WireVersion            `protobuf:"varint,1,opt,name=wire_version,json=wireVersion,proto3,enum=rti.v1.WireVersion" json:"wire_version,omitempty"`
	FederationName   string                 `protobuf:"bytes,2,opt,name=federation_name,json=federationName,proto3" json:"federation_name,omitempty"`
	FederateHandle   uint64                 `protobuf:"varint,3,opt,name=federate_handle,json=federateHandle,proto3" json:"federate_handle,omitempty"` // current owner
	ObjectHandle     uint64                 `protobuf:"varint,4,opt,name=object_handle,json=objectHandle,proto3" json:"object_handle,omitempty"`
	AttributeHandles []uint64               `protobuf:"varint,5,rep,packed,name=attribute_handles,json=attributeHandles,proto3" json:"attribute_handles,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UnconditionalDivestRequest) Reset() {
	*x = UnconditionalDivestRequest{}
	mi := &file_rti_v1_ownership_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnconditionalDivestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnconditionalDivestRequest) ProtoMessage() {}

func (x *UnconditionalDivestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_ownership_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnconditionalDivestRequest.ProtoReflect.Descriptor instead.
func (*UnconditionalDivestRequest) Descriptor() ([]byte, []int) {
	return file_rti_v1_ownership_proto_rawDescGZIP(), []int{0}
}

func (x *UnconditionalDivestRequest) GetWireVersion() WireVersion {
	if x != nil {
		return x.WireVersion
	}
	return WireVersion_WIRE_VERSION_UNSPECIFIED
}

func (x *UnconditionalDivestRequest) GetFederationName() string {
	if x != nil {
		return x.FederationName
	}
	return ""
}

func (x *UnconditionalDivestRequest) GetFederateHandle() uint64 {
	if x != nil {
		return x.FederateHandle
	}
	return 0
}

func (x *UnconditionalDivestRequest) GetObjectHandle() uint64 {
	if x != nil {
		return x.ObjectHandle
	}
	return 0
}

func (x *UnconditionalDivestRequest) GetAttributeHandles() []uint64 {
	if x != nil {
		return x.AttributeHandles
	}
	return nil
}

type NegotiatedDivestRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	WireVersion      WireVersion            `protobuf:"varint,1,opt,name=wire_version,json=wireVersion,proto3,enum=rti.v1.WireVersion" json:"wire_version,omitempty"`
	FederationName   string                 `protobuf:"bytes,2,opt,name=federation_name,json=federationName,proto3" json:"federation_name,omitempty"`
	FederateHandle   uint64                 `protobuf:"varint,3,opt,name=federate_handle,json=federateHandle,proto3" json:"federate_handle,omitempty"`
	ObjectHandle     uint64                 `protobuf:"varint,4,opt,name=object_handle,json=objectHandle,proto3" json:"object_handle,omitempty"`
	AttributeHandles []uint64               `protobuf:"varint,5,rep,packed,name=attribute_handles,json=attributeHandles,proto3" json:"attribute_handles,omitempty"`
	Tag              []byte                 `protobuf:"bytes,6,opt,name=tag,proto3" json:"tag,omitempty"`
	// IEEE 1516.1-2010 §7.3/§7.6 REAL two-phase protocol (M37 Agent EA,
	// additive tag 7). When true: an acquirer's arrival emits
	// requestDivestitureConfirmation to the divester and the transfer
	// completes ONLY on a subsequent ConfirmDivestiture RPC. When
	// absent/false: the pre-M37 one-phase flow (transfer completes as
	// soon as an acquirer engages) is preserved for old clients.
	TwoPhase      bool `protobuf:"varint,7,opt,name=two_phase,json=twoPhase,proto3" json:"two_phase,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NegotiatedDivestRequest) Reset() {
	*x = NegotiatedDivestRequest{}
	mi := &file_rti_v1_ownership_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NegotiatedDivestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NegotiatedDivestRequest) ProtoMessage() {}

func (x *NegotiatedDivestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_ownership_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NegotiatedDivestRequest.ProtoReflect.Descriptor instead.
func (*NegotiatedDivestRequest) Descriptor() ([]byte, []int) {
	return file_rti_v1_ownership_proto_rawDescGZIP(), []int{1}
}

func (x *NegotiatedDivestRequest) GetWireVersion() WireVersion {
	if x != nil {
		return x.WireVersion
	}
	return WireVersion_WIRE_VERSION_UNSPECIFIED
}

func (x *NegotiatedDivestRequest) GetFederationName() string {
	if x != nil {
		return x.FederationName
	}
	return ""
}

func (x *NegotiatedDivestRequest) GetFederateHandle() uint64 {
	if x != nil {
		return x.FederateHandle
	}
	return 0
}

func (x *NegotiatedDivestRequest) GetObjectHandle() uint64 {
	if x != nil {
		return x.ObjectHandle
	}
	return 0
}

func (x *NegotiatedDivestRequest) GetAttributeHandles() []uint64 {
	if x != nil {
		return x.AttributeHandles
	}
	return nil
}

func (x *NegotiatedDivestRequest) GetTag() []byte {
	if x != nil {
		return x.Tag
	}
	return nil
}

func (x *NegotiatedDivestRequest) GetTwoPhase() bool {
	if x != nil {
		return x.TwoPhase
	}
	return false
}

// ConfirmDivestiture — IEEE 1516.1-2010 §7.6 (M37 Agent EA). The
// divesting federate (federate_handle) confirms; the RTI transfers the
// listed attributes to the strategy-selected queued acquirer.
type ConfirmDivestitureRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	WireVersion      WireVersion            `protobuf:"varint,1,opt,name=wire_version,json=wireVersion,proto3,enum=rti.v1.WireVersion" json:"wire_version,omitempty"`
	FederationName   string                 `protobuf:"bytes,2,opt,name=federation_name,json=federationName,proto3" json:"federation_name,omitempty"`
	FederateHandle   uint64                 `protobuf:"varint,3,opt,name=federate_handle,json=federateHandle,proto3" json:"federate_handle,omitempty"` // divesting owner
	ObjectHandle     uint64                 `protobuf:"varint,4,opt,name=object_handle,json=objectHandle,proto3" json:"object_handle,omitempty"`
	AttributeHandles []uint64               `protobuf:"varint,5,rep,packed,name=attribute_handles,json=attributeHandles,proto3" json:"attribute_handles,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ConfirmDivestitureRequest) Reset() {
	*x = ConfirmDivestitureRequest{}
	mi := &file_rti_v1_ownership_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmDivestitureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmDivestitureRequest) ProtoMessage() {}

func (x *ConfirmDivestitureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_ownership_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmDivestitureRequest.ProtoReflect.Descriptor instead.
func (*ConfirmDivestitureRequest) Descriptor() ([]byte, []int) {
	return file_rti_v1_ownership_proto_rawDescGZIP(), []int{2}
}

func (x *ConfirmDivestitureRequest) GetWireVersion() WireVersion {
	if x != nil {
		return x.WireVersion
	}
	return WireVersion_WIRE_VERSION_UNSPECIFIED
}

func (x *ConfirmDivestitureRequest) GetFederationName() string {
	if x != nil {
		return x.FederationName
	}
	return ""
}

func (x *ConfirmDivestitureRequest) GetFederateHandle() uint64 {
	if x != nil {
		return x.FederateHandle
	}
	return 0
}

func (x *ConfirmDivestitureRequest) GetObjectHandle() uint64 {
	if x != nil {
		return x.ObjectHandle
	}
	return 0
}

func (x *ConfirmDivestitureRequest) GetAttributeHandles() []uint64 {
	if x != nil {
		return x.AttributeHandles
	}
	return nil
}

type AcquireRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	WireVersion      WireVersion            `protobuf:"varint,1,opt,name=wire_version,json=wireVersion,proto3,enum=rti.v1.WireVersion" json:"wire_version,omitempty"`
	FederationName   string                 `protobuf:"bytes,2,opt,name=federation_name,json=federationName,proto3" json:"federation_name,omitempty"`
	FederateHandle   uint64                 `protobuf:"varint,3,opt,name=federate_handle,json=federateHandle,proto3" json:"federate_handle,omitempty"` // acquirer
	ObjectHandle     uint64                 `protobuf:"varint,4,opt,name=object_handle,json=objectHandle,proto3" json:"object_handle,omitempty"`
	AttributeHandles []uint64               `protobuf:"varint,5,rep,packed,name=attribute_handles,json=attributeHandles,proto3" json:"attribute_handles,omitempty"`
	Tag              []byte                 `protobuf:"bytes,6,opt,name=tag,proto3" json:"tag,omitempty"`
	// IEEE 1516.1-2010 §7.9 attributeOwnershipAcquisitionIfAvailable —
	// when true, the RTI atomically grants ONLY the attributes that are
	// currently available (unowned, or mid-divest with this acquirer
	// selected); the rest produce an AttributeOwnershipUnavailable
	// callback (§7.10) and NO pending acquire is queued. Absent/false
	// (old clients) keeps plain §7.8 queueing semantics. M37 Agent EA
	// (additive, tag 7).
	IfAvailable   bool `protobuf:"varint,7,opt,name=if_available,json=ifAvailable,proto3" json:"if_available,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcquireRequest) Reset() {
	*x = AcquireRequest{}
	mi := &file_rti_v1_ownership_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcquireRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquireRequest) ProtoMessage() {}

func (x *AcquireRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_ownership_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcquireRequest.ProtoReflect.Descriptor instead.
func (*AcquireRequest) Descriptor() ([]byte, []int) {
	return file_rti_v1_ownership_proto_rawDescGZIP(), []int{3}
}

func (x *AcquireRequest) GetWireVersion() WireVersion {
	if x != nil {
		return x.WireVersion
	}
	return WireVersion_WIRE_VERSION_UNSPECIFIED
}

func (x *AcquireRequest) GetFederationName() string {
	if x != nil {
		return x.FederationName
	}
	return ""
}

func (x *AcquireRequest) GetFederateHandle() uint64 {
	if x != nil {
		return x.FederateHandle
	}
	return 0
}

func (x *AcquireRequest) GetObjectHandle() uint64 {
	if x != nil {
		return x.ObjectHandle
	}
	return 0
}

func (x *AcquireRequest) GetAttributeHandles() []uint64 {
	if x != nil {
		return x.AttributeHandles
	}
	return nil
}

func (x *AcquireRequest) GetTag() []byte {
	if x != nil {
		return x.Tag
	}
	return nil
}

func (x *AcquireRequest) GetIfAvailable() bool {
	if x != nil {
		return x.IfAvailable
	}
	return false
}

type CancelDivestRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	WireVersion      WireVersion            `protobuf:"varint,1,opt,name=wire_version,json=wireVersion,proto3,enum=rti.v1.WireVersion" json:"wire_version,omitempty"`
	FederationName   string                 `protobuf:"bytes,2,opt,name=federation_name,json=federationName,proto3" json:"federation_name,omitempty"`
	FederateHandle   uint64                 `protobuf:"varint,3,opt,name=federate_handle,json=federateHandle,proto3" json:"federate_handle,omitempty"` // owner withdrawing
	ObjectHandle     uint64                 `protobuf:"varint,4,opt,name=object_handle,json=objectHandle,proto3" json:"object_handle,omitempty"`
	AttributeHandles []uint64               `protobuf:"varint,5,rep,packed,name=attribute_handles,json=attributeHandles,proto3" json:"attribute_handles,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CancelDivestRequest) Reset() {
	*x = CancelDivestRequest{}
	mi := &file_rti_v1_ownership_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelDivestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelDivestRequest) ProtoMessage() {}

func (x *CancelDivestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_ownership_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelDivestRequest.ProtoReflect.Descriptor instead.
func (*CancelDivestRequest) Descriptor() ([]byte, []int) {
	return file_rti_v1_ownership_proto_rawDescGZIP(), []int{4}
}

func (x *CancelDivestRequest) GetWireVersion() WireVersion {
	if x != nil {
		return x.WireVersion
	}
	return WireVersion_WIRE_VERSION_UNSPECIFIED
}

func (x *CancelDivestRequest) GetFederationName() string {
	if x != nil {
		return x.FederationName
	}
	return ""
}

func (x *CancelDivestRequest) GetFederateHandle() uint64 {
	if x != nil {
		return x.FederateHandle
	}
	return 0
}

func (x *CancelDivestRequest) GetObjectHandle() uint64 {
	if x != nil {
		return x.ObjectHandle
	}
	return 0
}

func (x *CancelDivestRequest) GetAttributeHandles() []uint64 {
	if x != nil {
		return x.AttributeHandles
	}
	return nil
}

type CancelAcquireRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	WireVersion      WireVersion            `protobuf:"varint,1,opt,name=wire_version,json=wireVersion,proto3,enum=rti.v1.WireVersion" json:"wire_version,omitempty"`
	FederationName   string                 `protobuf:"bytes,2,opt,name=federation_name,json=federationName,proto3" json:"federation_name,omitempty"`
	FederateHandle   uint64                 `protobuf:"varint,3,opt,name=federate_handle,json=federateHandle,proto3" json:"federate_handle,omitempty"` // acquirer withdrawing
	ObjectHandle     uint64                 `protobuf:"varint,4,opt,name=object_handle,json=objectHandle,proto3" json:"object_handle,omitempty"`
	AttributeHandles []uint64               `protobuf:"varint,5,rep,packed,name=attribute_handles,json=attributeHandles,proto3" json:"attribute_handles,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CancelAcquireRequest) Reset() {
	*x = CancelAcquireRequest{}
	mi := &file_rti_v1_ownership_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelAcquireRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelAcquireRequest) ProtoMessage() {}

func (x *CancelAcquireRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_ownership_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelAcquireRequest.ProtoReflect.Descriptor instead.
func (*CancelAcquireRequest) Descriptor() ([]byte, []int) {
	return file_rti_v1_ownership_proto_rawDescGZIP(), []int{5}
}

func (x *CancelAcquireRequest) GetWireVersion() WireVersion {
	if x != nil {
		return x.WireVersion
	}
	return WireVersion_WIRE_VERSION_UNSPECIFIED
}

func (x *CancelAcquireRequest) GetFederationName() string {
	if x != nil {
		return x.FederationName
	}
	return ""
}

func (x *CancelAcquireRequest) GetFederateHandle() uint64 {
	if x != nil {
		return x.FederateHandle
	}
	return 0
}

func (x *CancelAcquireRequest) GetObjectHandle() uint64 {
	if x != nil {
		return x.ObjectHandle
	}
	return 0
}

func (x *CancelAcquireRequest) GetAttributeHandles() []uint64 {
	if x != nil {
		return x.AttributeHandles
	}
	return nil
}

type DivestIfWantedRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	WireVersion      WireVersion            `protobuf:"varint,1,opt,name=wire_version,json=wireVersion,proto3,enum=rti.v1.WireVersion" json:"wire_version,omitempty"`
	FederationName   string                 `protobuf:"bytes,2,opt,name=federation_name,json=federationName,proto3" json:"federation_name,omitempty"`
	FederateHandle   uint64                 `protobuf:"varint,3,opt,name=federate_handle,json=federateHandle,proto3" json:"federate_handle,omitempty"`
	ObjectHandle     uint64                 `protobuf:"varint,4,opt,name=object_handle,json=objectHandle,proto3" json:"object_handle,omitempty"`
	AttributeHandles []uint64               `protobuf:"varint,5,rep,packed,name=attribute_handles,json=attributeHandles,proto3" json:"attribute_handles,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DivestIfWantedRequest) Reset() {
	*x = DivestIfWantedRequest{}
	mi := &file_rti_v1_ownership_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DivestIfWantedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DivestIfWantedRequest) ProtoMessage() {}

func (x *DivestIfWantedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_ownership_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DivestIfWantedRequest.ProtoReflect.Descriptor instead.
func (*DivestIfWantedRequest) Descriptor() ([]byte, []int) {
	return file_rti_v1_ownership_proto_rawDescGZIP(), []int{6}
}

func (x *DivestIfWantedRequest) GetWireVersion() WireVersion {
	if x != nil {
		return x.WireVersion
	}
	return WireVersion_WIRE_VERSION_UNSPECIFIED
}

func (x *DivestIfWantedRequest) GetFederationName() string {
	if x != nil {
		return x.FederationName
	}
	return ""
}

func (x *DivestIfWantedRequest) GetFederateHandle() uint64 {
	if x != nil {
		return x.FederateHandle
	}
	return 0
}

func (x *DivestIfWantedRequest) GetObjectHandle() uint64 {
	if x != nil {
		return x.ObjectHandle
	}
	return 0
}

func (x *DivestIfWantedRequest) GetAttributeHandles() []uint64 {
	if x != nil {
		return x.AttributeHandles
	}
	return nil
}

type QueryOwnershipRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	WireVersion     WireVersion            `protobuf:"varint,1,opt,name=wire_version,json=wireVersion,proto3,enum=rti.v1.WireVersion" json:"wire_version,omitempty"`
	FederationName  string                 `protobuf:"bytes,2,opt,name=federation_name,json=federationName,proto3" json:"federation_name,omitempty"`
	ObjectHandle    uint64                 `protobuf:"varint,3,opt,name=object_handle,json=objectHandle,proto3" json:"object_handle,omitempty"`
	AttributeHandle uint64                 `protobuf:"varint,4,opt,name=attribute_handle,json=attributeHandle,proto3" json:"attribute_handle,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *QueryOwnershipRequest) Reset() {
	*x = QueryOwnershipRequest{}
	mi := &file_rti_v1_ownership_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryOwnershipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryOwnershipRequest) ProtoMessage() {}

func (x *QueryOwnershipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_ownership_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryOwnershipRequest.ProtoReflect.Descriptor instead.
func (*QueryOwnershipRequest) Descriptor() ([]byte, []int) {
	return file_rti_v1_ownership_proto_rawDescGZIP(), []int{7}
}

func (x *QueryOwnershipRequest) GetWireVersion() WireVersion {
	if x != nil {
		return x.WireVersion
	}
	return WireVersion_WIRE_VERSION_UNSPECIFIED
}

func (x *QueryOwnershipRequest) GetFederationName() string {
	if x != nil {
		return x.FederationName
	}
	return ""
}

func (x *QueryOwnershipRequest) GetObjectHandle() uint64 {
	if x != nil {
		return x.ObjectHandle
	}
	return 0
}

func (x *QueryOwnershipRequest) GetAttributeHandle() uint64 {
	if x != nil {
		return x.AttributeHandle
	}
	return 0
}

type QueryOwnershipResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	OwnerFederateHandle uint64                 `protobuf:"varint,1,opt,name=owner_federate_handle,json=ownerFederateHandle,proto3" json:"owner_federate_handle,omitempty"` // 0 if attribute is mid-transfer / unowned
	Owned               bool                   `protobuf:"varint,2,opt,name=owned,proto3" json:"owned,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *QueryOwnershipResponse) Reset() {
	*x = QueryOwnershipResponse{}
	mi := &file_rti_v1_ownership_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryOwnershipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryOwnershipResponse) ProtoMessage() {}

func (x *QueryOwnershipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_ownership_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryOwnershipResponse.ProtoReflect.Descriptor instead.
func (*QueryOwnershipResponse) Descriptor() ([]byte, []int) {
	return file_rti_v1_ownership_proto_rawDescGZIP(), []int{8}
}

func (x *QueryOwnershipResponse) GetOwnerFederateHandle() uint64 {
	if x != nil {
		return x.OwnerFederateHandle
	}
	return 0
}

func (x *QueryOwnershipResponse) GetOwned() bool {
	if x != nil {
		return x.Owned
	}
	return false
}

type IsOwnedRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	WireVersion     WireVersion            `protobuf:"varint,1,opt,name=wire_version,json=wireVersion,proto3,enum=rti.v1.WireVersion" json:"wire_version,omitempty"`
	FederationName  string                 `protobuf:"bytes,2,opt,name=federation_name,json=federationName,proto3" json:"federation_name,omitempty"`
	FederateHandle  uint64                 `protobuf:"varint,3,opt,name=federate_handle,json=federateHandle,proto3" json:"federate_handle,omitempty"`
	ObjectHandle    uint64                 `protobuf:"varint,4,opt,name=object_handle,json=objectHandle,proto3" json:"object_handle,omitempty"`
	AttributeHandle uint64                 `protobuf:"varint,5,opt,name=attribute_handle,json=attributeHandle,proto3" json:"attribute_handle,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *IsOwnedRequest) Reset() {
	*x = IsOwnedRequest{}
	mi := &file_rti_v1_ownership_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsOwnedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsOwnedRequest) ProtoMessage() {}

func (x *IsOwnedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_ownership_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsOwnedRequest.ProtoReflect.Descriptor instead.
func (*IsOwnedRequest) Descriptor() ([]byte, []int) {
	return file_rti_v1_ownership_proto_rawDescGZIP(), []int{9}
}

func (x *IsOwnedRequest) GetWireVersion() WireVersion {
	if x != nil {
		return x.WireVersion
	}
	return WireVersion_WIRE_VERSION_UNSPECIFIED
}

func (x *IsOwnedRequest) GetFederationName() string {
	if x != nil {
		return x.FederationName
	}
	return ""
}

func (x *IsOwnedRequest) GetFederateHandle() uint64 {
	if x != nil {
		return x.FederateHandle
	}
	return 0
}

func (x *IsOwnedRequest) GetObjectHandle() uint64 {
	if x != nil {
		return x.ObjectHandle
	}
	return 0
}

func (x *IsOwnedRequest) GetAttributeHandle() uint64 {
	if x != nil {
		return x.AttributeHandle
	}
	return 0
}

type IsOwnedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owned         bool                   `protobuf:"varint,1,opt,name=owned,proto3" json:"owned,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsOwnedResponse) Reset() {
	*x = IsOwnedResponse{}
	mi := &file_rti_v1_ownership_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsOwnedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsOwnedResponse) ProtoMessage() {}

func (x *IsOwnedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_ownership_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsOwnedResponse.ProtoReflect.Descriptor instead.
func (*IsOwnedResponse) Descriptor() ([]byte, []int) {
	return file_rti_v1_ownership_proto_rawDescGZIP(), []int{10}
}

func (x *IsOwnedResponse) GetOwned() bool {
	if x != nil {
		return x.Owned
	}
	return false
}

// OwnershipRecordEntry is one (object, attribute) ownership entry in
// OwnershipManagerState.owners — captures the current owner of one
// attribute on one object. M13 thread C (docs/srs.md §10.4).
type OwnershipRecordEntry struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ObjectHandle    uint64                 `protobuf:"varint,1,opt,name=object_handle,json=objectHandle,proto3" json:"object_handle,omitempty"`
	AttributeHandle uint64                 `protobuf:"varint,2,opt,name=attribute_handle,json=attributeHandle,proto3" json:"attribute_handle,omitempty"`
	OwnerFederate   uint64                 `protobuf:"varint,3,opt,name=owner_federate,json=ownerFederate,proto3" json:"owner_federate,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OwnershipRecordEntry) Reset() {
	*x = OwnershipRecordEntry{}
	mi := &file_rti_v1_ownership_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OwnershipRecordEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OwnershipRecordEntry) ProtoMessage() {}

func (x *OwnershipRecordEntry) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_ownership_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OwnershipRecordEntry.ProtoReflect.Descriptor instead.
func (*OwnershipRecordEntry) Descriptor() ([]byte, []int) {
	return file_rti_v1_ownership_proto_rawDescGZIP(), []int{11}
}

func (x *OwnershipRecordEntry) GetObjectHandle() uint64 {
	if x != nil {
		return x.ObjectHandle
	}
	return 0
}

func (x *OwnershipRecordEntry) GetAttributeHandle() uint64 {
	if x != nil {
		return x.AttributeHandle
	}
	return 0
}

func (x *OwnershipRecordEntry) GetOwnerFederate() uint64 {
	if x != nil {
		return x.OwnerFederate
	}
	return 0
}

// PendingDivestEntry is one in-flight NegotiatedDivest entry in
// OwnershipManagerState.pending_divests.
type PendingDivestEntry struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ObjectHandle    uint64                 `protobuf:"varint,1,opt,name=object_handle,json=objectHandle,proto3" json:"object_handle,omitempty"`
	AttributeHandle uint64                 `protobuf:"varint,2,opt,name=attribute_handle,json=attributeHandle,proto3" json:"attribute_handle,omitempty"`
	OwnerFederate   uint64                 `protobuf:"varint,3,opt,name=owner_federate,json=ownerFederate,proto3" json:"owner_federate,omitempty"`
	Tag             []byte                 `protobuf:"bytes,4,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PendingDivestEntry) Reset() {
	*x = PendingDivestEntry{}
	mi := &file_rti_v1_ownership_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PendingDivestEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PendingDivestEntry) ProtoMessage() {}

func (x *PendingDivestEntry) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_ownership_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PendingDivestEntry.ProtoReflect.Descriptor instead.
func (*PendingDivestEntry) Descriptor() ([]byte, []int) {
	return file_rti_v1_ownership_proto_rawDescGZIP(), []int{12}
}

func (x *PendingDivestEntry) GetObjectHandle() uint64 {
	if x != nil {
		return x.ObjectHandle
	}
	return 0
}

func (x *PendingDivestEntry) GetAttributeHandle() uint64 {
	if x != nil {
		return x.AttributeHandle
	}
	return 0
}

func (x *PendingDivestEntry) GetOwnerFederate() uint64 {
	if x != nil {
		return x.OwnerFederate
	}
	return 0
}

func (x *PendingDivestEntry) GetTag() []byte {
	if x != nil {
		return x.Tag
	}
	return nil
}

// PendingAcquireEntry is one queued Acquire entry in
// OwnershipManagerState.pending_acquires.
type PendingAcquireEntry struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ObjectHandle     uint64                 `protobuf:"varint,1,opt,name=object_handle,json=objectHandle,proto3" json:"object_handle,omitempty"`
	AttributeHandle  uint64                 `protobuf:"varint,2,opt,name=attribute_handle,json=attributeHandle,proto3" json:"attribute_handle,omitempty"`
	AcquirerFederate uint64                 `protobuf:"varint,3,opt,name=acquirer_federate,json=acquirerFederate,proto3" json:"acquirer_federate,omitempty"`
	Tag              []byte                 `protobuf:"bytes,4,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PendingAcquireEntry) Reset() {
	*x = PendingAcquireEntry{}
	mi := &file_rti_v1_ownership_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PendingAcquireEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PendingAcquireEntry) ProtoMessage() {}

func (x *PendingAcquireEntry) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_ownership_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PendingAcquireEntry.ProtoReflect.Descriptor instead.
func (*PendingAcquireEntry) Descriptor() ([]byte, []int) {
	return file_rti_v1_ownership_proto_rawDescGZIP(), []int{13}
}

func (x *PendingAcquireEntry) GetObjectHandle() uint64 {
	if x != nil {
		return x.ObjectHandle
	}
	return 0
}

func (x *PendingAcquireEntry) GetAttributeHandle() uint64 {
	if x != nil {
		return x.AttributeHandle
	}
	return 0
}

func (x *PendingAcquireEntry) GetAcquirerFederate() uint64 {
	if x != nil {
		return x.AcquirerFederate
	}
	return 0
}

func (x *PendingAcquireEntry) GetTag() []byte {
	if x != nil {
		return x.Tag
	}
	return nil
}

// OwnershipManagerState is the per-federation snapshot persisted into
// the save manifest under key "ownership". M13 thread C
// (docs/srs.md §10.4). On Marshal, every entry slice is sorted
// deterministically (ObjectHandle, AttributeHandle, AcquirerHandle).
type OwnershipManagerState struct {
	state           protoimpl.MessageState  `protogen:"open.v1"`
	Owners          []*OwnershipRecordEntry `protobuf:"bytes,1,rep,name=owners,proto3" json:"owners,omitempty"`
	PendingDivests  []*PendingDivestEntry   `protobuf:"bytes,2,rep,name=pending_divests,json=pendingDivests,proto3" json:"pending_divests,omitempty"`
	PendingAcquires []*PendingAcquireEntry  `protobuf:"bytes,3,rep,name=pending_acquires,json=pendingAcquires,proto3" json:"pending_acquires,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OwnershipManagerState) Reset() {
	*x = OwnershipManagerState{}
	mi := &file_rti_v1_ownership_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OwnershipManagerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OwnershipManagerState) ProtoMessage() {}

func (x *OwnershipManagerState) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_ownership_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OwnershipManagerState.ProtoReflect.Descriptor instead.
func (*OwnershipManagerState) Descriptor() ([]byte, []int) {
	return file_rti_v1_ownership_proto_rawDescGZIP(), []int{14}
}

func (x *OwnershipManagerState) GetOwners() []*OwnershipRecordEntry {
	if x != nil {
		return x.Owners
	}
	return nil
}

func (x *OwnershipManagerState) GetPendingDivests() []*PendingDivestEntry {
	if x != nil {
		return x.PendingDivests
	}
	return nil
}

func (x *OwnershipManagerState) GetPendingAcquires() []*PendingAcquireEntry {
	if x != nil {
		return x.PendingAcquires
	}
	return nil
}

var File_rti_v1_ownership_proto protoreflect.FileDescriptor

const file_rti_v1_ownership_proto_rawDesc = "" +
	"\n" +
	"\x16rti/v1/ownership.proto\x12\x06rti.v1\x1a\x13rti/v1/common.proto\"\xf8\x01\n" +
	"\x1aUnconditionalDivestRequest\x126\n" +
	"\fwire_version\x18\x01 \x01(\x0e2\x13.rti.v1.WireVersionR\vwireVersion\x12'\n" +
	"\x0ffederation_name\x18\x02 \x01(\tR\x0efederationName\x12'\n" +
	"\x0ffederate_handle\x18\x03 \x01(\x04R\x0efederateHandle\x12#\n" +
	"\robject_handle\x18\x04 \x01(\x04R\fobjectHandle\x12+\n" +
	"\x11attribute_handles\x18\x05 \x03(\x04R\x10attributeHandles\"\xa4\x02\n" +
	"\x17NegotiatedDivestRequest\x126\n" +
	"\fwire_version\x18\x01 \x01(\x0e2\x13.rti.v1.WireVersionR\vwireVersion\x12'\n" +
	"\x0ffederation_name\x18\x02 \x01(\tR\x0efederationName\x12'\n" +
	"\x0ffederate_handle\x18\x03 \x01(\x04R\x0efederateHandle\x12#\n" +
	"\robject_handle\x18\x04 \x01(\x04R\fobjectHandle\x12+\n" +
	"\x11attribute_handles\x18\x05 \x03(\x04R\x10attributeHandles\x12\x10\n" +
	"\x03tag\x18\x06 \x01(\fR\x03tag\x12\x1b\n" +
	"\ttwo_phase\x18\a \x01(\bR\btwoPhase\"\xf7\x01\n" +
	"\x19ConfirmDivestitureRequest\x126\n" +
	"\fwire_version\x18\x01 \x01(\x0e2\x13.rti.v1.WireVersionR\vwireVersion\x12'\n" +
	"\x0ffederation_name\x18\x02 \x01(\tR\x0efederationName\x12'\n" +
	"\x0ffederate_handle\x18\x03 \x01(\x04R\x0efederateHandle\x12#\n" +
	"\robject_handle\x18\x04 \x01(\x04R\fobjectHandle\x12+\n" +
	"\x11attribute_handles\x18\x05 \x03(\x04R\x10attributeHandles\"\xa1\x02\n" +
	"\x0eAcquireRequest\x126\n" +
	"\fwire_version\x18\x01 \x01(\x0e2\x13.rti.v1.WireVersionR\vwireVersion\x12'\n" +
	"\x0ffederation_name\x18\x02 \x01(\tR\x0efederationName\x12'\n" +
	"\x0ffederate_handle\x18\x03 \x01(\x04R\x0efederateHandle\x12#\n" +
	"\robject_handle\x18\x04 \x01(\x04R\fobjectHandle\x12+\n" +
	"\x11attribute_handles\x18\x05 \x03(\x04R\x10attributeHandles\x12\x10\n" +
	"\x03tag\x18\x06 \x01(\fR\x03tag\x12!\n" +
	"\fif_available\x18\a \x01(\bR\vifAvailable\"\xf1\x01\n" +
	"\x13CancelDivestRequest\x126\n" +
	"\fwire_version\x18\x01 \x01(\x0e2\x13.rti.v1.WireVersionR\vwireVersion\x12'\n" +
	"\x0ffederation_name\x18\x02 \x01(\tR\x0efederationName\x12'\n" +
	"\x0ffederate_handle\x18\x03 \x01(\x04R\x0efederateHandle\x12#\n" +
	"\robject_handle\x18\x04 \x01(\x04R\fobjectHandle\x12+\n" +
	"\x11attribute_handles\x18\x05 \x03(\x04R\x10attributeHandles\"\xf2\x01\n" +
	"\x14CancelAcquireRequest\x126\n" +
	"\fwire_version\x18\x01 \x01(\x0e2\x13.rti.v1.WireVersionR\vwireVersion\x12'\n" +
	"\x0ffederation_name\x18\x02 \x01(\tR\x0efederationName\x12'\n" +
	"\x0ffederate_handle\x18\x03 \x01(\x04R\x0efederateHandle\x12#\n" +
	"\robject_handle\x18\x04 \x01(\x04R\fobjectHandle\x12+\n" +
	"\x11attribute_handles\x18\x05 \x03(\x04R\x10attributeHandles\"\xf3\x01\n" +
	"\x15DivestIfWantedRequest\x126\n" +
	"\fwire_version\x18\x01 \x01(\x0e2\x13.rti.v1.WireVersionR\vwireVersion\x12'\n" +
	"\x0ffederation_name\x18\x02 \x01(\tR\x0efederationName\x12'\n" +
	"\x0ffederate_handle\x18\x03 \x01(\x04R\x0efederateHandle\x12#\n" +
	"\robject_handle\x18\x04 \x01(\x04R\fobjectHandle\x12+\n" +
	"\x11attribute_handles\x18\x05 \x03(\x04R\x10attributeHandles\"\xc8\x01\n" +
	"\x15QueryOwnershipRequest\x126\n" +
	"\fwire_version\x18\x01 \x01(\x0e2\x13.rti.v1.WireVersionR\vwireVersion\x12'\n" +
	"\x0ffederation_name\x18\x02 \x01(\tR\x0efederationName\x12#\n" +
	"\robject_handle\x18\x03 \x01(\x04R\fobjectHandle\x12)\n" +
	"\x10attribute_handle\x18\x04 \x01(\x04R\x0fattributeHandle\"b\n" +
	"\x16QueryOwnershipResponse\x122\n" +
	"\x15owner_federate_handle\x18\x01 \x01(\x04R\x13ownerFederateHandle\x12\x14\n" +
	"\x05owned\x18\x02 \x01(\bR\x05owned\"\xea\x01\n" +
	"\x0eIsOwnedRequest\x126\n" +
	"\fwire_version\x18\x01 \x01(\x0e2\x13.rti.v1.WireVersionR\vwireVersion\x12'\n" +
	"\x0ffederation_name\x18\x02 \x01(\tR\x0efederationName\x12'\n" +
	"\x0ffederate_handle\x18\x03 \x01(\x04R\x0efederateHandle\x12#\n" +
	"\robject_handle\x18\x04 \x01(\x04R\fobjectHandle\x12)\n" +
	"\x10attribute_handle\x18\x05 \x01(\x04R\x0fattributeHandle\"'\n" +
	"\x0fIsOwnedResponse\x12\x14\n" +
	"\x05owned\x18\x01 \x01(\bR\x05owned\"\x8d\x01\n" +
	"\x14OwnershipRecordEntry\x12#\n" +
	"\robject_handle\x18\x01 \x01(\x04R\fobjectHandle\x12)\n" +
	"\x10attribute_handle\x18\x02 \x01(\x04R\x0fattributeHandle\x12%\n" +
	"\x0eowner_federate\x18\x03 \x01(\x04R\rownerFederate\"\x9d\x01\n" +
	"\x12PendingDivestEntry\x12#\n" +
	"\robject_handle\x18\x01 \x01(\x04R\fobjectHandle\x12)\n" +
	"\x10attribute_handle\x18\x02 \x01(\x04R\x0fattributeHandle\x12%\n" +
	"\x0eowner_federate\x18\x03 \x01(\x04R\rownerFederate\x12\x10\n" +
	"\x03tag\x18\x04 \x01(\fR\x03tag\"\xa4\x01\n" +
	"\x13PendingAcquireEntry\x12#\n" +
	"\robject_handle\x18\x01 \x01(\x04R\fobjectHandle\x12)\n" +
	"\x10attribute_handle\x18\x02 \x01(\x04R\x0fattributeHandle\x12+\n" +
	"\x11acquirer_federate\x18\x03 \x01(\x04R\x10acquirerFederate\x12\x10\n" +
	"\x03tag\x18\x04 \x01(\fR\x03tag\"\xda\x01\n" +
	"\x15OwnershipManagerState\x124\n" +
	"\x06owners\x18\x01 \x03(\v2\x1c.rti.v1.OwnershipRecordEntryR\x06owners\x12C\n" +
	"\x0fpending_divests\x18\x02 \x03(\v2\x1a.rti.v1.PendingDivestEntryR\x0ependingDivests\x12F\n" +
	"\x10pending_acquires\x18\x03 \x03(\v2\x1b.rti.v1.PendingAcquireEntryR\x0fpendingAcquires2\x8f\x06\n" +
	"\x10OwnershipService\x12_\n" +
	"*UnconditionalAttributeOwnershipDivestiture\x12\".rti.v1.UnconditionalDivestRequest\x1a\r.rti.v1.Empty\x12Y\n" +
	"'NegotiatedAttributeOwnershipDivestiture\x12\x1f.rti.v1.NegotiatedDivestRequest\x1a\r.rti.v1.Empty\x12F\n" +
	"\x1dAttributeOwnershipAcquisition\x12\x16.rti.v1.AcquireRequest\x1a\r.rti.v1.Empty\x12[\n" +
	"-CancelNegotiatedAttributeOwnershipDivestiture\x12\x1b.rti.v1.CancelDivestRequest\x1a\r.rti.v1.Empty\x12R\n" +
	"#CancelAttributeOwnershipAcquisition\x12\x1c.rti.v1.CancelAcquireRequest\x1a\r.rti.v1.Empty\x12U\n" +
	"%AttributeOwnershipDivestitureIfWanted\x12\x1d.rti.v1.DivestIfWantedRequest\x1a\r.rti.v1.Empty\x12F\n" +
	"\x12ConfirmDivestiture\x12!.rti.v1.ConfirmDivestitureRequest\x1a\r.rti.v1.Empty\x12X\n" +
	"\x17QueryAttributeOwnership\x12\x1d.rti.v1.QueryOwnershipRequest\x1a\x1e.rti.v1.QueryOwnershipResponse\x12M\n" +
	"\x1aIsAttributeOwnedByFederate\x12\x16.rti.v1.IsOwnedRequest\x1a\x17.rti.v1.IsOwnedResponseB<Z:github.com/cbchoi/gorti/rti/internal/genproto/rti/v1;rtiv1b\x06proto3"

var (
	file_rti_v1_ownership_proto_rawDescOnce sync.Once
	file_rti_v1_ownership_proto_rawDescData []byte
)

func file_rti_v1_ownership_proto_rawDescGZIP() []byte {
	file_rti_v1_ownership_proto_rawDescOnce.Do(func() {
		file_rti_v1_ownership_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rti_v1_ownership_proto_rawDesc), len(file_rti_v1_ownership_proto_rawDesc)))
	})
	return file_rti_v1_ownership_proto_rawDescData
}

var file_rti_v1_ownership_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_rti_v1_ownership_proto_goTypes = []any{
	(*UnconditionalDivestRequest)(nil), // 0: rti.v1.UnconditionalDivestRequest
	(*NegotiatedDivestRequest)(nil),    // 1: rti.v1.NegotiatedDivestRequest
	(*ConfirmDivestitureRequest)(nil),  // 2: rti.v1.ConfirmDivestitureRequest
	(*AcquireRequest)(nil),             // 3: rti.v1.AcquireRequest
	(*CancelDivestRequest)(nil),        // 4: rti.v1.CancelDivestRequest
	(*CancelAcquireRequest)(nil),       // 5: rti.v1.CancelAcquireRequest
	(*DivestIfWantedRequest)(nil),      // 6: rti.v1.DivestIfWantedRequest
	(*QueryOwnershipRequest)(nil),      // 7: rti.v1.QueryOwnershipRequest
	(*QueryOwnershipResponse)(nil),     // 8: rti.v1.QueryOwnershipResponse
	(*IsOwnedRequest)(nil),             // 9: rti.v1.IsOwnedRequest
	(*IsOwnedResponse)(nil),            // 10: rti.v1.IsOwnedResponse
	(*OwnershipRecordEntry)(nil),       // 11: rti.v1.OwnershipRecordEntry
	(*PendingDivestEntry)(nil),         // 12: rti.v1.PendingDivestEntry
	(*PendingAcquireEntry)(nil),        // 13: rti.v1.PendingAcquireEntry
	(*OwnershipManagerState)(nil),      // 14: rti.v1.OwnershipManagerState
	(WireVersion)(0),                   // 15: rti.v1.WireVersion
	(*Empty)(nil),                      // 16: rti.v1.Empty
}
var file_rti_v1_ownership_proto_depIdxs = []int32{
	15, // 0: rti.v1.UnconditionalDivestRequest.wire_version:type_name -> rti.v1.WireVersion
	15, // 1: rti.v1.NegotiatedDivestRequest.wire_version:type_name -> rti.v1.WireVersion
	15, // 2: rti.v1.ConfirmDivestitureRequest.wire_version:type_name -> rti.v1.WireVersion
	15, // 3: rti.v1.AcquireRequest.wire_version:type_name -> rti.v1.WireVersion
	15, // 4: rti.v1.CancelDivestRequest.wire_version:type_name -> rti.v1.WireVersion
	15, // 5: rti.v1.CancelAcquireRequest.wire_version:type_name -> rti.v1.WireVersion
	15, // 6: rti.v1.DivestIfWantedRequest.wire_version:type_name -> rti.v1.WireVersion
	15, // 7: rti.v1.QueryOwnershipRequest.wire_version:type_name -> rti.v1.WireVersion
	15, // 8: rti.v1.IsOwnedRequest.wire_version:type_name -> rti.v1.WireVersion
	11, // 9: rti.v1.OwnershipManagerState.owners:type_name -> rti.v1.OwnershipRecordEntry
	12, // 10: rti.v1.OwnershipManagerState.pending_divests:type_name -> rti.v1.PendingDivestEntry
	13, // 11: rti.v1.OwnershipManagerState.pending_acquires:type_name -> rti.v1.PendingAcquireEntry
	0,  // 12: rti.v1.OwnershipService.UnconditionalAttributeOwnershipDivestiture:input_type -> rti.v1.UnconditionalDivestRequest
	1,  // 13: rti.v1.OwnershipService.NegotiatedAttributeOwnershipDivestiture:input_type -> rti.v1.NegotiatedDivestRequest
	3,  // 14: rti.v1.OwnershipService.AttributeOwnershipAcquisition:input_type -> rti.v1.AcquireRequest
	4,  // 15: rti.v1.OwnershipService.CancelNegotiatedAttributeOwnershipDivestiture:input_type -> rti.v1.CancelDivestRequest
	5,  // 16: rti.v1.OwnershipService.CancelAttributeOwnershipAcquisition:input_type -> rti.v1.CancelAcquireRequest
	6,  // 17: rti.v1.OwnershipService.AttributeOwnershipDivestitureIfWanted:input_type -> rti.v1.DivestIfWantedRequest
	2,  // 18: rti.v1.OwnershipService.ConfirmDivestiture:input_type -> rti.v1.ConfirmDivestitureRequest
	7,  // 19: rti.v1.OwnershipService.QueryAttributeOwnership:input_type -> rti.v1.QueryOwnershipRequest
	9,  // 20: rti.v1.OwnershipService.IsAttributeOwnedByFederate:input_type -> rti.v1.IsOwnedRequest
	16, // 21: rti.v1.OwnershipService.UnconditionalAttributeOwnershipDivestiture:output_type -> rti.v1.Empty
	16, // 22: rti.v1.OwnershipService.NegotiatedAttributeOwnershipDivestiture:output_type -> rti.v1.Empty
	16, // 23: rti.v1.OwnershipService.AttributeOwnershipAcquisition:output_type -> rti.v1.Empty
	16, // 24: rti.v1.OwnershipService.CancelNegotiatedAttributeOwnershipDivestiture:output_type -> rti.v1.Empty
	16, // 25: rti.v1.OwnershipService.CancelAttributeOwnershipAcquisition:output_type -> rti.v1.Empty
	16, // 26: rti.v1.OwnershipService.AttributeOwnershipDivestitureIfWanted:output_type -> rti.v1.Empty
	16, // 27: rti.v1.OwnershipService.ConfirmDivestiture:output_type -> rti.v1.Empty
	8,  // 28: rti.v1.OwnershipService.QueryAttributeOwnership:output_type -> rti.v1.QueryOwnershipResponse
	10, // 29: rti.v1.OwnershipService.IsAttributeOwnedByFederate:output_type -> rti.v1.IsOwnedResponse
	21, // [21:30] is the sub-list for method output_type
	12, // [12:21] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_rti_v1_ownership_proto_init() }
func file_rti_v1_ownership_proto_init() {
	if File_rti_v1_ownership_proto != nil {
		return
	}
	file_rti_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rti_v1_ownership_proto_rawDesc), len(file_rti_v1_ownership_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rti_v1_ownership_proto_goTypes,
		DependencyIndexes: file_rti_v1_ownership_proto_depIdxs,
		MessageInfos:      file_rti_v1_ownership_proto_msgTypes,
	}.Build()
	File_rti_v1_ownership_proto = out.File
	file_rti_v1_ownership_proto_goTypes = nil
	file_rti_v1_ownership_proto_depIdxs = nil
}
