// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: rti/v1/savepoint.proto

package rtiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SaveState int32

const (
	SaveState_SAVE_STATE_UNSPECIFIED SaveState = 0
	SaveState_SAVE_STATE_IDLE        SaveState = 1
	SaveState_SAVE_STATE_INITIATED   SaveState = 2
	SaveState_SAVE_STATE_SAVED       SaveState = 3
	SaveState_SAVE_STATE_NOT_SAVED   SaveState = 4
)

// Enum value maps for SaveState.
var (
	SaveState_name = map[int32]string{
		0: "SAVE_STATE_UNSPECIFIED",
		1: "SAVE_STATE_IDLE",
		2: "SAVE_STATE_INITIATED",
		3: "SAVE_STATE_SAVED",
		4: "SAVE_STATE_NOT_SAVED",
	}
	SaveState_value = map[string]int32{
		"SAVE_STATE_UNSPECIFIED": 0,
		"SAVE_STATE_IDLE":        1,
		"SAVE_STATE_INITIATED":   2,
		"SAVE_STATE_SAVED":       3,
		"SAVE_STATE_NOT_SAVED":   4,
	}
)

func (x SaveState) Enum() *SaveState {
	p := new(SaveState)
	*p = x
	return p
}

func (x SaveState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SaveState) Descriptor() protoreflect.EnumDescriptor {
	return file_rti_v1_savepoint_proto_enumTypes[0].Descriptor()
}

func (SaveState) Type() protoreflect.EnumType {
	return &file_rti_v1_savepoint_proto_enumTypes[0]
}

func (x SaveState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SaveState.Descriptor instead.
func (SaveState) EnumDescriptor() ([]byte, []int) {
	return file_rti_v1_savepoint_proto_rawDescGZIP(), []int{0}
}

type RestoreState int32

const (
	RestoreState_RESTORE_STATE_UNSPECIFIED RestoreState = 0
	RestoreState_RESTORE_STATE_IDLE        RestoreState = 1
	RestoreState_RESTORE_STATE_LOADING     RestoreState = 2
	RestoreState_RESTORE_STATE_INITIATED   RestoreState = 3
	RestoreState_RESTORE_STATE_COMPLETED   RestoreState = 4
	RestoreState_RESTORE_STATE_FAILED      RestoreState = 5
)

// Enum value maps for RestoreState.
var (
	RestoreState_name = map[int32]string{
		0: "RESTORE_STATE_UNSPECIFIED",
		1: "RESTORE_STATE_IDLE",
		2: "RESTORE_STATE_LOADING",
		3: "RESTORE_STATE_INITIATED",
		4: "RESTORE_STATE_COMPLETED",
		5: "RESTORE_STATE_FAILED",
	}
	RestoreState_value = map[string]int32{
		"RESTORE_STATE_UNSPECIFIED": 0,
		"RESTORE_STATE_IDLE":        1,
		"RESTORE_STATE_LOADING":     2,
		"RESTORE_STATE_INITIATED":   3,
		"RESTORE_STATE_COMPLETED":   4,
		"RESTORE_STATE_FAILED":      5,
	}
)

func (x RestoreState) Enum() *RestoreState {
	p := new(RestoreState)
	*p = x
	return p
}

func (x RestoreState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RestoreState) Descriptor() protoreflect.EnumDescriptor {
	return file_rti_v1_savepoint_proto_enumTypes[1].Descriptor()
}

func (RestoreState) Type() protoreflect.EnumType {
	return &file_rti_v1_savepoint_proto_enumTypes[1]
}

func (x RestoreState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RestoreState.Descriptor instead.
func (RestoreState) EnumDescriptor() ([]byte, []int) {
	return file_rti_v1_savepoint_proto_rawDescGZIP(), []int{1}
}

// AbortFederationSave — §4.28 (M24).
type AbortFederationSaveRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WireVersion    WireVersion            `protobuf:"varint,1,opt,name=wire_version,json=wireVersion,proto3,enum=rti.v1.WireVersion" json:"wire_version,omitempty"`
	FederationName string                 `protobuf:"bytes,2,opt,name=federation_name,json=federationName,proto3" json:"federation_name,omitempty"`
	FederateHandle *uint64                `protobuf:"varint,3,opt,name=federate_handle,json=federateHandle,proto3,oneof" json:"federate_handle,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AbortFederationSaveRequest) Reset() {
	*x = AbortFederationSaveRequest{}
	mi := &file_rti_v1_savepoint_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortFederationSaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortFederationSaveRequest) ProtoMessage() {}

func (x *AbortFederationSaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_savepoint_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortFederationSaveRequest.ProtoReflect.Descriptor instead.
func (*AbortFederationSaveRequest) Descriptor() ([]byte, []int) {
	return file_rti_v1_savepoint_proto_rawDescGZIP(), []int{0}
}

func (x *AbortFederationSaveRequest) GetWireVersion() WireVersion {
	if x != nil {
		return x.WireVersion
	}
	return WireVersion_WIRE_VERSION_UNSPECIFIED
}

func (x *AbortFederationSaveRequest) GetFederationName() string {
	if x != nil {
		return x.FederationName
	}
	return ""
}

func (x *AbortFederationSaveRequest) GetFederateHandle() uint64 {
	if x != nil && x.FederateHandle != nil {
		return *x.FederateHandle
	}
	return 0
}

// AbortFederationRestore — §4.30 (M24).
type AbortFederationRestoreRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WireVersion    WireVersion            `protobuf:"varint,1,opt,name=wire_version,json=wireVersion,proto3,enum=rti.v1.WireVersion" json:"wire_version,omitempty"`
	FederationName string                 `protobuf:"bytes,2,opt,name=federation_name,json=federationName,proto3" json:"federation_name,omitempty"`
	FederateHandle *uint64                `protobuf:"varint,3,opt,name=federate_handle,json=federateHandle,proto3,oneof" json:"federate_handle,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AbortFederationRestoreRequest) Reset() {
	*x = AbortFederationRestoreRequest{}
	mi := &file_rti_v1_savepoint_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortFederationRestoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortFederationRestoreRequest) ProtoMessage() {}

func (x *AbortFederationRestoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_savepoint_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortFederationRestoreRequest.ProtoReflect.Descriptor instead.
func (*AbortFederationRestoreRequest) Descriptor() ([]byte, []int) {
	return file_rti_v1_savepoint_proto_rawDescGZIP(), []int{1}
}

func (x *AbortFederationRestoreRequest) GetWireVersion() WireVersion {
	if x != nil {
		return x.WireVersion
	}
	return WireVersion_WIRE_VERSION_UNSPECIFIED
}

func (x *AbortFederationRestoreRequest) GetFederationName() string {
	if x != nil {
		return x.FederationName
	}
	return ""
}

func (x *AbortFederationRestoreRequest) GetFederateHandle() uint64 {
	if x != nil && x.FederateHandle != nil {
		return *x.FederateHandle
	}
	return 0
}

type RequestFederationSaveRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WireVersion    WireVersion            `protobuf:"varint,1,opt,name=wire_version,json=wireVersion,proto3,enum=rti.v1.WireVersion" json:"wire_version,omitempty"`
	FederationName string                 `protobuf:"bytes,2,opt,name=federation_name,json=federationName,proto3" json:"federation_name,omitempty"`
	FederateHandle uint64                 `protobuf:"varint,3,opt,name=federate_handle,json=federateHandle,proto3" json:"federate_handle,omitempty"` // requester
	Label          string                 `protobuf:"bytes,4,opt,name=label,proto3" json:"label,omitempty"`
	// Optional save-time pin; absent means "save now at current sync point".
	SaveTime      *float64 `protobuf:"fixed64,5,opt,name=save_time,json=saveTime,proto3,oneof" json:"save_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestFederationSaveRequest) Reset() {
	*x = RequestFederationSaveRequest{}
	mi := &file_rti_v1_savepoint_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestFederationSaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestFederationSaveRequest) ProtoMessage() {}

func (x *RequestFederationSaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_savepoint_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestFederationSaveRequest.ProtoReflect.Descriptor instead.
func (*RequestFederationSaveRequest) Descriptor() ([]byte, []int) {
	return file_rti_v1_savepoint_proto_rawDescGZIP(), []int{2}
}

func (x *RequestFederationSaveRequest) GetWireVersion() WireVersion {
	if x != nil {
		return x.WireVersion
	}
	return WireVersion_WIRE_VERSION_UNSPECIFIED
}

func (x *RequestFederationSaveRequest) GetFederationName() string {
	if x != nil {
		return x.FederationName
	}
	return ""
}

func (x *RequestFederationSaveRequest) GetFederateHandle() uint64 {
	if x != nil {
		return x.FederateHandle
	}
	return 0
}

func (x *RequestFederationSaveRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *RequestFederationSaveRequest) GetSaveTime() float64 {
	if x != nil && x.SaveTime != nil {
		return *x.SaveTime
	}
	return 0
}

type FederateSaveResponseRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WireVersion    WireVersion            `protobuf:"varint,1,opt,name=wire_version,json=wireVersion,proto3,enum=rti.v1.WireVersion" json:"wire_version,omitempty"`
	FederationName string                 `protobuf:"bytes,2,opt,name=federation_name,json=federationName,proto3" json:"federation_name,omitempty"`
	FederateHandle uint64                 `protobuf:"varint,3,opt,name=federate_handle,json=federateHandle,proto3" json:"federate_handle,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FederateSaveResponseRequest) Reset() {
	*x = FederateSaveResponseRequest{}
	mi := &file_rti_v1_savepoint_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FederateSaveResponseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FederateSaveResponseRequest) ProtoMessage() {}

func (x *FederateSaveResponseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_savepoint_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FederateSaveResponseRequest.ProtoReflect.Descriptor instead.
func (*FederateSaveResponseRequest) Descriptor() ([]byte, []int) {
	return file_rti_v1_savepoint_proto_rawDescGZIP(), []int{3}
}

func (x *FederateSaveResponseRequest) GetWireVersion() WireVersion {
	if x != nil {
		return x.WireVersion
	}
	return WireVersion_WIRE_VERSION_UNSPECIFIED
}

func (x *FederateSaveResponseRequest) GetFederationName() string {
	if x != nil {
		return x.FederationName
	}
	return ""
}

func (x *FederateSaveResponseRequest) GetFederateHandle() uint64 {
	if x != nil {
		return x.FederateHandle
	}
	return 0
}

type QuerySaveStateRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WireVersion    WireVersion            `protobuf:"varint,1,opt,name=wire_version,json=wireVersion,proto3,enum=rti.v1.WireVersion" json:"wire_version,omitempty"`
	FederationName string                 `protobuf:"bytes,2,opt,name=federation_name,json=federationName,proto3" json:"federation_name,omitempty"`
	Label          string                 `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *QuerySaveStateRequest) Reset() {
	*x = QuerySaveStateRequest{}
	mi := &file_rti_v1_savepoint_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuerySaveStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuerySaveStateRequest) ProtoMessage() {}

func (x *QuerySaveStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_savepoint_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuerySaveStateRequest.ProtoReflect.Descriptor instead.
func (*QuerySaveStateRequest) Descriptor() ([]byte, []int) {
	return file_rti_v1_savepoint_proto_rawDescGZIP(), []int{4}
}

func (x *QuerySaveStateRequest) GetWireVersion() WireVersion {
	if x != nil {
		return x.WireVersion
	}
	return WireVersion_WIRE_VERSION_UNSPECIFIED
}

func (x *QuerySaveStateRequest) GetFederationName() string {
	if x != nil {
		return x.FederationName
	}
	return ""
}

func (x *QuerySaveStateRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type QuerySaveStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         SaveState              `protobuf:"varint,1,opt,name=state,proto3,enum=rti.v1.SaveState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuerySaveStateResponse) Reset() {
	*x = QuerySaveStateResponse{}
	mi := &file_rti_v1_savepoint_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuerySaveStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuerySaveStateResponse) ProtoMessage() {}

func (x *QuerySaveStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_savepoint_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuerySaveStateResponse.ProtoReflect.Descriptor instead.
func (*QuerySaveStateResponse) Descriptor() ([]byte, []int) {
	return file_rti_v1_savepoint_proto_rawDescGZIP(), []int{5}
}

func (x *QuerySaveStateResponse) GetState() SaveState {
	if x != nil {
		return x.State
	}
	return SaveState_SAVE_STATE_UNSPECIFIED
}

type RequestFederationRestoreRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WireVersion    WireVersion            `protobuf:"varint,1,opt,name=wire_version,json=wireVersion,proto3,enum=rti.v1.WireVersion" json:"wire_version,omitempty"`
	FederationName string                 `protobuf:"bytes,2,opt,name=federation_name,json=federationName,proto3" json:"federation_name,omitempty"`
	FederateHandle uint64                 `protobuf:"varint,3,opt,name=federate_handle,json=federateHandle,proto3" json:"federate_handle,omitempty"` // requester
	Label          string                 `protobuf:"bytes,4,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RequestFederationRestoreRequest) Reset() {
	*x = RequestFederationRestoreRequest{}
	mi := &file_rti_v1_savepoint_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestFederationRestoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestFederationRestoreRequest) ProtoMessage() {}

func (x *RequestFederationRestoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_savepoint_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestFederationRestoreRequest.ProtoReflect.Descriptor instead.
func (*RequestFederationRestoreRequest) Descriptor() ([]byte, []int) {
	return file_rti_v1_savepoint_proto_rawDescGZIP(), []int{6}
}

func (x *RequestFederationRestoreRequest) GetWireVersion() WireVersion {
	if x != nil {
		return x.WireVersion
	}
	return WireVersion_WIRE_VERSION_UNSPECIFIED
}

func (x *RequestFederationRestoreRequest) GetFederationName() string {
	if x != nil {
		return x.FederationName
	}
	return ""
}

func (x *RequestFederationRestoreRequest) GetFederateHandle() uint64 {
	if x != nil {
		return x.FederateHandle
	}
	return 0
}

func (x *RequestFederationRestoreRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type FederateRestoreResponseRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WireVersion    WireVersion            `protobuf:"varint,1,opt,name=wire_version,json=wireVersion,proto3,enum=rti.v1.WireVersion" json:"wire_version,omitempty"`
	FederationName string                 `protobuf:"bytes,2,opt,name=federation_name,json=federationName,proto3" json:"federation_name,omitempty"`
	FederateHandle uint64                 `protobuf:"varint,3,opt,name=federate_handle,json=federateHandle,proto3" json:"federate_handle,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FederateRestoreResponseRequest) Reset() {
	*x = FederateRestoreResponseRequest{}
	mi := &file_rti_v1_savepoint_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FederateRestoreResponseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FederateRestoreResponseRequest) ProtoMessage() {}

func (x *FederateRestoreResponseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_savepoint_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FederateRestoreResponseRequest.ProtoReflect.Descriptor instead.
func (*FederateRestoreResponseRequest) Descriptor() ([]byte, []int) {
	return file_rti_v1_savepoint_proto_rawDescGZIP(), []int{7}
}

func (x *FederateRestoreResponseRequest) GetWireVersion() WireVersion {
	if x != nil {
		return x.WireVersion
	}
	return WireVersion_WIRE_VERSION_UNSPECIFIED
}

func (x *FederateRestoreResponseRequest) GetFederationName() string {
	if x != nil {
		return x.FederationName
	}
	return ""
}

func (x *FederateRestoreResponseRequest) GetFederateHandle() uint64 {
	if x != nil {
		return x.FederateHandle
	}
	return 0
}

type QueryRestoreStateRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WireVersion    WireVersion            `protobuf:"varint,1,opt,name=wire_version,json=wireVersion,proto3,enum=rti.v1.WireVersion" json:"wire_version,omitempty"`
	FederationName string                 `protobuf:"bytes,2,opt,name=federation_name,json=federationName,proto3" json:"federation_name,omitempty"`
	Label          string                 `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *QueryRestoreStateRequest) Reset() {
	*x = QueryRestoreStateRequest{}
	mi := &file_rti_v1_savepoint_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRestoreStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRestoreStateRequest) ProtoMessage() {}

func (x *QueryRestoreStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_savepoint_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRestoreStateRequest.ProtoReflect.Descriptor instead.
func (*QueryRestoreStateRequest) Descriptor() ([]byte, []int) {
	return file_rti_v1_savepoint_proto_rawDescGZIP(), []int{8}
}

func (x *QueryRestoreStateRequest) GetWireVersion() WireVersion {
	if x != nil {
		return x.WireVersion
	}
	return WireVersion_WIRE_VERSION_UNSPECIFIED
}

func (x *QueryRestoreStateRequest) GetFederationName() string {
	if x != nil {
		return x.FederationName
	}
	return ""
}

func (x *QueryRestoreStateRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type QueryRestoreStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         RestoreState           `protobuf:"varint,1,opt,name=state,proto3,enum=rti.v1.RestoreState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRestoreStateResponse) Reset() {
	*x = QueryRestoreStateResponse{}
	mi := &file_rti_v1_savepoint_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRestoreStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRestoreStateResponse) ProtoMessage() {}

func (x *QueryRestoreStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_savepoint_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRestoreStateResponse.ProtoReflect.Descriptor instead.
func (*QueryRestoreStateResponse) Descriptor() ([]byte, []int) {
	return file_rti_v1_savepoint_proto_rawDescGZIP(), []int{9}
}

func (x *QueryRestoreStateResponse) GetState() RestoreState {
	if x != nil {
		return x.State
	}
	return RestoreState_RESTORE_STATE_UNSPECIFIED
}

var File_rti_v1_savepoint_proto protoreflect.FileDescriptor

const file_rti_v1_savepoint_proto_rawDesc = "" +
	"\n" +
	"\x16rti/v1/savepoint.proto\x12\x06rti.v1\x1a\x13rti/v1/common.proto\"\xbf\x01\n" +
	"\x1aAbortFederationSaveRequest\x126\n" +
	"\fwire_version\x18\x01 \x01(\x0e2\x13.rti.v1.WireVersionR\vwireVersion\x12'\n" +
	"\x0ffederation_name\x18\x02 \x01(\tR\x0efederationName\x12,\n" +
	"\x0ffederate_handle\x18\x03 \x01(\x04H\x00R\x0efederateHandle\x88\x01\x01B\x12\n" +
	"\x10_federate_handle\"\xc2\x01\n" +
	"\x1dAbortFederationRestoreRequest\x126\n" +
	"\fwire_version\x18\x01 \x01(\x0e2\x13.rti.v1.WireVersionR\vwireVersion\x12'\n" +
	"\x0ffederation_name\x18\x02 \x01(\tR\x0efederationName\x12,\n" +
	"\x0ffederate_handle\x18\x03 \x01(\x04H\x00R\x0efederateHandle\x88\x01\x01B\x12\n" +
	"\x10_federate_handle\"\xee\x01\n" +
	"\x1cRequestFederationSaveRequest\x126\n" +
	"\fwire_version\x18\x01 \x01(\x0e2\x13.rti.v1.WireVersionR\vwireVersion\x12'\n" +
	"\x0ffederation_name\x18\x02 \x01(\tR\x0efederationName\x12'\n" +
	"\x0ffederate_handle\x18\x03 \x01(\x04R\x0efederateHandle\x12\x14\n" +
	"\x05label\x18\x04 \x01(\tR\x05label\x12 \n" +
	"\tsave_time\x18\x05 \x01(\x01H\x00R\bsaveTime\x88\x01\x01B\f\n" +
	"\n" +
	"_save_time\"\xa7\x01\n" +
	"\x1bFederateSaveResponseRequest\x126\n" +
	"\fwire_version\x18\x01 \x01(\x0e2\x13.rti.v1.WireVersionR\vwireVersion\x12'\n" +
	"\x0ffederation_name\x18\x02 \x01(\tR\x0efederationName\x12'\n" +
	"\x0ffederate_handle\x18\x03 \x01(\x04R\x0efederateHandle\"\x8e\x01\n" +
	"\x15QuerySaveStateRequest\x126\n" +
	"\fwire_version\x18\x01 \x01(\x0e2\x13.rti.v1.WireVersionR\vwireVersion\x12'\n" +
	"\x0ffederation_name\x18\x02 \x01(\tR\x0efederationName\x12\x14\n" +
	"\x05label\x18\x03 \x01(\tR\x05label\"A\n" +
	"\x16QuerySaveStateResponse\x12'\n" +
	"\x05state\x18\x01 \x01(\x0e2\x11.rti.v1.SaveStateR\x05state\"\xc1\x01\n" +
	"\x1fRequestFederationRestoreRequest\x126\n" +
	"\fwire_version\x18\x01 \x01(\x0e2\x13.rti.v1.WireVersionR\vwireVersion\x12'\n" +
	"\x0ffederation_name\x18\x02 \x01(\tR\x0efederationName\x12'\n" +
	"\x0ffederate_handle\x18\x03 \x01(\x04R\x0efederateHandle\x12\x14\n" +
	"\x05label\x18\x04 \x01(\tR\x05label\"\xaa\x01\n" +
	"\x1eFederateRestoreResponseRequest\x126\n" +
	"\fwire_version\x18\x01 \x01(\x0e2\x13.rti.v1.WireVersionR\vwireVersion\x12'\n" +
	"\x0ffederation_name\x18\x02 \x01(\tR\x0efederationName\x12'\n" +
	"\x0ffederate_handle\x18\x03 \x01(\x04R\x0efederateHandle\"\x91\x01\n" +
	"\x18QueryRestoreStateRequest\x126\n" +
	"\fwire_version\x18\x01 \x01(\x0e2\x13.rti.v1.WireVersionR\vwireVersion\x12'\n" +
	"\x0ffederation_name\x18\x02 \x01(\tR\x0efederationName\x12\x14\n" +
	"\x05label\x18\x03 \x01(\tR\x05label\"G\n" +
	"\x19QueryRestoreStateResponse\x12*\n" +
	"\x05state\x18\x01 \x01(\x0e2\x14.rti.v1.RestoreStateR\x05state*\x86\x01\n" +
	"\tSaveState\x12\x1a\n" +
	"\x16SAVE_STATE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fSAVE_STATE_IDLE\x10\x01\x12\x18\n" +
	"\x14SAVE_STATE_INITIATED\x10\x02\x12\x14\n" +
	"\x10SAVE_STATE_SAVED\x10\x03\x12\x18\n" +
	"\x14SAVE_STATE_NOT_SAVED\x10\x04*\xb4\x01\n" +
	"\fRestoreState\x12\x1d\n" +
	"\x19RESTORE_STATE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12RESTORE_STATE_IDLE\x10\x01\x12\x19\n" +
	"\x15RESTORE_STATE_LOADING\x10\x02\x12\x1b\n" +
	"\x17RESTORE_STATE_INITIATED\x10\x03\x12\x1b\n" +
	"\x17RESTORE_STATE_COMPLETED\x10\x04\x12\x18\n" +
	"\x14RESTORE_STATE_FAILED\x10\x052\xe6\x05\n" +
	"\x10SavepointService\x12L\n" +
	"\x15RequestFederationSave\x12$.rti.v1.RequestFederationSaveRequest\x1a\r.rti.v1.Empty\x12J\n" +
	"\x14FederateSaveComplete\x12#.rti.v1.FederateSaveResponseRequest\x1a\r.rti.v1.Empty\x12M\n" +
	"\x17FederateSaveNotComplete\x12#.rti.v1.FederateSaveResponseRequest\x1a\r.rti.v1.Empty\x12O\n" +
	"\x0eQuerySaveState\x12\x1d.rti.v1.QuerySaveStateRequest\x1a\x1e.rti.v1.QuerySaveStateResponse\x12R\n" +
	"\x18RequestFederationRestore\x12'.rti.v1.RequestFederationRestoreRequest\x1a\r.rti.v1.Empty\x12P\n" +
	"\x17FederateRestoreComplete\x12&.rti.v1.FederateRestoreResponseRequest\x1a\r.rti.v1.Empty\x12X\n" +
	"\x11QueryRestoreState\x12 .rti.v1.QueryRestoreStateRequest\x1a!.rti.v1.QueryRestoreStateResponse\x12H\n" +
	"\x13AbortFederationSave\x12\".rti.v1.AbortFederationSaveRequest\x1a\r.rti.v1.Empty\x12N\n" +
	"\x16AbortFederationRestore\x12%.rti.v1.AbortFederationRestoreRequest\x1a\r.rti.v1.EmptyB<Z:github.com/cbchoi/gorti/rti/internal/genproto/rti/v1;rtiv1b\x06proto3"

var (
	file_rti_v1_savepoint_proto_rawDescOnce sync.Once
	file_rti_v1_savepoint_proto_rawDescData []byte
)

func file_rti_v1_savepoint_proto_rawDescGZIP() []byte {
	file_rti_v1_savepoint_proto_rawDescOnce.Do(func() {
		file_rti_v1_savepoint_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rti_v1_savepoint_proto_rawDesc), len(file_rti_v1_savepoint_proto_rawDesc)))
	})
	return file_rti_v1_savepoint_proto_rawDescData
}

var file_rti_v1_savepoint_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_rti_v1_savepoint_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_rti_v1_savepoint_proto_goTypes = []any{
	(SaveState)(0),                          // 0: rti.v1.SaveState
	(RestoreState)(0),                       // 1: rti.v1.RestoreState
	(*AbortFederationSaveRequest)(nil),      // 2: rti.v1.AbortFederationSaveRequest
	(*AbortFederationRestoreRequest)(nil),   // 3: rti.v1.AbortFederationRestoreRequest
	(*RequestFederationSaveRequest)(nil),    // 4: rti.v1.RequestFederationSaveRequest
	(*FederateSaveResponseRequest)(nil),     // 5: rti.v1.FederateSaveResponseRequest
	(*QuerySaveStateRequest)(nil),           // 6: rti.v1.QuerySaveStateRequest
	(*QuerySaveStateResponse)(nil),          // 7: rti.v1.QuerySaveStateResponse
	(*RequestFederationRestoreRequest)(nil), // 8: rti.v1.RequestFederationRestoreRequest
	(*FederateRestoreResponseRequest)(nil),  // 9: rti.v1.FederateRestoreResponseRequest
	(*QueryRestoreStateRequest)(nil),        // 10: rti.v1.QueryRestoreStateRequest
	(*QueryRestoreStateResponse)(nil),       // 11: rti.v1.QueryRestoreStateResponse
	(WireVersion)(0),                        // 12: rti.v1.WireVersion
	(*Empty)(nil),                           // 13: rti.v1.Empty
}
var file_rti_v1_savepoint_proto_depIdxs = []int32{
	12, // 0: rti.v1.AbortFederationSaveRequest.wire_version:type_name -> rti.v1.WireVersion
	12, // 1: rti.v1.AbortFederationRestoreRequest.wire_version:type_name -> rti.v1.WireVersion
	12, // 2: rti.v1.RequestFederationSaveRequest.wire_version:type_name -> rti.v1.WireVersion
	12, // 3: rti.v1.FederateSaveResponseRequest.wire_version:type_name -> rti.v1.WireVersion
	12, // 4: rti.v1.QuerySaveStateRequest.wire_version:type_name -> rti.v1.WireVersion
	0,  // 5: rti.v1.QuerySaveStateResponse.state:type_name -> rti.v1.SaveState
	12, // 6: rti.v1.RequestFederationRestoreRequest.wire_version:type_name -> rti.v1.WireVersion
	12, // 7: rti.v1.FederateRestoreResponseRequest.wire_version:type_name -> rti.v1.WireVersion
	12, // 8: rti.v1.QueryRestoreStateRequest.wire_version:type_name -> rti.v1.WireVersion
	1,  // 9: rti.v1.QueryRestoreStateResponse.state:type_name -> rti.v1.RestoreState
	4,  // 10: rti.v1.SavepointService.RequestFederationSave:input_type -> rti.v1.RequestFederationSaveRequest
	5,  // 11: rti.v1.SavepointService.FederateSaveComplete:input_type -> rti.v1.FederateSaveResponseRequest
	5,  // 12: rti.v1.SavepointService.FederateSaveNotComplete:input_type -> rti.v1.FederateSaveResponseRequest
	6,  // 13: rti.v1.SavepointService.QuerySaveState:input_type -> rti.v1.QuerySaveStateRequest
	8,  // 14: rti.v1.SavepointService.RequestFederationRestore:input_type -> rti.v1.RequestFederationRestoreRequest
	9,  // 15: rti.v1.SavepointService.FederateRestoreComplete:input_type -> rti.v1.FederateRestoreResponseRequest
	10, // 16: rti.v1.SavepointService.QueryRestoreState:input_type -> rti.v1.QueryRestoreStateRequest
	2,  // 17: rti.v1.SavepointService.AbortFederationSave:input_type -> rti.v1.AbortFederationSaveRequest
	3,  // 18: rti.v1.SavepointService.AbortFederationRestore:input_type -> rti.v1.AbortFederationRestoreRequest
	13, // 19: rti.v1.SavepointService.RequestFederationSave:output_type -> rti.v1.Empty
	13, // 20: rti.v1.SavepointService.FederateSaveComplete:output_type -> rti.v1.Empty
	13, // 21: rti.v1.SavepointService.FederateSaveNotComplete:output_type -> rti.v1.Empty
	7,  // 22: rti.v1.SavepointService.QuerySaveState:output_type -> rti.v1.QuerySaveStateResponse
	13, // 23: rti.v1.SavepointService.RequestFederationRestore:output_type -> rti.v1.Empty
	13, // 24: rti.v1.SavepointService.FederateRestoreComplete:output_type -> rti.v1.Empty
	11, // 25: rti.v1.SavepointService.QueryRestoreState:output_type -> rti.v1.QueryRestoreStateResponse
	13, // 26: rti.v1.SavepointService.AbortFederationSave:output_type -> rti.v1.Empty
	13, // 27: rti.v1.SavepointService.AbortFederationRestore:output_type -> rti.v1.Empty
	19, // [19:28] is the sub-list for method output_type
	10, // [10:19] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_rti_v1_savepoint_proto_init() }
func file_rti_v1_savepoint_proto_init() {
	if File_rti_v1_savepoint_proto != nil {
		return
	}
	file_rti_v1_common_proto_init()
	file_rti_v1_savepoint_proto_msgTypes[0].OneofWrappers = []any{}
	file_rti_v1_savepoint_proto_msgTypes[1].OneofWrappers = []any{}
	file_rti_v1_savepoint_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rti_v1_savepoint_proto_rawDesc), len(file_rti_v1_savepoint_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rti_v1_savepoint_proto_goTypes,
		DependencyIndexes: file_rti_v1_savepoint_proto_depIdxs,
		EnumInfos:         file_rti_v1_savepoint_proto_enumTypes,
		MessageInfos:      file_rti_v1_savepoint_proto_msgTypes,
	}.Build()
	File_rti_v1_savepoint_proto = out.File
	file_rti_v1_savepoint_proto_goTypes = nil
	file_rti_v1_savepoint_proto_depIdxs = nil
}
