// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: rti/v1/support.proto

package rtiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetObjectClassHandleRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WireVersion    WireVersion            `protobuf:"varint,1,opt,name=wire_version,json=wireVersion,proto3,enum=rti.v1.WireVersion" json:"wire_version,omitempty"`
	FederationName string                 `protobuf:"bytes,2,opt,name=federation_name,json=federationName,proto3" json:"federation_name,omitempty"`
	ClassName      string                 `protobuf:"bytes,3,opt,name=class_name,json=className,proto3" json:"class_name,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetObjectClassHandleRequest) Reset() {
	*x = GetObjectClassHandleRequest{}
	mi := &file_rti_v1_support_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetObjectClassHandleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObjectClassHandleRequest) ProtoMessage() {}

func (x *GetObjectClassHandleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_support_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObjectClassHandleRequest.ProtoReflect.Descriptor instead.
func (*GetObjectClassHandleRequest) Descriptor() ([]byte, []int) {
	return file_rti_v1_support_proto_rawDescGZIP(), []int{0}
}

func (x *GetObjectClassHandleRequest) GetWireVersion() WireVersion {
	if x != nil {
		return x.WireVersion
	}
	return WireVersion_WIRE_VERSION_UNSPECIFIED
}

func (x *GetObjectClassHandleRequest) GetFederationName() string {
	if x != nil {
		return x.FederationName
	}
	return ""
}

func (x *GetObjectClassHandleRequest) GetClassName() string {
	if x != nil {
		return x.ClassName
	}
	return ""
}

type GetObjectClassHandleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClassHandle   uint64                 `protobuf:"varint,1,opt,name=class_handle,json=classHandle,proto3" json:"class_handle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetObjectClassHandleResponse) Reset() {
	*x = GetObjectClassHandleResponse{}
	mi := &file_rti_v1_support_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetObjectClassHandleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObjectClassHandleResponse) ProtoMessage() {}

func (x *GetObjectClassHandleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_support_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObjectClassHandleResponse.ProtoReflect.Descriptor instead.
func (*GetObjectClassHandleResponse) Descriptor() ([]byte, []int) {
	return file_rti_v1_support_proto_rawDescGZIP(), []int{1}
}

func (x *GetObjectClassHandleResponse) GetClassHandle() uint64 {
	if x != nil {
		return x.ClassHandle
	}
	return 0
}

type GetObjectClassNameRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WireVersion    WireVersion            `protobuf:"varint,1,opt,name=wire_version,json=wireVersion,proto3,enum=rti.v1.WireVersion" json:"wire_version,omitempty"`
	FederationName string                 `protobuf:"bytes,2,opt,name=federation_name,json=federationName,proto3" json:"federation_name,omitempty"`
	ClassHandle    uint64                 `protobuf:"varint,3,opt,name=class_handle,json=classHandle,proto3" json:"class_handle,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetObjectClassNameRequest) Reset() {
	*x = GetObjectClassNameRequest{}
	mi := &file_rti_v1_support_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetObjectClassNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObjectClassNameRequest) ProtoMessage() {}

func (x *GetObjectClassNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_support_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObjectClassNameRequest.ProtoReflect.Descriptor instead.
func (*GetObjectClassNameRequest) Descriptor() ([]byte, []int) {
	return file_rti_v1_support_proto_rawDescGZIP(), []int{2}
}

func (x *GetObjectClassNameRequest) GetWireVersion() WireVersion {
	if x != nil {
		return x.WireVersion
	}
	return WireVersion_WIRE_VERSION_UNSPECIFIED
}

func (x *GetObjectClassNameRequest) GetFederationName() string {
	if x != nil {
		return x.FederationName
	}
	return ""
}

func (x *GetObjectClassNameRequest) GetClassHandle() uint64 {
	if x != nil {
		return x.ClassHandle
	}
	return 0
}

type GetObjectClassNameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClassName     string                 `protobuf:"bytes,1,opt,name=class_name,json=className,proto3" json:"class_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetObjectClassNameResponse) Reset() {
	*x = GetObjectClassNameResponse{}
	mi := &file_rti_v1_support_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetObjectClassNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObjectClassNameResponse) ProtoMessage() {}

func (x *GetObjectClassNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_support_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObjectClassNameResponse.ProtoReflect.Descriptor instead.
func (*GetObjectClassNameResponse) Descriptor() ([]byte, []int) {
	return file_rti_v1_support_proto_rawDescGZIP(), []int{3}
}

func (x *GetObjectClassNameResponse) GetClassName() string {
	if x != nil {
		return x.ClassName
	}
	return ""
}

type GetAttributeHandleRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WireVersion    WireVersion            `protobuf:"varint,1,opt,name=wire_version,json=wireVersion,proto3,enum=rti.v1.WireVersion" json:"wire_version,omitempty"`
	FederationName string                 `protobuf:"bytes,2,opt,name=federation_name,json=federationName,proto3" json:"federation_name,omitempty"`
	ClassHandle    uint64                 `protobuf:"varint,3,opt,name=class_handle,json=classHandle,proto3" json:"class_handle,omitempty"`
	AttributeName  string                 `protobuf:"bytes,4,opt,name=attribute_name,json=attributeName,proto3" json:"attribute_name,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetAttributeHandleRequest) Reset() {
	*x = GetAttributeHandleRequest{}
	mi := &file_rti_v1_support_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAttributeHandleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttributeHandleRequest) ProtoMessage() {}

func (x *GetAttributeHandleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_support_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttributeHandleRequest.ProtoReflect.Descriptor instead.
func (*GetAttributeHandleRequest) Descriptor() ([]byte, []int) {
	return file_rti_v1_support_proto_rawDescGZIP(), []int{4}
}

func (x *GetAttributeHandleRequest) GetWireVersion() WireVersion {
	if x != nil {
		return x.WireVersion
	}
	return WireVersion_WIRE_VERSION_UNSPECIFIED
}

func (x *GetAttributeHandleRequest) GetFederationName() string {
	if x != nil {
		return x.FederationName
	}
	return ""
}

func (x *GetAttributeHandleRequest) GetClassHandle() uint64 {
	if x != nil {
		return x.ClassHandle
	}
	return 0
}

func (x *GetAttributeHandleRequest) GetAttributeName() string {
	if x != nil {
		return x.AttributeName
	}
	return ""
}

type GetAttributeHandleResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AttributeHandle uint64                 `protobuf:"varint,1,opt,name=attribute_handle,json=attributeHandle,proto3" json:"attribute_handle,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetAttributeHandleResponse) Reset() {
	*x = GetAttributeHandleResponse{}
	mi := &file_rti_v1_support_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAttributeHandleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttributeHandleResponse) ProtoMessage() {}

func (x *GetAttributeHandleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_support_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttributeHandleResponse.ProtoReflect.Descriptor instead.
func (*GetAttributeHandleResponse) Descriptor() ([]byte, []int) {
	return file_rti_v1_support_proto_rawDescGZIP(), []int{5}
}

func (x *GetAttributeHandleResponse) GetAttributeHandle() uint64 {
	if x != nil {
		return x.AttributeHandle
	}
	return 0
}

type GetAttributeNameRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	WireVersion     WireVersion            `protobuf:"varint,1,opt,name=wire_version,json=wireVersion,proto3,enum=rti.v1.WireVersion" json:"wire_version,omitempty"`
	FederationName  string                 `protobuf:"bytes,2,opt,name=federation_name,json=federationName,proto3" json:"federation_name,omitempty"`
	ClassHandle     uint64                 `protobuf:"varint,3,opt,name=class_handle,json=classHandle,proto3" json:"class_handle,omitempty"`
	AttributeHandle uint64                 `protobuf:"varint,4,opt,name=attribute_handle,json=attributeHandle,proto3" json:"attribute_handle,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetAttributeNameRequest) Reset() {
	*x = GetAttributeNameRequest{}
	mi := &file_rti_v1_support_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAttributeNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttributeNameRequest) ProtoMessage() {}

func (x *GetAttributeNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_support_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttributeNameRequest.ProtoReflect.Descriptor instead.
func (*GetAttributeNameRequest) Descriptor() ([]byte, []int) {
	return file_rti_v1_support_proto_rawDescGZIP(), []int{6}
}

func (x *GetAttributeNameRequest) GetWireVersion() WireVersion {
	if x != nil {
		return x.WireVersion
	}
	return WireVersion_WIRE_VERSION_UNSPECIFIED
}

func (x *GetAttributeNameRequest) GetFederationName() string {
	if x != nil {
		return x.FederationName
	}
	return ""
}

func (x *GetAttributeNameRequest) GetClassHandle() uint64 {
	if x != nil {
		return x.ClassHandle
	}
	return 0
}

func (x *GetAttributeNameRequest) GetAttributeHandle() uint64 {
	if x != nil {
		return x.AttributeHandle
	}
	return 0
}

type GetAttributeNameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AttributeName string                 `protobuf:"bytes,1,opt,name=attribute_name,json=attributeName,proto3" json:"attribute_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAttributeNameResponse) Reset() {
	*x = GetAttributeNameResponse{}
	mi := &file_rti_v1_support_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAttributeNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttributeNameResponse) ProtoMessage() {}

func (x *GetAttributeNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_support_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttributeNameResponse.ProtoReflect.Descriptor instead.
func (*GetAttributeNameResponse) Descriptor() ([]byte, []int) {
	return file_rti_v1_support_proto_rawDescGZIP(), []int{7}
}

func (x *GetAttributeNameResponse) GetAttributeName() string {
	if x != nil {
		return x.AttributeName
	}
	return ""
}

type GetInteractionClassHandleRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WireVersion    WireVersion            `protobuf:"varint,1,opt,name=wire_version,json=wireVersion,proto3,enum=rti.v1.WireVersion" json:"wire_version,omitempty"`
	FederationName string                 `protobuf:"bytes,2,opt,name=federation_name,json=federationName,proto3" json:"federation_name,omitempty"`
	ClassName      string                 `protobuf:"bytes,3,opt,name=class_name,json=className,proto3" json:"class_name,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetInteractionClassHandleRequest) Reset() {
	*x = GetInteractionClassHandleRequest{}
	mi := &file_rti_v1_support_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInteractionClassHandleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInteractionClassHandleRequest) ProtoMessage() {}

func (x *GetInteractionClassHandleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_support_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInteractionClassHandleRequest.ProtoReflect.Descriptor instead.
func (*GetInteractionClassHandleRequest) Descriptor() ([]byte, []int) {
	return file_rti_v1_support_proto_rawDescGZIP(), []int{8}
}

func (x *GetInteractionClassHandleRequest) GetWireVersion() WireVersion {
	if x != nil {
		return x.WireVersion
	}
	return WireVersion_WIRE_VERSION_UNSPECIFIED
}

func (x *GetInteractionClassHandleRequest) GetFederationName() string {
	if x != nil {
		return x.FederationName
	}
	return ""
}

func (x *GetInteractionClassHandleRequest) GetClassName() string {
	if x != nil {
		return x.ClassName
	}
	return ""
}

type GetInteractionClassHandleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClassHandle   uint64                 `protobuf:"varint,1,opt,name=class_handle,json=classHandle,proto3" json:"class_handle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInteractionClassHandleResponse) Reset() {
	*x = GetInteractionClassHandleResponse{}
	mi := &file_rti_v1_support_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInteractionClassHandleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInteractionClassHandleResponse) ProtoMessage() {}

func (x *GetInteractionClassHandleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_support_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInteractionClassHandleResponse.ProtoReflect.Descriptor instead.
func (*GetInteractionClassHandleResponse) Descriptor() ([]byte, []int) {
	return file_rti_v1_support_proto_rawDescGZIP(), []int{9}
}

func (x *GetInteractionClassHandleResponse) GetClassHandle() uint64 {
	if x != nil {
		return x.ClassHandle
	}
	return 0
}

type GetInteractionClassNameRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WireVersion    WireVersion            `protobuf:"varint,1,opt,name=wire_version,json=wireVersion,proto3,enum=rti.v1.WireVersion" json:"wire_version,omitempty"`
	FederationName string                 `protobuf:"bytes,2,opt,name=federation_name,json=federationName,proto3" json:"federation_name,omitempty"`
	ClassHandle    uint64                 `protobuf:"varint,3,opt,name=class_handle,json=classHandle,proto3" json:"class_handle,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetInteractionClassNameRequest) Reset() {
	*x = GetInteractionClassNameRequest{}
	mi := &file_rti_v1_support_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInteractionClassNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInteractionClassNameRequest) ProtoMessage() {}

func (x *GetInteractionClassNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_support_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInteractionClassNameRequest.ProtoReflect.Descriptor instead.
func (*GetInteractionClassNameRequest) Descriptor() ([]byte, []int) {
	return file_rti_v1_support_proto_rawDescGZIP(), []int{10}
}

func (x *GetInteractionClassNameRequest) GetWireVersion() WireVersion {
	if x != nil {
		return x.WireVersion
	}
	return WireVersion_WIRE_VERSION_UNSPECIFIED
}

func (x *GetInteractionClassNameRequest) GetFederationName() string {
	if x != nil {
		return x.FederationName
	}
	return ""
}

func (x *GetInteractionClassNameRequest) GetClassHandle() uint64 {
	if x != nil {
		return x.ClassHandle
	}
	return 0
}

type GetInteractionClassNameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClassName     string                 `protobuf:"bytes,1,opt,name=class_name,json=className,proto3" json:"class_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInteractionClassNameResponse) Reset() {
	*x = GetInteractionClassNameResponse{}
	mi := &file_rti_v1_support_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInteractionClassNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInteractionClassNameResponse) ProtoMessage() {}

func (x *GetInteractionClassNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_support_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInteractionClassNameResponse.ProtoReflect.Descriptor instead.
func (*GetInteractionClassNameResponse) Descriptor() ([]byte, []int) {
	return file_rti_v1_support_proto_rawDescGZIP(), []int{11}
}

func (x *GetInteractionClassNameResponse) GetClassName() string {
	if x != nil {
		return x.ClassName
	}
	return ""
}

type GetParameterHandleRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WireVersion    WireVersion            `protobuf:"varint,1,opt,name=wire_version,json=wireVersion,proto3,enum=rti.v1.WireVersion" json:"wire_version,omitempty"`
	FederationName string                 `protobuf:"bytes,2,opt,name=federation_name,json=federationName,proto3" json:"federation_name,omitempty"`
	ClassHandle    uint64                 `protobuf:"varint,3,opt,name=class_handle,json=classHandle,proto3" json:"class_handle,omitempty"`
	ParameterName  string                 `protobuf:"bytes,4,opt,name=parameter_name,json=parameterName,proto3" json:"parameter_name,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetParameterHandleRequest) Reset() {
	*x = GetParameterHandleRequest{}
	mi := &file_rti_v1_support_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetParameterHandleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetParameterHandleRequest) ProtoMessage() {}

func (x *GetParameterHandleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_support_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetParameterHandleRequest.ProtoReflect.Descriptor instead.
func (*GetParameterHandleRequest) Descriptor() ([]byte, []int) {
	return file_rti_v1_support_proto_rawDescGZIP(), []int{12}
}

func (x *GetParameterHandleRequest) GetWireVersion() WireVersion {
	if x != nil {
		return x.WireVersion
	}
	return WireVersion_WIRE_VERSION_UNSPECIFIED
}

func (x *GetParameterHandleRequest) GetFederationName() string {
	if x != nil {
		return x.FederationName
	}
	return ""
}

func (x *GetParameterHandleRequest) GetClassHandle() uint64 {
	if x != nil {
		return x.ClassHandle
	}
	return 0
}

func (x *GetParameterHandleRequest) GetParameterName() string {
	if x != nil {
		return x.ParameterName
	}
	return ""
}

type GetParameterHandleResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ParameterHandle uint64                 `protobuf:"varint,1,opt,name=parameter_handle,json=parameterHandle,proto3" json:"parameter_handle,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetParameterHandleResponse) Reset() {
	*x = GetParameterHandleResponse{}
	mi := &file_rti_v1_support_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetParameterHandleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetParameterHandleResponse) ProtoMessage() {}

func (x *GetParameterHandleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_support_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetParameterHandleResponse.ProtoReflect.Descriptor instead.
func (*GetParameterHandleResponse) Descriptor() ([]byte, []int) {
	return file_rti_v1_support_proto_rawDescGZIP(), []int{13}
}

func (x *GetParameterHandleResponse) GetParameterHandle() uint64 {
	if x != nil {
		return x.ParameterHandle
	}
	return 0
}

type GetParameterNameRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	WireVersion     WireVersion            `protobuf:"varint,1,opt,name=wire_version,json=wireVersion,proto3,enum=rti.v1.WireVersion" json:"wire_version,omitempty"`
	FederationName  string                 `protobuf:"bytes,2,opt,name=federation_name,json=federationName,proto3" json:"federation_name,omitempty"`
	ClassHandle     uint64                 `protobuf:"varint,3,opt,name=class_handle,json=classHandle,proto3" json:"class_handle,omitempty"`
	ParameterHandle uint64                 `protobuf:"varint,4,opt,name=parameter_handle,json=parameterHandle,proto3" json:"parameter_handle,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetParameterNameRequest) Reset() {
	*x = GetParameterNameRequest{}
	mi := &file_rti_v1_support_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetParameterNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetParameterNameRequest) ProtoMessage() {}

func (x *GetParameterNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_support_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetParameterNameRequest.ProtoReflect.Descriptor instead.
func (*GetParameterNameRequest) Descriptor() ([]byte, []int) {
	return file_rti_v1_support_proto_rawDescGZIP(), []int{14}
}

func (x *GetParameterNameRequest) GetWireVersion() WireVersion {
	if x != nil {
		return x.WireVersion
	}
	return WireVersion_WIRE_VERSION_UNSPECIFIED
}

func (x *GetParameterNameRequest) GetFederationName() string {
	if x != nil {
		return x.FederationName
	}
	return ""
}

func (x *GetParameterNameRequest) GetClassHandle() uint64 {
	if x != nil {
		return x.ClassHandle
	}
	return 0
}

func (x *GetParameterNameRequest) GetParameterHandle() uint64 {
	if x != nil {
		return x.ParameterHandle
	}
	return 0
}

type GetParameterNameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParameterName string                 `protobuf:"bytes,1,opt,name=parameter_name,json=parameterName,proto3" json:"parameter_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetParameterNameResponse) Reset() {
	*x = GetParameterNameResponse{}
	mi := &file_rti_v1_support_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetParameterNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetParameterNameResponse) ProtoMessage() {}

func (x *GetParameterNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_support_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetParameterNameResponse.ProtoReflect.Descriptor instead.
func (*GetParameterNameResponse) Descriptor() ([]byte, []int) {
	return file_rti_v1_support_proto_rawDescGZIP(), []int{15}
}

func (x *GetParameterNameResponse) GetParameterName() string {
	if x != nil {
		return x.ParameterName
	}
	return ""
}

type GetDimensionHandleRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WireVersion    WireVersion            `protobuf:"varint,1,opt,name=wire_version,json=wireVersion,proto3,enum=rti.v1.WireVersion" json:"wire_version,omitempty"`
	FederationName string                 `protobuf:"bytes,2,opt,name=federation_name,json=federationName,proto3" json:"federation_name,omitempty"`
	DimensionName  string                 `protobuf:"bytes,3,opt,name=dimension_name,json=dimensionName,proto3" json:"dimension_name,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetDimensionHandleRequest) Reset() {
	*x = GetDimensionHandleRequest{}
	mi := &file_rti_v1_support_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDimensionHandleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDimensionHandleRequest) ProtoMessage() {}

func (x *GetDimensionHandleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_support_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDimensionHandleRequest.ProtoReflect.Descriptor instead.
func (*GetDimensionHandleRequest) Descriptor() ([]byte, []int) {
	return file_rti_v1_support_proto_rawDescGZIP(), []int{16}
}

func (x *GetDimensionHandleRequest) GetWireVersion() WireVersion {
	if x != nil {
		return x.WireVersion
	}
	return WireVersion_WIRE_VERSION_UNSPECIFIED
}

func (x *GetDimensionHandleRequest) GetFederationName() string {
	if x != nil {
		return x.FederationName
	}
	return ""
}

func (x *GetDimensionHandleRequest) GetDimensionName() string {
	if x != nil {
		return x.DimensionName
	}
	return ""
}

type GetDimensionHandleResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DimensionHandle uint64                 `protobuf:"varint,1,opt,name=dimension_handle,json=dimensionHandle,proto3" json:"dimension_handle,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetDimensionHandleResponse) Reset() {
	*x = GetDimensionHandleResponse{}
	mi := &file_rti_v1_support_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDimensionHandleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDimensionHandleResponse) ProtoMessage() {}

func (x *GetDimensionHandleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_support_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDimensionHandleResponse.ProtoReflect.Descriptor instead.
func (*GetDimensionHandleResponse) Descriptor() ([]byte, []int) {
	return file_rti_v1_support_proto_rawDescGZIP(), []int{17}
}

func (x *GetDimensionHandleResponse) GetDimensionHandle() uint64 {
	if x != nil {
		return x.DimensionHandle
	}
	return 0
}

type GetDimensionNameRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	WireVersion     WireVersion            `protobuf:"varint,1,opt,name=wire_version,json=wireVersion,proto3,enum=rti.v1.WireVersion" json:"wire_version,omitempty"`
	FederationName  string                 `protobuf:"bytes,2,opt,name=federation_name,json=federationName,proto3" json:"federation_name,omitempty"`
	DimensionHandle uint64                 `protobuf:"varint,3,opt,name=dimension_handle,json=dimensionHandle,proto3" json:"dimension_handle,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetDimensionNameRequest) Reset() {
	*x = GetDimensionNameRequest{}
	mi := &file_rti_v1_support_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDimensionNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDimensionNameRequest) ProtoMessage() {}

func (x *GetDimensionNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_support_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDimensionNameRequest.ProtoReflect.Descriptor instead.
func (*GetDimensionNameRequest) Descriptor() ([]byte, []int) {
	return file_rti_v1_support_proto_rawDescGZIP(), []int{18}
}

func (x *GetDimensionNameRequest) GetWireVersion() WireVersion {
	if x != nil {
		return x.WireVersion
	}
	return WireVersion_WIRE_VERSION_UNSPECIFIED
}

func (x *GetDimensionNameRequest) GetFederationName() string {
	if x != nil {
		return x.FederationName
	}
	return ""
}

func (x *GetDimensionNameRequest) GetDimensionHandle() uint64 {
	if x != nil {
		return x.DimensionHandle
	}
	return 0
}

type GetDimensionNameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DimensionName string                 `protobuf:"bytes,1,opt,name=dimension_name,json=dimensionName,proto3" json:"dimension_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDimensionNameResponse) Reset() {
	*x = GetDimensionNameResponse{}
	mi := &file_rti_v1_support_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDimensionNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDimensionNameResponse) ProtoMessage() {}

func (x *GetDimensionNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_support_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDimensionNameResponse.ProtoReflect.Descriptor instead.
func (*GetDimensionNameResponse) Descriptor() ([]byte, []int) {
	return file_rti_v1_support_proto_rawDescGZIP(), []int{19}
}

func (x *GetDimensionNameResponse) GetDimensionName() string {
	if x != nil {
		return x.DimensionName
	}
	return ""
}

type GetDimensionUpperBoundRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	WireVersion     WireVersion            `protobuf:"varint,1,opt,name=wire_version,json=wireVersion,proto3,enum=rti.v1.WireVersion" json:"wire_version,omitempty"`
	FederationName  string                 `protobuf:"bytes,2,opt,name=federation_name,json=federationName,proto3" json:"federation_name,omitempty"`
	DimensionHandle uint64                 `protobuf:"varint,3,opt,name=dimension_handle,json=dimensionHandle,proto3" json:"dimension_handle,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetDimensionUpperBoundRequest) Reset() {
	*x = GetDimensionUpperBoundRequest{}
	mi := &file_rti_v1_support_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDimensionUpperBoundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDimensionUpperBoundRequest) ProtoMessage() {}

func (x *GetDimensionUpperBoundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_support_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDimensionUpperBoundRequest.ProtoReflect.Descriptor instead.
func (*GetDimensionUpperBoundRequest) Descriptor() ([]byte, []int) {
	return file_rti_v1_support_proto_rawDescGZIP(), []int{20}
}

func (x *GetDimensionUpperBoundRequest) GetWireVersion() WireVersion {
	if x != nil {
		return x.WireVersion
	}
	return WireVersion_WIRE_VERSION_UNSPECIFIED
}

func (x *GetDimensionUpperBoundRequest) GetFederationName() string {
	if x != nil {
		return x.FederationName
	}
	return ""
}

func (x *GetDimensionUpperBoundRequest) GetDimensionHandle() uint64 {
	if x != nil {
		return x.DimensionHandle
	}
	return 0
}

type GetDimensionUpperBoundResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UpperBound    uint64                 `protobuf:"varint,1,opt,name=upper_bound,json=upperBound,proto3" json:"upper_bound,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDimensionUpperBoundResponse) Reset() {
	*x = GetDimensionUpperBoundResponse{}
	mi := &file_rti_v1_support_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDimensionUpperBoundResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDimensionUpperBoundResponse) ProtoMessage() {}

func (x *GetDimensionUpperBoundResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_support_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDimensionUpperBoundResponse.ProtoReflect.Descriptor instead.
func (*GetDimensionUpperBoundResponse) Descriptor() ([]byte, []int) {
	return file_rti_v1_support_proto_rawDescGZIP(), []int{21}
}

func (x *GetDimensionUpperBoundResponse) GetUpperBound() uint64 {
	if x != nil {
		return x.UpperBound
	}
	return 0
}

type GetOrderTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WireVersion   WireVersion            `protobuf:"varint,1,opt,name=wire_version,json=wireVersion,proto3,enum=rti.v1.WireVersion" json:"wire_version,omitempty"`
	OrderName     string                 `protobuf:"bytes,2,opt,name=order_name,json=orderName,proto3" json:"order_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderTypeRequest) Reset() {
	*x = GetOrderTypeRequest{}
	mi := &file_rti_v1_support_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderTypeRequest) ProtoMessage() {}

func (x *GetOrderTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_support_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderTypeRequest.ProtoReflect.Descriptor instead.
func (*GetOrderTypeRequest) Descriptor() ([]byte, []int) {
	return file_rti_v1_support_proto_rawDescGZIP(), []int{22}
}

func (x *GetOrderTypeRequest) GetWireVersion() WireVersion {
	if x != nil {
		return x.WireVersion
	}
	return WireVersion_WIRE_VERSION_UNSPECIFIED
}

func (x *GetOrderTypeRequest) GetOrderName() string {
	if x != nil {
		return x.OrderName
	}
	return ""
}

type GetOrderTypeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderType     uint32                 `protobuf:"varint,1,opt,name=order_type,json=orderType,proto3" json:"order_type,omitempty"` // 1=Receive, 2=TimeStamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderTypeResponse) Reset() {
	*x = GetOrderTypeResponse{}
	mi := &file_rti_v1_support_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderTypeResponse) ProtoMessage() {}

func (x *GetOrderTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_support_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderTypeResponse.ProtoReflect.Descriptor instead.
func (*GetOrderTypeResponse) Descriptor() ([]byte, []int) {
	return file_rti_v1_support_proto_rawDescGZIP(), []int{23}
}

func (x *GetOrderTypeResponse) GetOrderType() uint32 {
	if x != nil {
		return x.OrderType
	}
	return 0
}

type GetOrderNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WireVersion   WireVersion            `protobuf:"varint,1,opt,name=wire_version,json=wireVersion,proto3,enum=rti.v1.WireVersion" json:"wire_version,omitempty"`
	OrderType     uint32                 `protobuf:"varint,2,opt,name=order_type,json=orderType,proto3" json:"order_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderNameRequest) Reset() {
	*x = GetOrderNameRequest{}
	mi := &file_rti_v1_support_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderNameRequest) ProtoMessage() {}

func (x *GetOrderNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_support_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderNameRequest.ProtoReflect.Descriptor instead.
func (*GetOrderNameRequest) Descriptor() ([]byte, []int) {
	return file_rti_v1_support_proto_rawDescGZIP(), []int{24}
}

func (x *GetOrderNameRequest) GetWireVersion() WireVersion {
	if x != nil {
		return x.WireVersion
	}
	return WireVersion_WIRE_VERSION_UNSPECIFIED
}

func (x *GetOrderNameRequest) GetOrderType() uint32 {
	if x != nil {
		return x.OrderType
	}
	return 0
}

type GetOrderNameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderName     string                 `protobuf:"bytes,1,opt,name=order_name,json=orderName,proto3" json:"order_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderNameResponse) Reset() {
	*x = GetOrderNameResponse{}
	mi := &file_rti_v1_support_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderNameResponse) ProtoMessage() {}

func (x *GetOrderNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_support_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderNameResponse.ProtoReflect.Descriptor instead.
func (*GetOrderNameResponse) Descriptor() ([]byte, []int) {
	return file_rti_v1_support_proto_rawDescGZIP(), []int{25}
}

func (x *GetOrderNameResponse) GetOrderName() string {
	if x != nil {
		return x.OrderName
	}
	return ""
}

type GetTransportationTypeRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	WireVersion        WireVersion            `protobuf:"varint,1,opt,name=wire_version,json=wireVersion,proto3,enum=rti.v1.WireVersion" json:"wire_version,omitempty"`
	TransportationName string                 `protobuf:"bytes,2,opt,name=transportation_name,json=transportationName,proto3" json:"transportation_name,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetTransportationTypeRequest) Reset() {
	*x = GetTransportationTypeRequest{}
	mi := &file_rti_v1_support_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransportationTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransportationTypeRequest) ProtoMessage() {}

func (x *GetTransportationTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_support_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransportationTypeRequest.ProtoReflect.Descriptor instead.
func (*GetTransportationTypeRequest) Descriptor() ([]byte, []int) {
	return file_rti_v1_support_proto_rawDescGZIP(), []int{26}
}

func (x *GetTransportationTypeRequest) GetWireVersion() WireVersion {
	if x != nil {
		return x.WireVersion
	}
	return WireVersion_WIRE_VERSION_UNSPECIFIED
}

func (x *GetTransportationTypeRequest) GetTransportationName() string {
	if x != nil {
		return x.TransportationName
	}
	return ""
}

type GetTransportationTypeResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TransportationType uint32                 `protobuf:"varint,1,opt,name=transportation_type,json=transportationType,proto3" json:"transportation_type,omitempty"` // 1=HLAreliable, 2=HLAbestEffort
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetTransportationTypeResponse) Reset() {
	*x = GetTransportationTypeResponse{}
	mi := &file_rti_v1_support_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransportationTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransportationTypeResponse) ProtoMessage() {}

func (x *GetTransportationTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_support_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransportationTypeResponse.ProtoReflect.Descriptor instead.
func (*GetTransportationTypeResponse) Descriptor() ([]byte, []int) {
	return file_rti_v1_support_proto_rawDescGZIP(), []int{27}
}

func (x *GetTransportationTypeResponse) GetTransportationType() uint32 {
	if x != nil {
		return x.TransportationType
	}
	return 0
}

type GetTransportationNameRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	WireVersion        WireVersion            `protobuf:"varint,1,opt,name=wire_version,json=wireVersion,proto3,enum=rti.v1.WireVersion" json:"wire_version,omitempty"`
	TransportationType uint32                 `protobuf:"varint,2,opt,name=transportation_type,json=transportationType,proto3" json:"transportation_type,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetTransportationNameRequest) Reset() {
	*x = GetTransportationNameRequest{}
	mi := &file_rti_v1_support_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransportationNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransportationNameRequest) ProtoMessage() {}

func (x *GetTransportationNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_support_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransportationNameRequest.ProtoReflect.Descriptor instead.
func (*GetTransportationNameRequest) Descriptor() ([]byte, []int) {
	return file_rti_v1_support_proto_rawDescGZIP(), []int{28}
}

func (x *GetTransportationNameRequest) GetWireVersion() WireVersion {
	if x != nil {
		return x.WireVersion
	}
	return WireVersion_WIRE_VERSION_UNSPECIFIED
}

func (x *GetTransportationNameRequest) GetTransportationType() uint32 {
	if x != nil {
		return x.TransportationType
	}
	return 0
}

type GetTransportationNameResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TransportationName string                 `protobuf:"bytes,1,opt,name=transportation_name,json=transportationName,proto3" json:"transportation_name,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetTransportationNameResponse) Reset() {
	*x = GetTransportationNameResponse{}
	mi := &file_rti_v1_support_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransportationNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransportationNameResponse) ProtoMessage() {}

func (x *GetTransportationNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_support_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransportationNameResponse.ProtoReflect.Descriptor instead.
func (*GetTransportationNameResponse) Descriptor() ([]byte, []int) {
	return file_rti_v1_support_proto_rawDescGZIP(), []int{29}
}

func (x *GetTransportationNameResponse) GetTransportationName() string {
	if x != nil {
		return x.TransportationName
	}
	return ""
}

// §6.30 — resolve an object instance name to its runtime handle.
type GetObjectInstanceHandleRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WireVersion    WireVersion            `protobuf:"varint,1,opt,name=wire_version,json=wireVersion,proto3,enum=rti.v1.WireVersion" json:"wire_version,omitempty"`
	FederationName string                 `protobuf:"bytes,2,opt,name=federation_name,json=federationName,proto3" json:"federation_name,omitempty"`
	ObjectName     string                 `protobuf:"bytes,3,opt,name=object_name,json=objectName,proto3" json:"object_name,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetObjectInstanceHandleRequest) Reset() {
	*x = GetObjectInstanceHandleRequest{}
	mi := &file_rti_v1_support_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetObjectInstanceHandleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObjectInstanceHandleRequest) ProtoMessage() {}

func (x *GetObjectInstanceHandleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_support_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObjectInstanceHandleRequest.ProtoReflect.Descriptor instead.
func (*GetObjectInstanceHandleRequest) Descriptor() ([]byte, []int) {
	return file_rti_v1_support_proto_rawDescGZIP(), []int{30}
}

func (x *GetObjectInstanceHandleRequest) GetWireVersion() WireVersion {
	if x != nil {
		return x.WireVersion
	}
	return WireVersion_WIRE_VERSION_UNSPECIFIED
}

func (x *GetObjectInstanceHandleRequest) GetFederationName() string {
	if x != nil {
		return x.FederationName
	}
	return ""
}

func (x *GetObjectInstanceHandleRequest) GetObjectName() string {
	if x != nil {
		return x.ObjectName
	}
	return ""
}

type GetObjectInstanceHandleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectHandle  uint64                 `protobuf:"varint,1,opt,name=object_handle,json=objectHandle,proto3" json:"object_handle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetObjectInstanceHandleResponse) Reset() {
	*x = GetObjectInstanceHandleResponse{}
	mi := &file_rti_v1_support_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetObjectInstanceHandleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObjectInstanceHandleResponse) ProtoMessage() {}

func (x *GetObjectInstanceHandleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_support_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObjectInstanceHandleResponse.ProtoReflect.Descriptor instead.
func (*GetObjectInstanceHandleResponse) Descriptor() ([]byte, []int) {
	return file_rti_v1_support_proto_rawDescGZIP(), []int{31}
}

func (x *GetObjectInstanceHandleResponse) GetObjectHandle() uint64 {
	if x != nil {
		return x.ObjectHandle
	}
	return 0
}

// §6.31 — resolve an object instance handle to its registered name.
type GetObjectInstanceNameRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WireVersion    WireVersion            `protobuf:"varint,1,opt,name=wire_version,json=wireVersion,proto3,enum=rti.v1.WireVersion" json:"wire_version,omitempty"`
	FederationName string                 `protobuf:"bytes,2,opt,name=federation_name,json=federationName,proto3" json:"federation_name,omitempty"`
	ObjectHandle   uint64                 `protobuf:"varint,3,opt,name=object_handle,json=objectHandle,proto3" json:"object_handle,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetObjectInstanceNameRequest) Reset() {
	*x = GetObjectInstanceNameRequest{}
	mi := &file_rti_v1_support_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetObjectInstanceNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObjectInstanceNameRequest) ProtoMessage() {}

func (x *GetObjectInstanceNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_support_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObjectInstanceNameRequest.ProtoReflect.Descriptor instead.
func (*GetObjectInstanceNameRequest) Descriptor() ([]byte, []int) {
	return file_rti_v1_support_proto_rawDescGZIP(), []int{32}
}

func (x *GetObjectInstanceNameRequest) GetWireVersion() WireVersion {
	if x != nil {
		return x.WireVersion
	}
	return WireVersion_WIRE_VERSION_UNSPECIFIED
}

func (x *GetObjectInstanceNameRequest) GetFederationName() string {
	if x != nil {
		return x.FederationName
	}
	return ""
}

func (x *GetObjectInstanceNameRequest) GetObjectHandle() uint64 {
	if x != nil {
		return x.ObjectHandle
	}
	return 0
}

type GetObjectInstanceNameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectName    string                 `protobuf:"bytes,1,opt,name=object_name,json=objectName,proto3" json:"object_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetObjectInstanceNameResponse) Reset() {
	*x = GetObjectInstanceNameResponse{}
	mi := &file_rti_v1_support_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetObjectInstanceNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObjectInstanceNameResponse) ProtoMessage() {}

func (x *GetObjectInstanceNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_support_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObjectInstanceNameResponse.ProtoReflect.Descriptor instead.
func (*GetObjectInstanceNameResponse) Descriptor() ([]byte, []int) {
	return file_rti_v1_support_proto_rawDescGZIP(), []int{33}
}

func (x *GetObjectInstanceNameResponse) GetObjectName() string {
	if x != nil {
		return x.ObjectName
	}
	return ""
}

var File_rti_v1_support_proto protoreflect.FileDescriptor

const file_rti_v1_support_proto_rawDesc = "" +
	"\n" +
	"\x14rti/v1/support.proto\x12\x06rti.v1\x1a\x13rti/v1/common.proto\"\x9d\x01\n" +
	"\x1bGetObjectClassHandleRequest\x126\n" +
	"\fwire_version\x18\x01 \x01(\x0e2\x13.rti.v1.WireVersionR\vwireVersion\x12'\n" +
	"\x0ffederation_name\x18\x02 \x01(\tR\x0efederationName\x12\x1d\n" +
	"\n" +
	"class_name\x18\x03 \x01(\tR\tclassName\"A\n" +
	"\x1cGetObjectClassHandleResponse\x12!\n" +
	"\fclass_handle\x18\x01 \x01(\x04R\vclassHandle\"\x9f\x01\n" +
	"\x19GetObjectClassNameRequest\x126\n" +
	"\fwire_version\x18\x01 \x01(\x0e2\x13.rti.v1.WireVersionR\vwireVersion\x12'\n" +
	"\x0ffederation_name\x18\x02 \x01(\tR\x0efederationName\x12!\n" +
	"\fclass_handle\x18\x03 \x01(\x04R\vclassHandle\";\n" +
	"\x1aGetObjectClassNameResponse\x12\x1d\n" +
	"\n" +
	"class_name\x18\x01 \x01(\tR\tclassName\"\xc6\x01\n" +
	"\x19GetAttributeHandleRequest\x126\n" +
	"\fwire_version\x18\x01 \x01(\x0e2\x13.rti.v1.WireVersionR\vwireVersion\x12'\n" +
	"\x0ffederation_name\x18\x02 \x01(\tR\x0efederationName\x12!\n" +
	"\fclass_handle\x18\x03 \x01(\x04R\vclassHandle\x12%\n" +
	"\x0eattribute_name\x18\x04 \x01(\tR\rattributeName\"G\n" +
	"\x1aGetAttributeHandleResponse\x12)\n" +
	"\x10attribute_handle\x18\x01 \x01(\x04R\x0fattributeHandle\"\xc8\x01\n" +
	"\x17GetAttributeNameRequest\x126\n" +
	"\fwire_version\x18\x01 \x01(\x0e2\x13.rti.v1.WireVersionR\vwireVersion\x12'\n" +
	"\x0ffederation_name\x18\x02 \x01(\tR\x0efederationName\x12!\n" +
	"\fclass_handle\x18\x03 \x01(\x04R\vclassHandle\x12)\n" +
	"\x10attribute_handle\x18\x04 \x01(\x04R\x0fattributeHandle\"A\n" +
	"\x18GetAttributeNameResponse\x12%\n" +
	"\x0eattribute_name\x18\x01 \x01(\tR\rattributeName\"\xa2\x01\n" +
	" GetInteractionClassHandleRequest\x126\n" +
	"\fwire_version\x18\x01 \x01(\x0e2\x13.rti.v1.WireVersionR\vwireVersion\x12'\n" +
	"\x0ffederation_name\x18\x02 \x01(\tR\x0efederationName\x12\x1d\n" +
	"\n" +
	"class_name\x18\x03 \x01(\tR\tclassName\"F\n" +
	"!GetInteractionClassHandleResponse\x12!\n" +
	"\fclass_handle\x18\x01 \x01(\x04R\vclassHandle\"\xa4\x01\n" +
	"\x1eGetInteractionClassNameRequest\x126\n" +
	"\fwire_version\x18\x01 \x01(\x0e2\x13.rti.v1.WireVersionR\vwireVersion\x12'\n" +
	"\x0ffederation_name\x18\x02 \x01(\tR\x0efederationName\x12!\n" +
	"\fclass_handle\x18\x03 \x01(\x04R\vclassHandle\"@\n" +
	"\x1fGetInteractionClassNameResponse\x12\x1d\n" +
	"\n" +
	"class_name\x18\x01 \x01(\tR\tclassName\"\xc6\x01\n" +
	"\x19GetParameterHandleRequest\x126\n" +
	"\fwire_version\x18\x01 \x01(\x0e2\x13.rti.v1.WireVersionR\vwireVersion\x12'\n" +
	"\x0ffederation_name\x18\x02 \x01(\tR\x0efederationName\x12!\n" +
	"\fclass_handle\x18\x03 \x01(\x04R\vclassHandle\x12%\n" +
	"\x0eparameter_name\x18\x04 \x01(\tR\rparameterName\"G\n" +
	"\x1aGetParameterHandleResponse\x12)\n" +
	"\x10parameter_handle\x18\x01 \x01(\x04R\x0fparameterHandle\"\xc8\x01\n" +
	"\x17GetParameterNameRequest\x126\n" +
	"\fwire_version\x18\x01 \x01(\x0e2\x13.rti.v1.WireVersionR\vwireVersion\x12'\n" +
	"\x0ffederation_name\x18\x02 \x01(\tR\x0efederationName\x12!\n" +
	"\fclass_handle\x18\x03 \x01(\x04R\vclassHandle\x12)\n" +
	"\x10parameter_handle\x18\x04 \x01(\x04R\x0fparameterHandle\"A\n" +
	"\x18GetParameterNameResponse\x12%\n" +
	"\x0eparameter_name\x18\x01 \x01(\tR\rparameterName\"\xa3\x01\n" +
	"\x19GetDimensionHandleRequest\x126\n" +
	"\fwire_version\x18\x01 \x01(\x0e2\x13.rti.v1.WireVersionR\vwireVersion\x12'\n" +
	"\x0ffederation_name\x18\x02 \x01(\tR\x0efederationName\x12%\n" +
	"\x0edimension_name\x18\x03 \x01(\tR\rdimensionName\"G\n" +
	"\x1aGetDimensionHandleResponse\x12)\n" +
	"\x10dimension_handle\x18\x01 \x01(\x04R\x0fdimensionHandle\"\xa5\x01\n" +
	"\x17GetDimensionNameRequest\x126\n" +
	"\fwire_version\x18\x01 \x01(\x0e2\x13.rti.v1.WireVersionR\vwireVersion\x12'\n" +
	"\x0ffederation_name\x18\x02 \x01(\tR\x0efederationName\x12)\n" +
	"\x10dimension_handle\x18\x03 \x01(\x04R\x0fdimensionHandle\"A\n" +
	"\x18GetDimensionNameResponse\x12%\n" +
	"\x0edimension_name\x18\x01 \x01(\tR\rdimensionName\"\xab\x01\n" +
	"\x1dGetDimensionUpperBoundRequest\x126\n" +
	"\fwire_version\x18\x01 \x01(\x0e2\x13.rti.v1.WireVersionR\vwireVersion\x12'\n" +
	"\x0ffederation_name\x18\x02 \x01(\tR\x0efederationName\x12)\n" +
	"\x10dimension_handle\x18\x03 \x01(\x04R\x0fdimensionHandle\"A\n" +
	"\x1eGetDimensionUpperBoundResponse\x12\x1f\n" +
	"\vupper_bound\x18\x01 \x01(\x04R\n" +
	"upperBound\"l\n" +
	"\x13GetOrderTypeRequest\x126\n" +
	"\fwire_version\x18\x01 \x01(\x0e2\x13.rti.v1.WireVersionR\vwireVersion\x12\x1d\n" +
	"\n" +
	"order_name\x18\x02 \x01(\tR\torderName\"5\n" +
	"\x14GetOrderTypeResponse\x12\x1d\n" +
	"\n" +
	"order_type\x18\x01 \x01(\rR\torderType\"l\n" +
	"\x13GetOrderNameRequest\x126\n" +
	"\fwire_version\x18\x01 \x01(\x0e2\x13.rti.v1.WireVersionR\vwireVersion\x12\x1d\n" +
	"\n" +
	"order_type\x18\x02 \x01(\rR\torderType\"5\n" +
	"\x14GetOrderNameResponse\x12\x1d\n" +
	"\n" +
	"order_name\x18\x01 \x01(\tR\torderName\"\x87\x01\n" +
	"\x1cGetTransportationTypeRequest\x126\n" +
	"\fwire_version\x18\x01 \x01(\x0e2\x13.rti.v1.WireVersionR\vwireVersion\x12/\n" +
	"\x13transportation_name\x18\x02 \x01(\tR\x12transportationName\"P\n" +
	"\x1dGetTransportationTypeResponse\x12/\n" +
	"\x13transportation_type\x18\x01 \x01(\rR\x12transportationType\"\x87\x01\n" +
	"\x1cGetTransportationNameRequest\x126\n" +
	"\fwire_version\x18\x01 \x01(\x0e2\x13.rti.v1.WireVersionR\vwireVersion\x12/\n" +
	"\x13transportation_type\x18\x02 \x01(\rR\x12transportationType\"P\n" +
	"\x1dGetTransportationNameResponse\x12/\n" +
	"\x13transportation_name\x18\x01 \x01(\tR\x12transportationName\"\xa2\x01\n" +
	"\x1eGetObjectInstanceHandleRequest\x126\n" +
	"\fwire_version\x18\x01 \x01(\x0e2\x13.rti.v1.WireVersionR\vwireVersion\x12'\n" +
	"\x0ffederation_name\x18\x02 \x01(\tR\x0efederationName\x12\x1f\n" +
	"\vobject_name\x18\x03 \x01(\tR\n" +
	"objectName\"F\n" +
	"\x1fGetObjectInstanceHandleResponse\x12#\n" +
	"\robject_handle\x18\x01 \x01(\x04R\fobjectHandle\"\xa4\x01\n" +
	"\x1cGetObjectInstanceNameRequest\x126\n" +
	"\fwire_version\x18\x01 \x01(\x0e2\x13.rti.v1.WireVersionR\vwireVersion\x12'\n" +
	"\x0ffederation_name\x18\x02 \x01(\tR\x0efederationName\x12#\n" +
	"\robject_handle\x18\x03 \x01(\x04R\fobjectHandle\"@\n" +
	"\x1dGetObjectInstanceNameResponse\x12\x1f\n" +
	"\vobject_name\x18\x01 \x01(\tR\n" +
	"objectName2\xe7\f\n" +
	"\x0eSupportService\x12a\n" +
	"\x14GetObjectClassHandle\x12#.rti.v1.GetObjectClassHandleRequest\x1a$.rti.v1.GetObjectClassHandleResponse\x12[\n" +
	"\x12GetObjectClassName\x12!.rti.v1.GetObjectClassNameRequest\x1a\".rti.v1.GetObjectClassNameResponse\x12[\n" +
	"\x12GetAttributeHandle\x12!.rti.v1.GetAttributeHandleRequest\x1a\".rti.v1.GetAttributeHandleResponse\x12U\n" +
	"\x10GetAttributeName\x12\x1f.rti.v1.GetAttributeNameRequest\x1a .rti.v1.GetAttributeNameResponse\x12p\n" +
	"\x19GetInteractionClassHandle\x12(.rti.v1.GetInteractionClassHandleRequest\x1a).rti.v1.GetInteractionClassHandleResponse\x12j\n" +
	"\x17GetInteractionClassName\x12&.rti.v1.GetInteractionClassNameRequest\x1a'.rti.v1.GetInteractionClassNameResponse\x12[\n" +
	"\x12GetParameterHandle\x12!.rti.v1.GetParameterHandleRequest\x1a\".rti.v1.GetParameterHandleResponse\x12U\n" +
	"\x10GetParameterName\x12\x1f.rti.v1.GetParameterNameRequest\x1a .rti.v1.GetParameterNameResponse\x12[\n" +
	"\x12GetDimensionHandle\x12!.rti.v1.GetDimensionHandleRequest\x1a\".rti.v1.GetDimensionHandleResponse\x12U\n" +
	"\x10GetDimensionName\x12\x1f.rti.v1.GetDimensionNameRequest\x1a .rti.v1.GetDimensionNameResponse\x12g\n" +
	"\x16GetDimensionUpperBound\x12%.rti.v1.GetDimensionUpperBoundRequest\x1a&.rti.v1.GetDimensionUpperBoundResponse\x12I\n" +
	"\fGetOrderType\x12\x1b.rti.v1.GetOrderTypeRequest\x1a\x1c.rti.v1.GetOrderTypeResponse\x12I\n" +
	"\fGetOrderName\x12\x1b.rti.v1.GetOrderNameRequest\x1a\x1c.rti.v1.GetOrderNameResponse\x12d\n" +
	"\x15GetTransportationType\x12$.rti.v1.GetTransportationTypeRequest\x1a%.rti.v1.GetTransportationTypeResponse\x12d\n" +
	"\x15GetTransportationName\x12$.rti.v1.GetTransportationNameRequest\x1a%.rti.v1.GetTransportationNameResponse\x12j\n" +
	"\x17GetObjectInstanceHandle\x12&.rti.v1.GetObjectInstanceHandleRequest\x1a'.rti.v1.GetObjectInstanceHandleResponse\x12d\n" +
	"\x15GetObjectInstanceName\x12$.rti.v1.GetObjectInstanceNameRequest\x1a%.rti.v1.GetObjectInstanceNameResponseB<Z:github.com/cbchoi/gorti/rti/internal/genproto/rti/v1;rtiv1b\x06proto3"

var (
	file_rti_v1_support_proto_rawDescOnce sync.Once
	file_rti_v1_support_proto_rawDescData []byte
)

func file_rti_v1_support_proto_rawDescGZIP() []byte {
	file_rti_v1_support_proto_rawDescOnce.Do(func() {
		file_rti_v1_support_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rti_v1_support_proto_rawDesc), len(file_rti_v1_support_proto_rawDesc)))
	})
	return file_rti_v1_support_proto_rawDescData
}

var file_rti_v1_support_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_rti_v1_support_proto_goTypes = []any{
	(*GetObjectClassHandleRequest)(nil),       // 0: rti.v1.GetObjectClassHandleRequest
	(*GetObjectClassHandleResponse)(nil),      // 1: rti.v1.GetObjectClassHandleResponse
	(*GetObjectClassNameRequest)(nil),         // 2: rti.v1.GetObjectClassNameRequest
	(*GetObjectClassNameResponse)(nil),        // 3: rti.v1.GetObjectClassNameResponse
	(*GetAttributeHandleRequest)(nil),         // 4: rti.v1.GetAttributeHandleRequest
	(*GetAttributeHandleResponse)(nil),        // 5: rti.v1.GetAttributeHandleResponse
	(*GetAttributeNameRequest)(nil),           // 6: rti.v1.GetAttributeNameRequest
	(*GetAttributeNameResponse)(nil),          // 7: rti.v1.GetAttributeNameResponse
	(*GetInteractionClassHandleRequest)(nil),  // 8: rti.v1.GetInteractionClassHandleRequest
	(*GetInteractionClassHandleResponse)(nil), // 9: rti.v1.GetInteractionClassHandleResponse
	(*GetInteractionClassNameRequest)(nil),    // 10: rti.v1.GetInteractionClassNameRequest
	(*GetInteractionClassNameResponse)(nil),   // 11: rti.v1.GetInteractionClassNameResponse
	(*GetParameterHandleRequest)(nil),         // 12: rti.v1.GetParameterHandleRequest
	(*GetParameterHandleResponse)(nil),        // 13: rti.v1.GetParameterHandleResponse
	(*GetParameterNameRequest)(nil),           // 14: rti.v1.GetParameterNameRequest
	(*GetParameterNameResponse)(nil),          // 15: rti.v1.GetParameterNameResponse
	(*GetDimensionHandleRequest)(nil),         // 16: rti.v1.GetDimensionHandleRequest
	(*GetDimensionHandleResponse)(nil),        // 17: rti.v1.GetDimensionHandleResponse
	(*GetDimensionNameRequest)(nil),           // 18: rti.v1.GetDimensionNameRequest
	(*GetDimensionNameResponse)(nil),          // 19: rti.v1.GetDimensionNameResponse
	(*GetDimensionUpperBoundRequest)(nil),     // 20: rti.v1.GetDimensionUpperBoundRequest
	(*GetDimensionUpperBoundResponse)(nil),    // 21: rti.v1.GetDimensionUpperBoundResponse
	(*GetOrderTypeRequest)(nil),               // 22: rti.v1.GetOrderTypeRequest
	(*GetOrderTypeResponse)(nil),              // 23: rti.v1.GetOrderTypeResponse
	(*GetOrderNameRequest)(nil),               // 24: rti.v1.GetOrderNameRequest
	(*GetOrderNameResponse)(nil),              // 25: rti.v1.GetOrderNameResponse
	(*GetTransportationTypeRequest)(nil),      // 26: rti.v1.GetTransportationTypeRequest
	(*GetTransportationTypeResponse)(nil),     // 27: rti.v1.GetTransportationTypeResponse
	(*GetTransportationNameRequest)(nil),      // 28: rti.v1.GetTransportationNameRequest
	(*GetTransportationNameResponse)(nil),     // 29: rti.v1.GetTransportationNameResponse
	(*GetObjectInstanceHandleRequest)(nil),    // 30: rti.v1.GetObjectInstanceHandleRequest
	(*GetObjectInstanceHandleResponse)(nil),   // 31: rti.v1.GetObjectInstanceHandleResponse
	(*GetObjectInstanceNameRequest)(nil),      // 32: rti.v1.GetObjectInstanceNameRequest
	(*GetObjectInstanceNameResponse)(nil),     // 33: rti.v1.GetObjectInstanceNameResponse
	(WireVersion)(0),                          // 34: rti.v1.WireVersion
}
var file_rti_v1_support_proto_depIdxs = []int32{
	34, // 0: rti.v1.GetObjectClassHandleRequest.wire_version:type_name -> rti.v1.WireVersion
	34, // 1: rti.v1.GetObjectClassNameRequest.wire_version:type_name -> rti.v1.WireVersion
	34, // 2: rti.v1.GetAttributeHandleRequest.wire_version:type_name -> rti.v1.WireVersion
	34, // 3: rti.v1.GetAttributeNameRequest.wire_version:type_name -> rti.v1.WireVersion
	34, // 4: rti.v1.GetInteractionClassHandleRequest.wire_version:type_name -> rti.v1.WireVersion
	34, // 5: rti.v1.GetInteractionClassNameRequest.wire_version:type_name -> rti.v1.WireVersion
	34, // 6: rti.v1.GetParameterHandleRequest.wire_version:type_name -> rti.v1.WireVersion
	34, // 7: rti.v1.GetParameterNameRequest.wire_version:type_name -> rti.v1.WireVersion
	34, // 8: rti.v1.GetDimensionHandleRequest.wire_version:type_name -> rti.v1.WireVersion
	34, // 9: rti.v1.GetDimensionNameRequest.wire_version:type_name -> rti.v1.WireVersion
	34, // 10: rti.v1.GetDimensionUpperBoundRequest.wire_version:type_name -> rti.v1.WireVersion
	34, // 11: rti.v1.GetOrderTypeRequest.wire_version:type_name -> rti.v1.WireVersion
	34, // 12: rti.v1.GetOrderNameRequest.wire_version:type_name -> rti.v1.WireVersion
	34, // 13: rti.v1.GetTransportationTypeRequest.wire_version:type_name -> rti.v1.WireVersion
	34, // 14: rti.v1.GetTransportationNameRequest.wire_version:type_name -> rti.v1.WireVersion
	34, // 15: rti.v1.GetObjectInstanceHandleRequest.wire_version:type_name -> rti.v1.WireVersion
	34, // 16: rti.v1.GetObjectInstanceNameRequest.wire_version:type_name -> rti.v1.WireVersion
	0,  // 17: rti.v1.SupportService.GetObjectClassHandle:input_type -> rti.v1.GetObjectClassHandleRequest
	2,  // 18: rti.v1.SupportService.GetObjectClassName:input_type -> rti.v1.GetObjectClassNameRequest
	4,  // 19: rti.v1.SupportService.GetAttributeHandle:input_type -> rti.v1.GetAttributeHandleRequest
	6,  // 20: rti.v1.SupportService.GetAttributeName:input_type -> rti.v1.GetAttributeNameRequest
	8,  // 21: rti.v1.SupportService.GetInteractionClassHandle:input_type -> rti.v1.GetInteractionClassHandleRequest
	10, // 22: rti.v1.SupportService.GetInteractionClassName:input_type -> rti.v1.GetInteractionClassNameRequest
	12, // 23: rti.v1.SupportService.GetParameterHandle:input_type -> rti.v1.GetParameterHandleRequest
	14, // 24: rti.v1.SupportService.GetParameterName:input_type -> rti.v1.GetParameterNameRequest
	16, // 25: rti.v1.SupportService.GetDimensionHandle:input_type -> rti.v1.GetDimensionHandleRequest
	18, // 26: rti.v1.SupportService.GetDimensionName:input_type -> rti.v1.GetDimensionNameRequest
	20, // 27: rti.v1.SupportService.GetDimensionUpperBound:input_type -> rti.v1.GetDimensionUpperBoundRequest
	22, // 28: rti.v1.SupportService.GetOrderType:input_type -> rti.v1.GetOrderTypeRequest
	24, // 29: rti.v1.SupportService.GetOrderName:input_type -> rti.v1.GetOrderNameRequest
	26, // 30: rti.v1.SupportService.GetTransportationType:input_type -> rti.v1.GetTransportationTypeRequest
	28, // 31: rti.v1.SupportService.GetTransportationName:input_type -> rti.v1.GetTransportationNameRequest
	30, // 32: rti.v1.SupportService.GetObjectInstanceHandle:input_type -> rti.v1.GetObjectInstanceHandleRequest
	32, // 33: rti.v1.SupportService.GetObjectInstanceName:input_type -> rti.v1.GetObjectInstanceNameRequest
	1,  // 34: rti.v1.SupportService.GetObjectClassHandle:output_type -> rti.v1.GetObjectClassHandleResponse
	3,  // 35: rti.v1.SupportService.GetObjectClassName:output_type -> rti.v1.GetObjectClassNameResponse
	5,  // 36: rti.v1.SupportService.GetAttributeHandle:output_type -> rti.v1.GetAttributeHandleResponse
	7,  // 37: rti.v1.SupportService.GetAttributeName:output_type -> rti.v1.GetAttributeNameResponse
	9,  // 38: rti.v1.SupportService.GetInteractionClassHandle:output_type -> rti.v1.GetInteractionClassHandleResponse
	11, // 39: rti.v1.SupportService.GetInteractionClassName:output_type -> rti.v1.GetInteractionClassNameResponse
	13, // 40: rti.v1.SupportService.GetParameterHandle:output_type -> rti.v1.GetParameterHandleResponse
	15, // 41: rti.v1.SupportService.GetParameterName:output_type -> rti.v1.GetParameterNameResponse
	17, // 42: rti.v1.SupportService.GetDimensionHandle:output_type -> rti.v1.GetDimensionHandleResponse
	19, // 43: rti.v1.SupportService.GetDimensionName:output_type -> rti.v1.GetDimensionNameResponse
	21, // 44: rti.v1.SupportService.GetDimensionUpperBound:output_type -> rti.v1.GetDimensionUpperBoundResponse
	23, // 45: rti.v1.SupportService.GetOrderType:output_type -> rti.v1.GetOrderTypeResponse
	25, // 46: rti.v1.SupportService.GetOrderName:output_type -> rti.v1.GetOrderNameResponse
	27, // 47: rti.v1.SupportService.GetTransportationType:output_type -> rti.v1.GetTransportationTypeResponse
	29, // 48: rti.v1.SupportService.GetTransportationName:output_type -> rti.v1.GetTransportationNameResponse
	31, // 49: rti.v1.SupportService.GetObjectInstanceHandle:output_type -> rti.v1.GetObjectInstanceHandleResponse
	33, // 50: rti.v1.SupportService.GetObjectInstanceName:output_type -> rti.v1.GetObjectInstanceNameResponse
	34, // [34:51] is the sub-list for method output_type
	17, // [17:34] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_rti_v1_support_proto_init() }
func file_rti_v1_support_proto_init() {
	if File_rti_v1_support_proto != nil {
		return
	}
	file_rti_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rti_v1_support_proto_rawDesc), len(file_rti_v1_support_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rti_v1_support_proto_goTypes,
		DependencyIndexes: file_rti_v1_support_proto_depIdxs,
		MessageInfos:      file_rti_v1_support_proto_msgTypes,
	}.Build()
	File_rti_v1_support_proto = out.File
	file_rti_v1_support_proto_goTypes = nil
	file_rti_v1_support_proto_depIdxs = nil
}
