// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: rti/v1/sync.proto

package rtiv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SyncService_RegisterFederationSynchronizationPoint_FullMethodName = "/rti.v1.SyncService/RegisterFederationSynchronizationPoint"
	SyncService_SynchronizationPointAchieved_FullMethodName           = "/rti.v1.SyncService/SynchronizationPointAchieved"
)

// SyncServiceClient is the client API for SyncService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SyncService — Synchronization Management per IEEE 1516.1-2010 §4.6-4.7.
// Cut-3 (M12) gRPC exposure of cut-2 sync.Manager.
type SyncServiceClient interface {
	RegisterFederationSynchronizationPoint(ctx context.Context, in *RegisterSyncPointRequest, opts ...grpc.CallOption) (*Empty, error)
	SynchronizationPointAchieved(ctx context.Context, in *AchieveSyncPointRequest, opts ...grpc.CallOption) (*Empty, error)
}

type syncServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSyncServiceClient(cc grpc.ClientConnInterface) SyncServiceClient {
	return &syncServiceClient{cc}
}

func (c *syncServiceClient) RegisterFederationSynchronizationPoint(ctx context.Context, in *RegisterSyncPointRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, SyncService_RegisterFederationSynchronizationPoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncServiceClient) SynchronizationPointAchieved(ctx context.Context, in *AchieveSyncPointRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, SyncService_SynchronizationPointAchieved_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SyncServiceServer is the server API for SyncService service.
// All implementations must embed UnimplementedSyncServiceServer
// for forward compatibility.
//
// SyncService — Synchronization Management per IEEE 1516.1-2010 §4.6-4.7.
// Cut-3 (M12) gRPC exposure of cut-2 sync.Manager.
type SyncServiceServer interface {
	RegisterFederationSynchronizationPoint(context.Context, *RegisterSyncPointRequest) (*Empty, error)
	SynchronizationPointAchieved(context.Context, *AchieveSyncPointRequest) (*Empty, error)
	mustEmbedUnimplementedSyncServiceServer()
}

// UnimplementedSyncServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSyncServiceServer struct{}

func (UnimplementedSyncServiceServer) RegisterFederationSynchronizationPoint(context.Context, *RegisterSyncPointRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterFederationSynchronizationPoint not implemented")
}
func (UnimplementedSyncServiceServer) SynchronizationPointAchieved(context.Context, *AchieveSyncPointRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SynchronizationPointAchieved not implemented")
}
func (UnimplementedSyncServiceServer) mustEmbedUnimplementedSyncServiceServer() {}
func (UnimplementedSyncServiceServer) testEmbeddedByValue()                     {}

// UnsafeSyncServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SyncServiceServer will
// result in compilation errors.
type UnsafeSyncServiceServer interface {
	mustEmbedUnimplementedSyncServiceServer()
}

func RegisterSyncServiceServer(s grpc.ServiceRegistrar, srv SyncServiceServer) {
	// If the following call panics, it indicates UnimplementedSyncServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SyncService_ServiceDesc, srv)
}

func _SyncService_RegisterFederationSynchronizationPoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterSyncPointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncServiceServer).RegisterFederationSynchronizationPoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncService_RegisterFederationSynchronizationPoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncServiceServer).RegisterFederationSynchronizationPoint(ctx, req.(*RegisterSyncPointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncService_SynchronizationPointAchieved_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AchieveSyncPointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncServiceServer).SynchronizationPointAchieved(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncService_SynchronizationPointAchieved_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncServiceServer).SynchronizationPointAchieved(ctx, req.(*AchieveSyncPointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SyncService_ServiceDesc is the grpc.ServiceDesc for SyncService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SyncService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rti.v1.SyncService",
	HandlerType: (*SyncServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterFederationSynchronizationPoint",
			Handler:    _SyncService_RegisterFederationSynchronizationPoint_Handler,
		},
		{
			MethodName: "SynchronizationPointAchieved",
			Handler:    _SyncService_SynchronizationPointAchieved_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rti/v1/sync.proto",
}
