// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: rti/v1/sync.proto

package rtiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SyncPointSnapshotState — used inside SyncManagerState for the
// runtime state of one sync point. Distinct from the AdminService
// SyncPointState enum (admin.proto) so the two enums can evolve
// independently.
type SyncPointSnapshotState int32

const (
	SyncPointSnapshotState_SYNC_POINT_SNAPSHOT_STATE_UNSPECIFIED SyncPointSnapshotState = 0
	SyncPointSnapshotState_SYNC_POINT_SNAPSHOT_STATE_ANNOUNCED   SyncPointSnapshotState = 1
	SyncPointSnapshotState_SYNC_POINT_SNAPSHOT_STATE_ACHIEVED    SyncPointSnapshotState = 2
)

// Enum value maps for SyncPointSnapshotState.
var (
	SyncPointSnapshotState_name = map[int32]string{
		0: "SYNC_POINT_SNAPSHOT_STATE_UNSPECIFIED",
		1: "SYNC_POINT_SNAPSHOT_STATE_ANNOUNCED",
		2: "SYNC_POINT_SNAPSHOT_STATE_ACHIEVED",
	}
	SyncPointSnapshotState_value = map[string]int32{
		"SYNC_POINT_SNAPSHOT_STATE_UNSPECIFIED": 0,
		"SYNC_POINT_SNAPSHOT_STATE_ANNOUNCED":   1,
		"SYNC_POINT_SNAPSHOT_STATE_ACHIEVED":    2,
	}
)

func (x SyncPointSnapshotState) Enum() *SyncPointSnapshotState {
	p := new(SyncPointSnapshotState)
	*p = x
	return p
}

func (x SyncPointSnapshotState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SyncPointSnapshotState) Descriptor() protoreflect.EnumDescriptor {
	return file_rti_v1_sync_proto_enumTypes[0].Descriptor()
}

func (SyncPointSnapshotState) Type() protoreflect.EnumType {
	return &file_rti_v1_sync_proto_enumTypes[0]
}

func (x SyncPointSnapshotState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SyncPointSnapshotState.Descriptor instead.
func (SyncPointSnapshotState) EnumDescriptor() ([]byte, []int) {
	return file_rti_v1_sync_proto_rawDescGZIP(), []int{0}
}

type RegisterSyncPointRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WireVersion    WireVersion            `protobuf:"varint,1,opt,name=wire_version,json=wireVersion,proto3,enum=rti.v1.WireVersion" json:"wire_version,omitempty"`
	FederationName string                 `protobuf:"bytes,2,opt,name=federation_name,json=federationName,proto3" json:"federation_name,omitempty"`
	FederateHandle uint64                 `protobuf:"varint,3,opt,name=federate_handle,json=federateHandle,proto3" json:"federate_handle,omitempty"` // who's registering
	Label          string                 `protobuf:"bytes,4,opt,name=label,proto3" json:"label,omitempty"`
	Tag            []byte                 `protobuf:"bytes,5,opt,name=tag,proto3" json:"tag,omitempty"` // opaque user data echoed in announce callback
	// Optional explicit set; nil/empty = all currently joined federates.
	RequiredFederates []uint64 `protobuf:"varint,6,rep,packed,name=required_federates,json=requiredFederates,proto3" json:"required_federates,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RegisterSyncPointRequest) Reset() {
	*x = RegisterSyncPointRequest{}
	mi := &file_rti_v1_sync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterSyncPointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterSyncPointRequest) ProtoMessage() {}

func (x *RegisterSyncPointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_sync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterSyncPointRequest.ProtoReflect.Descriptor instead.
func (*RegisterSyncPointRequest) Descriptor() ([]byte, []int) {
	return file_rti_v1_sync_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterSyncPointRequest) GetWireVersion() WireVersion {
	if x != nil {
		return x.WireVersion
	}
	return WireVersion_WIRE_VERSION_UNSPECIFIED
}

func (x *RegisterSyncPointRequest) GetFederationName() string {
	if x != nil {
		return x.FederationName
	}
	return ""
}

func (x *RegisterSyncPointRequest) GetFederateHandle() uint64 {
	if x != nil {
		return x.FederateHandle
	}
	return 0
}

func (x *RegisterSyncPointRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *RegisterSyncPointRequest) GetTag() []byte {
	if x != nil {
		return x.Tag
	}
	return nil
}

func (x *RegisterSyncPointRequest) GetRequiredFederates() []uint64 {
	if x != nil {
		return x.RequiredFederates
	}
	return nil
}

type AchieveSyncPointRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WireVersion    WireVersion            `protobuf:"varint,1,opt,name=wire_version,json=wireVersion,proto3,enum=rti.v1.WireVersion" json:"wire_version,omitempty"`
	FederationName string                 `protobuf:"bytes,2,opt,name=federation_name,json=federationName,proto3" json:"federation_name,omitempty"`
	FederateHandle uint64                 `protobuf:"varint,3,opt,name=federate_handle,json=federateHandle,proto3" json:"federate_handle,omitempty"`
	Label          string                 `protobuf:"bytes,4,opt,name=label,proto3" json:"label,omitempty"`
	// IEEE 1516.1-2010 §4.14 synchronizationPointAchieved(label,
	// successfully). Absent (old clients) means TRUE — the federate
	// achieved the point successfully. When false the federate still
	// counts toward sync completion but is reported in the §4.15
	// FederationSynchronized.failed_to_sync set. M37.
	// (additive, tag 5).
	Successfully  *bool `protobuf:"varint,5,opt,name=successfully,proto3,oneof" json:"successfully,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AchieveSyncPointRequest) Reset() {
	*x = AchieveSyncPointRequest{}
	mi := &file_rti_v1_sync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AchieveSyncPointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AchieveSyncPointRequest) ProtoMessage() {}

func (x *AchieveSyncPointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_sync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AchieveSyncPointRequest.ProtoReflect.Descriptor instead.
func (*AchieveSyncPointRequest) Descriptor() ([]byte, []int) {
	return file_rti_v1_sync_proto_rawDescGZIP(), []int{1}
}

func (x *AchieveSyncPointRequest) GetWireVersion() WireVersion {
	if x != nil {
		return x.WireVersion
	}
	return WireVersion_WIRE_VERSION_UNSPECIFIED
}

func (x *AchieveSyncPointRequest) GetFederationName() string {
	if x != nil {
		return x.FederationName
	}
	return ""
}

func (x *AchieveSyncPointRequest) GetFederateHandle() uint64 {
	if x != nil {
		return x.FederateHandle
	}
	return 0
}

func (x *AchieveSyncPointRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *AchieveSyncPointRequest) GetSuccessfully() bool {
	if x != nil && x.Successfully != nil {
		return *x.Successfully
	}
	return false
}

// SyncPointStateEntry is one (label → record) entry in
// SyncManagerState.points. Carries only fields that change at
// runtime — setup-time configuration (the federation name itself)
// lives on the manifest.
type SyncPointStateEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Tag           []byte                 `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	State         SyncPointSnapshotState `protobuf:"varint,3,opt,name=state,proto3,enum=rti.v1.SyncPointSnapshotState" json:"state,omitempty"`
	Required      []uint64               `protobuf:"varint,4,rep,packed,name=required,proto3" json:"required,omitempty"` // sorted ascending
	Achieved      []uint64               `protobuf:"varint,5,rep,packed,name=achieved,proto3" json:"achieved,omitempty"` // sorted ascending
	Dynamic       bool                   `protobuf:"varint,6,opt,name=dynamic,proto3" json:"dynamic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncPointStateEntry) Reset() {
	*x = SyncPointStateEntry{}
	mi := &file_rti_v1_sync_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncPointStateEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncPointStateEntry) ProtoMessage() {}

func (x *SyncPointStateEntry) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_sync_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncPointStateEntry.ProtoReflect.Descriptor instead.
func (*SyncPointStateEntry) Descriptor() ([]byte, []int) {
	return file_rti_v1_sync_proto_rawDescGZIP(), []int{2}
}

func (x *SyncPointStateEntry) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *SyncPointStateEntry) GetTag() []byte {
	if x != nil {
		return x.Tag
	}
	return nil
}

func (x *SyncPointStateEntry) GetState() SyncPointSnapshotState {
	if x != nil {
		return x.State
	}
	return SyncPointSnapshotState_SYNC_POINT_SNAPSHOT_STATE_UNSPECIFIED
}

func (x *SyncPointStateEntry) GetRequired() []uint64 {
	if x != nil {
		return x.Required
	}
	return nil
}

func (x *SyncPointStateEntry) GetAchieved() []uint64 {
	if x != nil {
		return x.Achieved
	}
	return nil
}

func (x *SyncPointStateEntry) GetDynamic() bool {
	if x != nil {
		return x.Dynamic
	}
	return false
}

// SyncManagerState is the per-federation snapshot persisted into the
// save manifest's manager_snapshots map under key "sync".
// M13 thread C (docs/srs.md §10.4): structured save bundle.
//
// On Marshal, every active sync point in the federation is serialized
// in label-sorted order so the bytes are determinism-stable. On
// Unmarshal, the manager replaces the federation's sync state with
// the bundled set (additive — the manager is empty pre-Unmarshal in
// the production restore-bootstrap path).
type SyncManagerState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Points        []*SyncPointStateEntry `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncManagerState) Reset() {
	*x = SyncManagerState{}
	mi := &file_rti_v1_sync_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncManagerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncManagerState) ProtoMessage() {}

func (x *SyncManagerState) ProtoReflect() protoreflect.Message {
	mi := &file_rti_v1_sync_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncManagerState.ProtoReflect.Descriptor instead.
func (*SyncManagerState) Descriptor() ([]byte, []int) {
	return file_rti_v1_sync_proto_rawDescGZIP(), []int{3}
}

func (x *SyncManagerState) GetPoints() []*SyncPointStateEntry {
	if x != nil {
		return x.Points
	}
	return nil
}

var File_rti_v1_sync_proto protoreflect.FileDescriptor

const file_rti_v1_sync_proto_rawDesc = "" +
	"\n" +
	"\x11rti/v1/sync.proto\x12\x06rti.v1\x1a\x13rti/v1/common.proto\"\xfb\x01\n" +
	"\x18RegisterSyncPointRequest\x126\n" +
	"\fwire_version\x18\x01 \x01(\x0e2\x13.rti.v1.WireVersionR\vwireVersion\x12'\n" +
	"\x0ffederation_name\x18\x02 \x01(\tR\x0efederationName\x12'\n" +
	"\x0ffederate_handle\x18\x03 \x01(\x04R\x0efederateHandle\x12\x14\n" +
	"\x05label\x18\x04 \x01(\tR\x05label\x12\x10\n" +
	"\x03tag\x18\x05 \x01(\fR\x03tag\x12-\n" +
	"\x12required_federates\x18\x06 \x03(\x04R\x11requiredFederates\"\xf3\x01\n" +
	"\x17AchieveSyncPointRequest\x126\n" +
	"\fwire_version\x18\x01 \x01(\x0e2\x13.rti.v1.WireVersionR\vwireVersion\x12'\n" +
	"\x0ffederation_name\x18\x02 \x01(\tR\x0efederationName\x12'\n" +
	"\x0ffederate_handle\x18\x03 \x01(\x04R\x0efederateHandle\x12\x14\n" +
	"\x05label\x18\x04 \x01(\tR\x05label\x12'\n" +
	"\fsuccessfully\x18\x05 \x01(\bH\x00R\fsuccessfully\x88\x01\x01B\x0f\n" +
	"\r_successfully\"\xc5\x01\n" +
	"\x13SyncPointStateEntry\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x10\n" +
	"\x03tag\x18\x02 \x01(\fR\x03tag\x124\n" +
	"\x05state\x18\x03 \x01(\x0e2\x1e.rti.v1.SyncPointSnapshotStateR\x05state\x12\x1a\n" +
	"\brequired\x18\x04 \x03(\x04R\brequired\x12\x1a\n" +
	"\bachieved\x18\x05 \x03(\x04R\bachieved\x12\x18\n" +
	"\adynamic\x18\x06 \x01(\bR\adynamic\"G\n" +
	"\x10SyncManagerState\x123\n" +
	"\x06points\x18\x01 \x03(\v2\x1b.rti.v1.SyncPointStateEntryR\x06points*\x94\x01\n" +
	"\x16SyncPointSnapshotState\x12)\n" +
	"%SYNC_POINT_SNAPSHOT_STATE_UNSPECIFIED\x10\x00\x12'\n" +
	"#SYNC_POINT_SNAPSHOT_STATE_ANNOUNCED\x10\x01\x12&\n" +
	"\"SYNC_POINT_SNAPSHOT_STATE_ACHIEVED\x10\x022\xb8\x01\n" +
	"\vSyncService\x12Y\n" +
	"&RegisterFederationSynchronizationPoint\x12 .rti.v1.RegisterSyncPointRequest\x1a\r.rti.v1.Empty\x12N\n" +
	"\x1cSynchronizationPointAchieved\x12\x1f.rti.v1.AchieveSyncPointRequest\x1a\r.rti.v1.EmptyB<Z:github.com/cbchoi/gorti/rti/internal/genproto/rti/v1;rtiv1b\x06proto3"

var (
	file_rti_v1_sync_proto_rawDescOnce sync.Once
	file_rti_v1_sync_proto_rawDescData []byte
)

func file_rti_v1_sync_proto_rawDescGZIP() []byte {
	file_rti_v1_sync_proto_rawDescOnce.Do(func() {
		file_rti_v1_sync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rti_v1_sync_proto_rawDesc), len(file_rti_v1_sync_proto_rawDesc)))
	})
	return file_rti_v1_sync_proto_rawDescData
}

var file_rti_v1_sync_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_rti_v1_sync_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_rti_v1_sync_proto_goTypes = []any{
	(SyncPointSnapshotState)(0),      // 0: rti.v1.SyncPointSnapshotState
	(*RegisterSyncPointRequest)(nil), // 1: rti.v1.RegisterSyncPointRequest
	(*AchieveSyncPointRequest)(nil),  // 2: rti.v1.AchieveSyncPointRequest
	(*SyncPointStateEntry)(nil),      // 3: rti.v1.SyncPointStateEntry
	(*SyncManagerState)(nil),         // 4: rti.v1.SyncManagerState
	(WireVersion)(0),                 // 5: rti.v1.WireVersion
	(*Empty)(nil),                    // 6: rti.v1.Empty
}
var file_rti_v1_sync_proto_depIdxs = []int32{
	5, // 0: rti.v1.RegisterSyncPointRequest.wire_version:type_name -> rti.v1.WireVersion
	5, // 1: rti.v1.AchieveSyncPointRequest.wire_version:type_name -> rti.v1.WireVersion
	0, // 2: rti.v1.SyncPointStateEntry.state:type_name -> rti.v1.SyncPointSnapshotState
	3, // 3: rti.v1.SyncManagerState.points:type_name -> rti.v1.SyncPointStateEntry
	1, // 4: rti.v1.SyncService.RegisterFederationSynchronizationPoint:input_type -> rti.v1.RegisterSyncPointRequest
	2, // 5: rti.v1.SyncService.SynchronizationPointAchieved:input_type -> rti.v1.AchieveSyncPointRequest
	6, // 6: rti.v1.SyncService.RegisterFederationSynchronizationPoint:output_type -> rti.v1.Empty
	6, // 7: rti.v1.SyncService.SynchronizationPointAchieved:output_type -> rti.v1.Empty
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_rti_v1_sync_proto_init() }
func file_rti_v1_sync_proto_init() {
	if File_rti_v1_sync_proto != nil {
		return
	}
	file_rti_v1_common_proto_init()
	file_rti_v1_sync_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rti_v1_sync_proto_rawDesc), len(file_rti_v1_sync_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rti_v1_sync_proto_goTypes,
		DependencyIndexes: file_rti_v1_sync_proto_depIdxs,
		EnumInfos:         file_rti_v1_sync_proto_enumTypes,
		MessageInfos:      file_rti_v1_sync_proto_msgTypes,
	}.Build()
	File_rti_v1_sync_proto = out.File
	file_rti_v1_sync_proto_goTypes = nil
	file_rti_v1_sync_proto_depIdxs = nil
}
